### ISSUE TITLE
popupGraph in Mapview is no longer working on R 3.4.1

### ISSUE THREAD

**Issue by WTang123** [r-spatial/mapview#100]
Hi there,

The demonstration code for Mapview (as attached below) was working before I upgraded to R 3.4.1.
```r
data(meuse)
coordinates(meuse) <- ~ x + y
proj4string(meuse) <- CRS("+init=epsg:28992")

## create plots with points colored according to feature id
p <- xyplot(copper ~ cadmium, data = meuse@data, col = "grey")
p <- mget(rep("p", length(meuse)))

clr <- rep("grey", length(meuse))
p <- lapply(1:length(p), function(i) {
  clr[i] <- "red"
  update(p[[i]], col = clr)
})

mapview(meuse, popup = popupGraph(p, type = "svg", width = 3, height = 2.5))
```
The graph is no longer popped up, instead there is an empty bubble box.

Unfortunately it appears that I couldn't attach snapshot here - but I am wondering if anyone has had a similar problem?

**Comment by tim-salabim** [comment]
There has been an update to the way `width` and `height` are handled internally. These arguments now expect values in pixel units (used to be inches for `type = "svg"`. Thus, with proper values (defaults are `width = 300, height = 300`) the rendering will be as expected.
```r
library(sp)
library(mapview)
library(latice)

data(meuse)
coordinates(meuse) = ~ x + y
proj4string(meuse) = CRS("+init=epsg:28992")

## create plots with points colored according to feature id
p = xyplot(copper ~ cadmium, data = meuse@data, col = "grey")
p = mget(rep("p", length(meuse)))

clr = rep("grey", length(meuse))
p = lapply(1:length(p), function(i) {
  clr[i] = "red"
  update(p[[i]], col = clr)
})

mapview(meuse, popup = popupGraph(p, type = "svg"))
```
In version `2.1.7` of the package the examples have been updated accordingly.

**Comment by WTang123** [comment]
This is great - thank you for your help, Tim!
