### ISSUE TITLE
Different problems with different versions

### ISSUE THREAD

**Issue by carlocav** [r-spatial/mapview#102]
With release 2.1.10 downloaded from GitHub when overlapping a raster layer with a SpatialPointsDataFrame I get this error
```
Error in UseMethod("st_bbox") : 
  no applicable method for 'st_bbox' applied to an object of class "c('SpatialPixelsDataFrame', 'SpatialPixels', 'SpatialPointsDataFrame', 'SpatialPoints', 'Spatial', 'SpatialVector')"
```
I get the same error with `mapview(list(franconia, breweries)) + poppendorf[[5]]`

Instead, with release 2.1.04 downloaded from Cran the color palette on the spatial points data frame doesn't work

I have Mac OS 10.13 and GDAL 2.1.x

**Comment by tim-salabim** [comment]
The easiest way to get this working again is to install package sf from github too. The newest version has `st_bbox` methods for both sp and raster objects.

**Comment by carlocav** [comment]
Thank you!
