### ISSUE TITLE
Plotting error when POLYGON EMPTY 

### ISSUE THREAD

**Issue by ghiggi** [r-spatial/mapview#107]
Hey,
mapview() is not able to display empty simple features.

For examples: 
`library(sf)`
`a <- st_polygon()`
`mapview(a)`

It's quite a big issue because when you have a sf object, with some sfg that are EMPTY, then mapview() throw the following error:
`Error in x[[1]] : subscript out of bounds`.

In any case, when sfg is GEOMETRYCOLLECTION EMPTY, the error does not appear ;)

**Comment by edzer** [comment]
`is.na(st_dimension(x))` selects empty geometries.

**Comment by ghiggi** [comment]
I precisely used this  to make mapview work:
`sf_db <- sf_db[!is.na(st_dimension(upstream_catchments)),]`
`mapview(sf_db)`
However I think it would be much useful to deal with these geometries internally in the mapview function.
Cheers

**Comment by tim-salabim** [comment]
First of all, thanks for raising this issue. It made me realise a few things regarding a widespread misuse of `st_cast` (which was the reason for the error message you received). This should be fixed now in 01b17c0e685a632fb7bcfb2c2671a34f92346a4d, meaning that a `sfc_GEOMETRY` with some empty geometries (though not all empty) should not fail anymore.

That aside, I am not really convinced that mapview should handle such things. What exactly are you expecting mapview to do when passing an empty `sfg` (as in your example above)? There's no geometry to plot. `plot.sf` fails just as bad as mapview given that there is nothing there that can be plotted.

**Comment by edzer** [comment]
Please provide a repres for that last claim as an issue on sf. Empty geoms should be ignored by plot; think of them as NA value, as in `plot(c(1,NA,2),c(3,NA,5))`.

**Comment by tim-salabim** [comment]
```r
> library(sf)
Linking to GEOS 3.5.1, GDAL 2.2.1, proj.4 4.9.2, lwgeom 2.3.3 r15473
> plot(st_polygon())
Error in (function (xlim, ylim, log = "", asp = NA, ...)  : 
  need finite 'xlim' values

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.5-5

loaded via a namespace (and not attached):
[1] compiler_3.4.2 magrittr_1.5   DBI_0.7        tools_3.4.2    units_0.4-6    yaml_2.1.14   
[7] Rcpp_0.12.13   udunits2_0.13  grid_3.4.2    
```

**Comment by edzer** [comment]
That's the equivalent of `plot(NA)`. I meant sth along the lines of
```r
plot(st_sfc(list(st_point(0:1), st_polygon(), st_point(4:5))))
```

**Comment by tim-salabim** [comment]
That works of course. So does
```r
mapview(st_sfc(list(st_point(0:1), st_polygon(), st_point(4:5))))
```
now.

**Comment by edzer** [comment]
Ah, OK, I see now. Thx!
