### ISSUE TITLE
Popup tables with leading row numbers, how to disable?

### ISSUE THREAD

**Issue by ragapack** [r-spatial/mapview#109]
Hi,
I am using mapview with a shiny app and leaflet and want to format the popup table like you sample.
Unfortunately the Popup is quite different of yours, no color background and formating and has leading row numbers.
![image](https://user-images.githubusercontent.com/6429531/32416058-1dc4e3dc-c22a-11e7-9d12-16476dd3f11f.png)

Now I saw running  mapview(breweries) in R Studio your version has the same problem with leading row numbers.

![image](https://user-images.githubusercontent.com/6429531/32416041-f6105e5c-c229-11e7-9d1c-c9647702fa8d.png)

I am using the Development version of Mapview
devtools::install_github("r-spatial/mapview@develop")

My Version of R
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.1                         
year           2017                        
month          06                          
day            30                          
svn rev        72865                       
language       R                           
version.string R version 3.4.1 (2017-06-30)
nickname       Single Candle 

Thank you
Thomas

**Comment by tim-salabim** [comment]
Can you provide your code please. Also what version of mapview are you using? `packageVersion("mapview")`

**Comment by ragapack** [comment]
packageVersion("mapview")
[1] ‘2.2.1’
Here the part of my code for the popuptable

```
# Read Shape file
Brasil <- readOGR("../IBGE_Data","BRASIL_MUNIC")


# Read CSV file
SidraData <- read.csv(file="../IBGE_Data/tabela6579.csv", header=TRUE, sep=",")



#merge Data
 
Brasil <- merge(Brasil, SidraData, by.x = "CD_GEOCMU", by.y = "Município")

# Subset from selectInput
UF <- Brasil[Brasil@data$UF == input$estado,]

......
# Add polygons from DF

scol <- UF@data[[input$variable]]
    
pal <- colorQuantile(input$colors, scol, n = 5)
    
leafletProxy("map", data = UF) %>%

addPolygons(fillColor = ~pal(scol),
           fillOpacity = 0.5, 

           color = "#BDBDC3", 
                  
           weight = 2,
                  
           group = "Municipios",
                  
           popup = popupTable(UF, zcol = 2:6 ))%>%
```
Thanks

**Comment by tim-salabim** [comment]
To get the mapview `popupTable ` layout we need to attach the css which overrides the standard leaflet css popup definitions.

```r
library(mapview)

m = leaflet() %>%
  addProviderTiles("OpenStreetMap") %>%
  addPolygons(data = franconia,
              fillOpacity = 0.5, 
              color = "#BDBDC3", 
              weight = 2,
              group = "Municipios",
              popup = popupTable(franconia, zcol = 2:6 ))

m$dependencies = c(m$dependencies,
                   mapview:::mapviewPopupDependencies())

m
```

Regarding the row index numbers, this is more complicated. We will need to change the underlying C++ calls (where this is currently hard-coded). I will get to this as soon as I can.

**Comment by tim-salabim** [comment]
The above commit should fix this. You can now set `row.numbers = FALSE` to skip the row numbers. 
Please reopen if this doesn't solve your issue.

**Comment by Jigar-S** [comment]
> 
> 
> To get the mapview `popupTable ` layout we need to attach the css which overrides the standard leaflet css popup definitions to the maps dependencies.
> 
> ```r
> library(mapview)
> 
> m = leaflet() %>%
>   addProviderTiles("OpenStreetMap") %>%
>   addPolygons(data = franconia,
>               fillOpacity = 0.5, 
>               color = "#BDBDC3", 
>               weight = 2,
>               group = "Municipios",
>               popup = popupTable(franconia, zcol = 2:6 ))
> 
> m$dependencies = c(m$dependencies,
>                    mapview:::mapviewPopupDependencies())
> 
> m
> ```
> 
> Regarding the row index numbers, this is more complicated. We will need to change the underlying C++ calls (where this is currently hard-coded). I will get to this as soon as I can.

Hello Tim,
Thank you for the solution to try and override the default leaflet css with the mapview version.
However when I am running the above code, I get an error message that says:
 
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'mapviewPopupDependencies' not found

I have updated both leaflet as well as mapview to the latest versions:
Leaflet version 2.0.2
mapview version 2.6.4

Can you please help resolve the issue ?

Thanks a lot for your help,
Jigar

**Comment by Jigar-S** [comment]
> 
> 
> > To get the mapview `popupTable ` layout we need to attach the css which overrides the standard leaflet css popup definitions to the maps dependencies.
> > ```r
> > library(mapview)
> > 
> > m = leaflet() %>%
> >   addProviderTiles("OpenStreetMap") %>%
> >   addPolygons(data = franconia,
> >               fillOpacity = 0.5, 
> >               color = "#BDBDC3", 
> >               weight = 2,
> >               group = "Municipios",
> >               popup = popupTable(franconia, zcol = 2:6 ))
> > 
> > m$dependencies = c(m$dependencies,
> >                    mapview:::mapviewPopupDependencies())
> > 
> > m
> > ```
> > 
> > 
> > Regarding the row index numbers, this is more complicated. We will need to change the underlying C++ calls (where this is currently hard-coded). I will get to this as soon as I can.
> 
> Hello Tim,
> Thank you for the solution to try and override the default leaflet css with the mapview version.
> However when I am running the above code, I get an error message that says:
> 
> Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
> object 'mapviewPopupDependencies' not found
> 
> I have updated both leaflet as well as mapview to the latest versions:
> Leaflet version 2.0.2
> mapview version 2.6.4
> 
> Can you please help resolve the issue ?
> 
> Thanks a lot for your help,
> Jigar

Hey,
I figured it out on my own. The function name has changed from 'mapviewPopupDependencies()' to 'popupLayoutDependencies()'

Thanks,
Jigar

**Comment by tim-salabim** [comment]
Glad you found it. Would have taken me a while to figure that one out!
