### ISSUE TITLE
Small bug in mapview

### ISSUE THREAD

**Issue by ugroempi** [r-spatial/mapview#110]
Hi Tim,

thanks for providing mapview!
Below you find a small bug I encountered (the example should be reproducible for you).

Best, Ulrike

`require(tmap)`
`require(sf)`
`require(mapview)`
`data(NLD_prov)  ## spatial polygons data frame`
`NLD_sfc <- sf::st_as_sfc(NLD_prov)`
`NLD_sf <- st_as_sf(NLD_prov@data, geom=NLD_sfc)`
`mapview(NLD_sf, label=as.character(NLD_prov$name), col.regions=grey.colors(12))`

gives the following warning:
Warning message:
In if (ml > 0.8 | unique(colors) %in% c("cyan", "#00ffff", "#00FFFF")) { :
  the condition has length > 1 and only the first element will be used

**Comment by tim-salabim** [comment]
I don't see this warning (anymore). Which version of mapview did you use?

**Comment by ugroempi** [comment]
It was 2.1.4. Sorry, I should have checked for an update before posting.
Best, Ulrike
