### ISSUE TITLE
addLegend, addCircleMarkers and addPolygon functionality from leaflet

### ISSUE THREAD

**Issue by u-ashish** [r-spatial/mapview#112]
I was trying to use leaflet to render a map of data (that has points of varying colors/sizes) and then add multi-select features to my map. 

After some research, I came across the mapview/mapedit project and was able to incorporate multi-select using these two libraries. However, if I use mapview, I lose the ability to render points of different sizes/colors based on their characteristics in my input dataframe, which I did in leaflet using addCircleMarkers. 

I would also like to add shapefile data to my map, which was possible in leaflet using addPolygon but from my understanding is not available in mapview.

Is it at all possible to retain those features in mapview, or is there any plan to add them in the future?

**Comment by tim-salabim** [comment]
I suggest that you read the documentation at https://r-spatial.github.io/mapview/. Everything you mention is easily done with mapview
