### ISSUE TITLE
Showing wrong values for southern hemisphere using raster data

### ISSUE THREAD

**Issue by frzambra** [r-spatial/mapview#123]
Hello folks,

I was testing the new mapview feature and I realize that mapview it's not working properly. I'm using raster data for the southern hemisphere (here in Chile). I just test mapview and the values are wrongly showed, also NAs has dissapear. But, if I convert the raster to polygons, that works fine.

A priori I think that this issue could be inherited from leaflet, the same happened with it.

This is my code

```R
library(raster)
library(mapview)

im<- raster(nrows=7,ncols=2,xmn=-75.7,xmx=-66.55,ymn=-50,ymx=-17.5,
            crs=crs("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
im[]<- seq(1,length.out=14,by=100)
im[c(1,6,9,12)] <- NA

mapview(im)
#same with polygons
mapview(rasterToPolygons(im))

#with leaflet
leaflet() %>% addTiles() %>% addRasterImage(im)
```
And my sessionInfo()

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18.1

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=es_CL.UTF-8       LC_NUMERIC=C               LC_TIME=es_CL.UTF-8       
 [4] LC_COLLATE=es_CL.UTF-8     LC_MONETARY=es_CL.UTF-8    LC_MESSAGES=es_CL.UTF-8   
 [7] LC_PAPER=es_CL.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=es_CL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_2.2.2 leaflet_1.1.0 raster_2.6-7  sp_1.2-7     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15      compiler_3.4.3    pillar_1.1.0      plyr_1.8.4        R.methodsS3_1.7.1
 [6] R.utils_2.5.0     base64enc_0.1-3   iterators_1.0.8   class_7.3-14      tools_3.4.3      
[11] gdalUtils_2.0.1.7 digest_0.6.13     jsonlite_1.5      viridisLite_0.2.0 satellite_1.0.1  
[16] lattice_0.20-35   png_0.1-7         rlang_0.1.6.9003  foreach_1.4.3     shiny_1.0.5      
[21] DBI_0.7           crosstalk_1.0.0   yaml_2.1.16       rgdal_1.2-5       e1071_1.6-8      
[26] htmlwidgets_1.0   webshot_0.5.0     stats4_3.4.3      classInt_0.1-24   grid_3.4.3       
[31] sf_0.6-0          R6_2.2.2          udunits2_0.13     magrittr_1.5      scales_0.5.0.9000
[36] codetools_0.2-15  htmltools_0.3.6   units_0.5-1       mime_0.5          xtable_1.8-2     
[41] colorspace_1.3-2  httpuv_1.3.5      munsell_0.4.3     R.oo_1.21.0    
```

**Comment by tim-salabim** [comment]
Hi @frzambra,
what you see is the result of projecting the raster data to conform with the leaflet projection (web-mercator - epsg 3857). Both leaflet and mapview use the following code to reproject raster layers before rendering.

https://github.com/rstudio/leaflet/blob/master/R/layers.R#L269

The default projection method in mapview for numeric rasters is "bilinear". When you set your raster layer to be factorial - `as.factor(im)` - things will look (and now show) as expected. Note that leaflet is currently limited to bilinear resampling, hence you will see the same ("wrong") rendering even for factorial layers.

**Comment by frzambra** [comment]
@tim-salabim thanks for your quick answer. Now, I re-wrote the script making the projection manually first and then I set `project=FALSE` for leaflet, and works fine. As you suggested me, for mapview I can use `as.factor(im)`. However, How can I set `project=FALSE` for mapview? I tried `mapview(im,project=FALSE)` but doesn't work.

```R
epsg3857 <- "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"
imProj<-  projectRaster(im,crs = sp::CRS(epsg3857),method='ngb')

leaflet() %>% addRasterImage(imProj,project=FALSE)
```
Thanks for the help,

Cheers

**Comment by tim-salabim** [comment]
@frzambra at the moment you can't tell mapview not to reproject your data. It automatically does it to ensure that things end up in the correct place on the map. I am currently revisiting the raster based methods in mapview and will address this. I am not quite sure how to best implement this though.
We could 

1. use argument `project = FALSE` as in leaflet, or
2. use argument `method = c("bilinear", "ngb")` to pass the method on to `projectRaster`.

My gut feeling tells me option 2 is more desirable. But I am happy to hear your thoughts (and others, in case anyone reads this).

**Comment by tim-salabim** [comment]
In https://github.com/r-spatial/mapview/commit/a51e5282d5495e81d664379e27b25fa5beda4e16 I have implemented option 2. Please test for your use-case and let me know it this works for you.

```r
library(raster)
library(mapview)

im<- raster(nrows=7,ncols=2,xmn=-75.7,xmx=-66.55,ymn=-50,ymx=-17.5,
            crs=crs("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
im[]<- seq(1,length.out=14,by=100)
im[c(1,6,9,12)] <- NA

mapview(im, method = "ngb")
```
is, I think, what you want to see, right?

**Comment by frzambra** [comment]
Works perfectly, thanks for implementing it and also for this awesome package.
