### ISSUE TITLE
popupImage local images

### ISSUE THREAD

**Issue by ChuliangXiao** [r-spatial/mapview#130]
popupImage works well with **remote** images but not with **local** images

```{r}
library(mapview)
library(sp)
library(lattice)

pnt <- data.frame(x = 174.764474, y = -36.877245)

coordinates(pnt) <- ~ x + y
proj4string(pnt) <- "+init=epsg:4326"

img <- system.file("img","Rlogo.png", package="png")
mapview(pnt, popup = popupImage(img))
```

Error in strsplit(gsub("Size is ", "", info), split = ", ")[[1]] : 
  subscript out of bounds
In addition: Warning messages:
1: In gdal_setInstallation(ignore.full_scan = ignore.full_scan, verbose = verbose) :
  No GDAL installation found. Please install 'gdal' before continuing:
	- www.gdal.org (no HDF4 support!)
	- www.trac.osgeo.org/osgeo4w/ (with HDF4 support RECOMMENDED)
	- www.fwtools.maptools.org (with HDF4 support)

2: In gdal_setInstallation(ignore.full_scan = ignore.full_scan, verbose = verbose) :
  If you think GDAL is installed, please run:
gdal_setInstallation(ignore.full_scan=FALSE)

**Comment by tim-salabim** [comment]
I think the warning (especially 1.) is quite clear. You seem to lack a GDAL installation. GDAL is needed to check the specs of the local image. Hence, if you install a current version of GDAL things should work.

**Comment by ChuliangXiao** [comment]
After I install GDAL via www.trac.osgeo.org/osgeo4w/ (with HDF4 support RECOMMENDED), it works. Thank you very much.
