### ISSUE TITLE
[Feature Suggestion] allow opening a mapview directly in a browser window

### ISSUE THREAD

**Issue by lbusett** [r-spatial/mapview#132]
Hi, 

  with reference to viewer = browserViewer(browser = getOption("browser")), 
in `mapedit` I can programmatically choose to open an "editing gadget" in a browser window using  argument 

    viewer = browserViewer(browser = getOption("browser")

, while this does not seem to be possible in `mapview`. 

I think that this would be a useful feature for `mapview` (also for "consistency" reasons wrt `mapedit`) . 

PS: I had a quick look through the code, but I am not enough versed in leaflet/shiny to try implementing this myself, sorry....

**Comment by tim-salabim** [comment]
I don't think leaflet provides an option to specify the viewer explicitly like shiny does. I may be wrong though and will have a closer look. For now you can always set `options(viewer = NULL)` to render in the browser instead of rstudio viewer. I have thought about making this option available in mapview, but am not sure how to revert that setting after the mapview call returns the map...

**Comment by lbusett** [comment]
Ok, thanks.  That would solve my issue, but if I can not "revert" the option to default on exit I can not use it. Here I found a related discussion: 

https://stackoverflow.com/questions/33312891/force-rstudio-to-use-browser-instead-of-viewer

While I am at it, I ask for a suggetion: 

   in my MODIStsp package, I am implementing an interactive "extent" selector based on `mapedit::selectFeatures` and `mapedit::editMap`. 

I then would like to have a button that upon click just SHOWS the current selection (i.e., no editing or drawing or selecting features possible). I was thinking of using `mapview` for that purpose, but maybe there are other / better solutions. Any sugggestions? (Maybe I am missing something obvious, here....)

Lorenzo

**Comment by timelyportfolio** [comment]
@lbussett, @tim-salabim in theory `htmlwidgets` are designed to accept an `htmlwidgets::sizingPolicy` that allows for suppression of the RStudio viewer with `viewer.suppress = FALSE`.   Some widgets incorporate a `sizingPolicy` as an argument but `leaflet` does not, and occasionally I have encountered cases where `viewer.suppress` does not actually suppress.  Here is an example.

```
library(leaflet)

lf <- leaflet()

lf$sizingPolicy <- htmlwidgets::sizingPolicy(viewer.suppress = TRUE)
```

**Comment by timelyportfolio** [comment]
@tim-salabim  good question :) and you know me well.  This is an acceptable workaround, but the  ideal solution in my mind is to add an argument to `leaflet` to pass through to `htmlwidgets::createWidget` in [line](https://github.com/rstudio/leaflet/blob/master/R/leaflet.R#L44-L49).  It is very common to pass through all arguments to `htmlwidgets::createWidget` in the widget creator function, such as `leaflet()`.  However, I cannot guess at the willingness or desire to add in `leaflet` proper.

**Comment by tim-salabim** [comment]
@schloerke @jcheng5 can we get this implemented in the next leaflet release?

**Comment by tim-salabim** [comment]
@lbusett regarding your second question, do you mean like a "preview" button?

**Comment by lbusett** [comment]
@tim-salabim The idea was to open a map with a polygon overlay in a browser to show the selected extent. So, something similar to what you get with  `selectFeatures` but without the selection "capabilities" (so,, in practice, a `mapview` in a browser).  In the end, however, I found out I can implemented something very similar using `mapedit::selectMap`

**Comment by schloerke** [comment]
@tim-salabim So expose `sizingPolicy` in main `leaflet()` command?

@timelyportfolio 
Running the class example does not open the leaflet widget in an external browser for me.  It opens in a RStudio viewer detached from the 4 panel RStudio IDE.  

Even after exposing sizingPolicy and setting `viewer.suppress = TRUE`, the leaflet widget opens in the detached RStudio viewer, not a browser.  If I set it to `FALSE`, the leaflet widget opens in the attached viewer in the IDE.

**Comment by tim-salabim** [comment]
@schloerke yes, that would be great.
@timelyportfolio I can confirm @schloerke's finding. The example above opens a RStudio viewer in a stand-alone window detached from the RStudio IDE.

**Comment by tim-salabim** [comment]
@schloerke I think [this](https://github.com/rstudio/htmltools/blob/6996430ae0d769b0f3d90a2196011142bc75bd2b/R/html_print.R#L41) is where it all happens. This is called in both [`print.htmlwidget`](https://github.com/rstudio/htmltools/blob/6996430ae0d769b0f3d90a2196011142bc75bd2b/R/html_print.R#L41) and [`print.suppress_viewer`](https://github.com/ramnathv/htmlwidgets/blob/21fca6d2de74acf218bd436249413afcfaa77565/R/htmlwidgets.R#L47) which was updated on 12 Apr in https://github.com/ramnathv/htmlwidgets/commit/21fca6d2de74acf218bd436249413afcfaa77565. I vividly remember that @timelyportfolio's workaround worked at the time he posted it, so I assume the mentioned commit changed the behaviour.

**Comment by tim-salabim** [comment]
We now have argument `viewer.suppress` to specify whether to view in viewer (`FALSE`) or in browser (`TRUE`)

**Comment by stewartmacdonald** [comment]
Does this still work if you pass `viewer.suppress=TRUE` as an argument to `mapview`? I can only get it to work if I set it globally with `mapviewOptions(viewer.suppress=TRUE)`. I'm using mapview 2.10.0.

**Comment by tim-salabim** [comment]
Hi @stewartmacdonald to get mapview to show features again, you need to install the current dev version from here. Re `viewer.suppress` is it problematic to only be able to set it via options?

**Comment by tim-salabim** [comment]
Hi @stewartmacdonald to get mapview to show features again, you need to install the current dev version from here. Re `viewer.suppress` is it problematic to only be able to set it via options?

**Comment by stewartmacdonald** [comment]
Hi @tim-salabim. Thanks for the reply.  It's not problematic at all, it just doesn't match up with how I read the documentation.

**Comment by tim-salabim** [comment]
Good point! I'll remove the respective parts!

**Comment by stewartmacdonald** [comment]
I understand that this is an issue tracker, but I don't want to only leave feedback that could be taken negatively. I discovered `mapview` relatively recently, but it's made exploring spatial data in R so much easier. Thank you for all your hard work!
