### ISSUE TITLE
improve documentation: kiliNDVI dataset (as described in vignette) is hard to find and use

### ISSUE THREAD

**Issue by knbknb** [r-spatial/mapview#134]
After seeing the recording of the talk about sf / mapview at the rstudio conference 2018, I've just begun playing with the mapview package, in order to check if/where mapview is more powerful/user-friendly than tmap's interactive maps .

I was a bit puzzled because the mapview vignette [1-mapview basics](https://r-spatial.github.io/mapview/articles/articles/mapview_01-basics.html) mentions a dataset 'kiliNDVI' which is not getting displayed by the autocompleter in RStudio, and cannot be loaded with `mapview(kiliNDVI)` or `data(kiliNDVI)`, unlike the 'poppendorf' raster dataset.

instead it must be loaded *manually*, e.g. as described in issue #115 
 
```
kili_data <- system.file("extdata", "kiliNDVI.tif", package = "mapview")
kiliNDVI <- stack(kili_data)

```
Apparently for that codesample to work, 'stars' must be installed, which (at this time) requires specific dependencies (sf >= 6.1)

Please say so that kiliNDVI needs to be treated differently in the text of the vignette. it could save other users some time.

This is the current text from the vignette

> 
> mapview includes 2 raster type data sets:
> 
>     poppendorf - a RasterBrick including 5 bands of a landsat scene located in Franconia
>     kiliNDVI - a raw multiband raster data set of 23 16-day Aqua-MODIS NDVI layers of Mt. Kilimanajro in Tanzania for the year 2013. See Detsch et al. 2016 for details on how this data set was created
> 
> Here’s an example for raster data:
> ...

**Comment by knbknb** [comment]
Ah I see in the next vignette [2-mapview advanced controls](https://r-spatial.github.io/mapview/articles/articles/mapview_02-advanced.html), section "Adjusting color, col.regions & at" a similar codesnippet for loading kiliNDVI shows up. Never mind.

**Comment by tim-salabim** [comment]
The reason for not having `kiliNDVI` as standard data in the package is the fact that it is too big. Though your hint is noted, I will add a sentence to the data description part in vignette 1.
