### ISSUE TITLE
base map for data.frame

### ISSUE THREAD

**Issue by bhogan-mitre** [r-spatial/mapview#138]
With the fairly recent support for `data.frame`s, it would be nice to enable base maps to go with them.

Currently a call to `mapview` with a `data.frame` such as:
```mapview(data.frame(x = 1:10, y = 1:10), xcol = "x", ycol = "y")```

results in an interactive viewer with no basemap:
![2018-03-27_21-42-11](https://user-images.githubusercontent.com/32336739/38003988-27c5d1d6-3208-11e8-8c3e-0e81ae1e8e27.png)

Would it be possible to expose a `crs` parameter in the `xyView` function, that is then passed on to `sf::st_as_sf`?  I believe nothing would need to change in the `mapview` function itself.

I am interested in a function call such as:
```mapview(data.frame(x = 1:10, y = 1:10), xcol = "x", ycol = "y", crs = 4326)```

having the same result as:
```mapview(sf::st_as_sf(data.frame(x = 1:10, y = 1:10), coords = c("x", "y"), crs = 4326))```

![2018-03-27_22-01-07](https://user-images.githubusercontent.com/32336739/38004463-648839ea-320a-11e8-8927-5ed18ee66239.png)

Relates to #54

**Comment by tim-salabim** [comment]
What's the use-case for this?

**Comment by bhogan-mitre** [comment]
The use case is feeding `mapview` with `data.table` as an easy way to see my data on a map, while retaining the rest of my `data.table`-based analysis workflow.

Yes, I can convert everything to `sf`, including converting the rest of my analysis from `data.table` to `dplyr`.  Or I can maintain an `sf` copy of my data, separate from the `data.table`/`data.frame` copy that I use for analysis.  But if you're supporting `data.frame` anyways, why not flip the switch and let users see their data on a basemap?

I'm happy to submit a PR if you're open to it.  I'm just wondering if there is a good reason not to support basemaps for `data.frame`.

**Comment by tim-salabim** [comment]
`mapview(data.frame(x = 1:10, y = 1:10), xcol = "x", ycol = "y", crs = 4326)` should work now.

**Comment by bhogan-mitre** [comment]
Great, thank you!
