### ISSUE TITLE
Using popupIframe

### ISSUE THREAD

**Issue by DocOfi** [r-spatial/mapview#141]
Hi,
Let me first thank for putting this wonderful package together and offering it for free to the public.  I'm trying to make a make a map of the diabetes camps in our country using the example in your tutorial. The camp is located in this coordinattes
> pnt <- data.frame(x = 120.4242, y = 14.82691)
> pnt <- st_as_sf(pnt, coords = c("x", "y"), crs = 4326)
> pnt
Simple feature collection with 1 feature and 0 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: 120.4242 ymin: 14.82691 xmax: 120.4242 ymax: 14.82691
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
                   geometry
1 POINT (120.4242 14.82691)

Then  i used the following code to create the map
mapview(pnt, popup = mapview:::popupIframe("https://www.youtube.com/embed/iApz08Bh53w?autoplay=1", width = 300, height = 225))

the map appears but when i click on the point to show the youtube video it just comes up as a blank gray rectangle.

Here is the URL from YouTube:
https://www.youtube.com/watch?v=yc6OMXUSlLA

and the URL for embedding it an webpage
<iframe width="560" height="315" src="https://www.youtube.com/embed/yc6OMXUSlLA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe> 

Thanks again for your wonderful package.

**Comment by tim-salabim** [comment]
I am assuming you're seeing the grey rectangle with no video in RStudio viewer? have you tried opening it in the browser? Does the video play there?

**Comment by DocOfi** [comment]
Sorry to have bothered you but for some reason it is now working. I'm really sorry.  It was probably due to the slow internet connection here in the Philippines.  Thank you so much for your time and for putting this great package for all R users.
