### ISSUE TITLE
Add mapview method for stars objects

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/mapview#142]
I think `stars` objects should have their own `mapview()` method, just like `raster` objects, other than the already present `addStarsImage()` for `leaflet` objects.

EDIT: my apologies if this was already in the works.

**Comment by tim-salabim** [comment]
No worries, this is currently only available in the [develop version ](https://github.com/r-spatial/mapview/blob/develop/R/mapView.R#L297) as stars is not yet on CRAN. Testing more than welcome ;-)

**Comment by adrfantini** [comment]
Nice! You finally got to the stars.
