### ISSUE TITLE
raster and stars are displayed differently

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/mapview#143]
This might be intended, but just to make sure...

`raster` and `stars` data are displayed in slightly different ways:
```
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)[,,,1]
mapview(as(x, "Raster"), layer.name="raster") + mapview(x, layer.name="stars")
```
They are slightly different, see especially in the corners.

Another example file: [download](http://s000.tinyupload.com/download.php?file_id=57880143443085556645&t=5788014344308555664541305).

```
library(raster)
library(stars)
library(mapview)
r <- raster("test.nc")
s <- read_stars("test.nc", sub="pr")
mapview(r, layer.name="raster") + mapview(st_as_stars(r), layer.name="stars")
```
They are quite different.

I guess this is due to the fact that the `raster` file is remapped to the leaflet projection and the `stars` is not (how?) and this is all to be expected, but better be safe than sorry.

**Comment by adrfantini** [comment]
I have tested with a much larger dataset: [here it is](https://drive.google.com/open?id=14kxFVqtUC6FWIvbyyCvPK8E9WMUGZ6WI).

```
library(raster)
library(stars)
library(mapview)
prj <- "+proj=lcc +lat_1=30 +lat_2=65 +lat_0=48 +lon_0=9.75 +x_0=-6000 +y_0=-6000 +a=6371229 +b=6371229 +units=m +no_defs"
r <- raster("test.nc")
projection(r) <- prj
s <- st_as_stars(r)
st_crs(s) <- prj

mapview(r)
mapview(s)

```
Here is what the `raster` looks like (of course it has undergone automatic remapping to the Leaflet projection):
![screenshot_20180405_212207](https://user-images.githubusercontent.com/12826141/38387214-69275c38-3917-11e8-980a-f6ac5475d501.png)

Here is the `stars`:
![screenshot_20180405_212339](https://user-images.githubusercontent.com/12826141/38387326-b3e7e5da-3917-11e8-8cfb-dd1aa61be649.png)


Notice that for the `stars` file:

1. in the corners there are some values which are reported to be NULL by the top-right indicator, but they are nevertheless shown as valid and colored in the map
2. georeferentiation is completely wrong!

**Comment by tim-salabim** [comment]
Thanks for the example. I have updated the `stars` method and it should now produce "correct" results.
Having said that, there seems to be some problem with how stars transforms layers. If we transform both raster and stars layer to web mercator (epsg 3857):

```r
library(raster)
library(stars)
library(mapview)

prj <- "+proj=lcc +lat_1=30 +lat_2=65 +lat_0=48 +lon_0=9.75 +x_0=-6000 +y_0=-6000 +a=6371229 +b=6371229 +units=m +no_defs"
r <- raster(path.expand("~/software/testing/mapview/stars/test.nc"))
projection(r) <- prj
s <- st_as_stars(r)
st_crs(s) <- prj

# plot(r)
# plot(s) # so far so good

rwm = projectRaster(r, crs = sp::CRS(leaflet:::epsg3857))
swm = st_transform(s, crs = leaflet:::epsg3857)
```
we see for the raster layer `rwm`

```r
plot(rwm)
```

![rwm](https://user-images.githubusercontent.com/2826432/38418993-e7e13512-399e-11e8-9e37-f6488507cda0.png)

and for the stars layer `swm`

```r
plot(swm)
```

![swm](https://user-images.githubusercontent.com/2826432/38419038-1d3e6b30-399f-11e8-9c03-3187dc039f99.png)

Converting `rwm` to stars yields much closer results

```r
swm2 = st_as_stars(rwm)
plot(swm2)
```

![swm2](https://user-images.githubusercontent.com/2826432/38419073-43326bfc-399f-11e8-812b-c9864ebce8f8.png)

However, there are still small discrepancies as you can see when zooming in

```r
mapview(rwm, maxpixels = ncell(rwm)) + swm2
```

The dimensions of the two layers are equal
```r
> dim(rwm)
[1] 641 867   1
> dim(swm)
   x    y band 
 867  641    1 
```
though reported in swapped order.

Maybe @edzer can shed some light on this?

**Comment by edzer** [comment]
Thanks -- should work now!

**Comment by tim-salabim** [comment]
Thanks @edzer ! This is much closer. There are still minor differences in cell locations around the edges, but the overall image looks similar. I guess this is due to different resampling approaches taken by stars and raster...
