### ISSUE TITLE
A way to capture mouse coordinates with addMouseCoordinates?

### ISSUE THREAD

**Issue by jamesdalg** [r-spatial/mapview#147]
addMouseCoordinates() is an amazing and much needed function. Is there a way to capture the values as a manipulatable R object in shiny?

**Comment by tim-salabim** [comment]
Can you provide a bit more detail on what it is exactly that you want to capture? The function currently is pure JavaScript and is only able to display coordinates in its dedicated div triggered by mouse move. There are ways to capture coordinates and zoom on click in shiny (I've seen examples).

**Comment by jfroeschke** [comment]
Here is a simple example to get coordinates from a mouse click

output$out <- renderPrint({
validate(need(input$map_click, FALSE))
data.frame(input$map_click[1:2])
})

**Comment by tim-salabim** [comment]
@jamesdalg is this still unresolved?
