### ISSUE TITLE
feature request: npts also at feature level?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/mapview#155]
Hi

The npts function is very useful, yet in some cases it would be nice to return the number of vertices per feature, not necesarily the sum. Would it be possible to add a `byid=FALSE` argument (as in gArea, or any other name), to allow to return npts per feature?

I don't fully understand the code of npts, but some (inefficient) code like this could be a starting point?

Thanks!

    nNodes2 = function(x) {
      if(mapview:::getGeometryType(x) =="pt"){
        return(1)
      } else {
        return(if (is.list(x)) nNodes(x) else fun(x))
      }
    }

```
npts2 <- function(x, byid=FALSE) {
  gm <- st_geometry(x)
  res <- sapply(1:length(gm), function(i) nNodes2(gm[i]))
  if(!byid) res <- sum(res)
  res
}

npts2(franconia)
npts2(franconia, byid=TRUE)

npts2(breweries, byid=FALSE)
npts2(breweries, byid=TRUE)

```

**Comment by tim-salabim** [comment]
This should work now
```r
npts(x, by_feature = TRUE)
```
As mentioned in the help, am yet to find a clever way to get this working for `GEOMETRYCOLLECTION`. It should, however, work for `*POINT`, `*LINESTRING` and `*POLYGON`

**Comment by edzer** [comment]
Re: `GEOMETRYCOLLECTION` I would try sth like this
```r
npts = function(x) {  
	sum(
		if (is.list(x)) sapply(x, npts) else {
			if (is.matrix(x))
				nrow(x)
			else {
                             if (st_is_empty(x)) 0 else 1
                        }
		} 
	)
}
```
```r
> g = st_geometrycollection(list(st_point(0:1), st_linestring(matrix(1:6,3))))
> npts(st_sfc(g,st_point(0:1),g,st_point()))
[1] 9
```

**Comment by tim-salabim** [comment]
Thanks Edzer! Also for the hint on `st_is_empty` which I completely didn't consider so far...

**Comment by tim-salabim** [comment]
Thanks to @edzer this seems like a good solution:
```r
library(mapview)
library(sf)

nVerts = function(x) {  
  out = if (is.list(x)) sapply(sapply(x, nVerts), sum) else {
    if (is.matrix(x))
      nrow(x)
    else {
      if (sf::st_is_empty(x)) 0 else 1
    }
  } 
  unname(out)
}

npts = function(x, by_feature = FALSE) {
  if (by_feature) nVerts(x) else sum(nVerts(x))
}

tst = st_sfc(st_geometrycollection(c(st_geometry(franconia), st_geometry(breweries), st_sfc(st_point()))))

npts(st_geometry(franconia))
npts(st_geometry(trails))
npts(st_geometry(breweries))
npts(tst)

npts(st_geometry(franconia), by_feature = TRUE)
npts(st_geometry(trails), by_feature = TRUE)
npts(st_geometry(breweries), by_feature = TRUE)
npts(tst, by_feature = TRUE)
```
Will update mapview shortly
