### ISSUE TITLE
addStaticLabels not working in shiny app

### ISSUE THREAD

**Issue by lbusett** [r-spatial/mapview#160]
Hi, 

  in relation to https://github.com/r-spatial/mapview/pull/136 and this recent commit in the develop branch 3f6632efe8e00abc8a316b9d79caebae7967e51f, I just wanted to signal that while the addStaticLabels functionality is now working well again, I am having problems in using it within a Shiny application. 

Below, you can find a reprex: 

```
library(leaflet)
library(mapview)

ui <- fluidPage(
  mapview::mapviewOutput("map")
)

server <- shinyServer(function(input, output, session) {
  output$map <- renderMapview({
    lopt = labelOptions(noHide = TRUE,
                        direction = 'top',
                        textOnly = TRUE)
    m1 = mapview(breweries)
    l1 = addStaticLabels(m1,
                         label = breweries$number.of.types,
                         labelOptions = lopt)
    l1
  })
})
shinyApp(ui, server)
```
, which errors wtih:

> Listening on http://127.0.0.1:5855
> Warning: Error in methods::slot: no slot of name "map" for this object of class "leaflet"
>   50: methods::slot
>   49: mapview2leaflet
>   48: renderMapview
>   47: server [/home/lb/Source/git/bf.work/source/R/WIP/test_shiny.R#11]
> Error in methods::slot(x, "map") : 
>   no slot of name "map" for this object of class "leaflet

Any idea about I could solve this ? Am I doing anything wrong? 

Thanks in advance!

**Comment by tim-salabim** [comment]
I really need to bury `renderMapview` and `mapviewOutput` deep. They are not working as expected (they did for a while though). The best thing to do (and generally recommended) is to use `leafletOutput` together with `renderLeaflet` on the `@map` slot of the mapview object.
```r
library(leaflet)
library(mapview)
library(shiny)

ui <- fluidPage(
  mapview::leafletOutput("map")
)

server <- shinyServer(function(input, output, session) {
  output$map <- renderLeaflet({
    lopt = labelOptions(noHide = TRUE,
                        direction = 'top',
                        textOnly = TRUE)
    m1 = mapview(breweries)
    l1 = addStaticLabels(m1,
                         label = breweries$number.of.types,
                         labelOptions = lopt)
    l1
  })
})
shinyApp(ui, server)
```

**Comment by lbusett** [comment]
Indeed it works nicely! Thanks! 

One "caveat" worth mentioning is that (apparently) the dataset used to "build" the labels needs to be in lat/lon, otherwise the labels won't show. so, for example, since my input data is in UTM,  I needed to use: 

```
  l1 <- addStaticLabels(m1,
                       data = sf::st_transform(plot_data, 4326),
                       label = plot_data$id_geom,
                       labelOptions = lopt)
```

(I know that this is ugly and inefficient and will need to be changed - it's just to illustrate the point). 

If I may ask **another question**: I tried in several ways to **change the color / size of the labels** by modifying the labelOptions, but did not succeed. Is there a way to do that? 

Lorenzo

**Comment by tim-salabim** [comment]
Yeah, it's always a little tricky to figure out where to look when arguments get passed on to underlying frunctions (from other packages) via `...` as in this case. On the other side it means that the wrapper functions retains full flexibility provided by the original function. 
I'll have a look at the PR shortly.

**Comment by tim-salabim** [comment]
Closing here. Feel free to reopen if necessary
