### ISSUE TITLE
mapshot not preserving addWebGLHeatmap from leaflet.extras

### ISSUE THREAD

**Issue by mgrogger** [r-spatial/mapview#165]
I've been having an issue with the following code:
    
    map = leaflet(df) %>%
      addWebGLHeatmap(lng=~df$longitude, lat=~df$latitude, opacity= 1 , intensity = .5 ,size = 1000, gradientTexture='deep-sea', data=df)%>%
      addTiles(urlTemplate = map, attribution=attr)
    mapshot(map, file = 'new_orleans_la_map.png')

Which produces this image:

![](https://user-images.githubusercontent.com/7903768/42660797-cfb7608e-85f1-11e8-8e7f-58273369e1d2.png)

Instead of what RStudio produces (albeit just with the leaflet line):

![](https://user-images.githubusercontent.com/7903768/42660525-1308407a-85f1-11e8-9d24-3ffa983268f8.png)

I addressed an analogous issue [here](https://github.com/wch/webshot/issues/67) with the webshot creator. Is the issue with mapshot not preserving the WebGLHeatmap layer because it uses webshot in some applications? Or is this issue different?

**Comment by tim-salabim** [comment]
Sorry, but you're out of luck. mapshot is essentially a wrapper around saveWidget and webshot combined into one function. So, if webshot cannot handle WebGL, neither can mapshot.
