### ISSUE TITLE
Color gradient of polylines 

### ISSUE THREAD

**Issue by angelovangel** [r-spatial/mapview#166]
I think it would be great if something like the [Leaflet.hotline](https://github.com/iosphere/Leaflet.hotline) plugin could be implemented in `mapview`, especially for `sf` data (and thus making use of those Z/M dimensions). I could get the `JS` Leaflet.hotline plugin running in `leaflet`, using `onRender()`, but find it too complicated. Or are there other options?
Best!

**Comment by tim-salabim** [comment]
Agreed! Can you please rpovide the `onRender()` code as a strating point? 

@schloerke I think this is something that should be either in mapview or leaflet.extras. Of the two I favour mapview for the reason of Z/M coordinates that @angelovangel pointed out above and the fact that leaflet.extras is currently not maintained well. Or do you think this should be in core leaflet?

**Comment by angelovangel** [comment]
OK, [here](https://gist.github.com/angelovangel/3bf47edbb3522d48c661229ee59de737) is a minimal example of using the Leaflet.hotline `JS` plugin (I had to use the script locally). I think it can be used like this, provided there is a convenient way to feed `sf` data to it, using the `data` argument of the `onRender` function.

**Comment by tim-salabim** [comment]
I am a bit confused as to how this plugin maps colors to z coordinates. If you consider the following, it seems to only interpolate colors linearly between any 2 consecutive points disregarding the colors specification for z coordinates in between:
```r
m %>%
  
  onRender("function(el, x, data) {
  var latlngs = [[7,5,100],[9,4,600],[8,3,400],[7,4,100],[6,3,600]];

  //data = HTMLWidgets.dataframeToD3(data);
  //data = data.map(function(val) { return [val.lat, val.lon, val.geoaltitude]; });
  //require('leaflet-hotline')(L);
  
  var hotlineLayer = new L.Hotline(latlngs, {
                                          palette: {0: 'blue', 0.5: 'red', 1: 'yellow'},
                                          weight: 4,
                                          outlineWidth: 0,
                                          max: 600,
                                          min: 100}).addTo(this);
  var bounds = hotlineLayer.getBounds();
	this.fitBounds(bounds);
  
  }")
```
Clearly the first and last segments should respect the 'red' in the middle of their interpolation, but they don't. If this is the desired behaviour of the plugin, I am not sure it is useful for displaying e.g. elevation profiles along line segments.

**Comment by angelovangel** [comment]
I haven't noticed this, you are right...I think there are also other JS plugins with similar functionality, but I haven't tried them. How about color mapping to z-values using the `colorNumeric` function of `leaflet`?

**Comment by tim-salabim** [comment]
This is essentially what @edzer is doing at the bottom of [this post](https://www.r-spatial.org/r/2017/08/28/nest.html). I effectively means that you need to slice each LINETSRING into its segments and then color those. This, however, means that you need to decide how to map two values (z-value of segment start and z-value of segement end point) to one color (as you can have only one color per LINESTRING in leaflet). In case you are happy to review any of the other plugins you mention, I am haoppy to try to integrate them (if we find a suitable candidate).

**Comment by angelovangel** [comment]
This is marvelous, thanks!
It works perfectly and has the functionality I need. I think though that streamlining this idea in a convenient wrapper would make it easier to use.

**Comment by tim-salabim** [comment]
Ok, let me think of a way to implement this in mapview
