### ISSUE TITLE
Unloading and freeing memory

### ISSUE THREAD

**Issue by mredaelli** [r-spatial/mapview#170]
`mapview` depends on a lot of libraries, and a result of this is that importing it causes a lot of memory to be allocated. According to my OS, it's about 150 MB.
We are using it inside a pool of shiny application, and all those 150 MB sum up quickly.

I would like to unload `mapview` when it is not needed, and I tried something like this:

```r
> library(mapview)
> detach("package:mapview", unload=TRUE)
```
but that doesn't have any effect on the memory usage.

Do you have any suggestions?
I realize this is generally an R question ("how do you deallocate memory from a library"), but perhaps you guys have some specific idea, knowing the internals of the package.

**Comment by tim-salabim** [comment]
I don't know too much about memory allocation in R. As I said in the [similar tmap thread](https://github.com/mtennekes/tmap/issues/240) mapview naturally has hefty dependencies as it provides methods for the most common spatial classes which means that it has to import those. 

I suggest we keep this discussion in one thread (over at tmap), so I'm closing here.
