### ISSUE TITLE
Remove feature ID from popupTable

### ISSUE THREAD

**Issue by arthurgailes** [r-spatial/mapview#182]
From the example code:

 `leaflet() %>% addCircleMarkers(data = breweries, popup = popupTable(breweries))`

How can I remove or retitle the "Feature ID" part?

Thank you!

**Comment by tim-salabim** [comment]
Thanks for the suggestion. The above commit enables to suppress the 'Feature ID' column in `popupTable`

```r
leaflet() %>% addCircleMarkers(data = breweries, popup = popupTable(breweries, feature.id = FALSE))
```

**Comment by abdulrr** [comment]
Has the popupTable function been taken off?
I am using Mapview and trying to hide "mvFeatureId" and "fillColor" from the label popup.

Packages attached:
mapview_2.10.0
leaflet_2.0.4.1

Thanks!
