### ISSUE TITLE
Map without popup

### ISSUE THREAD

**Issue by RomanBi** [r-spatial/mapview#184]
I would like to create a map with labels, but without popups. Those are added automatically, removing them seems not straightforward. 
By setting `popup = FALSE`, an empty popup is added...

Is this feature implemented, am I missing something?

**Comment by tim-salabim** [comment]
Yeah, its not so intuitive as this is passed to the Javascript side and thus should be specified as `NULL` instead of `FALSE`.

 - I should add a test for `FALSE` -

**Comment by RomanBi** [comment]
Works like a charm. Thank you!

**Comment by tim-salabim** [comment]
Keeping this open as a reminder to implement check

**Comment by tim-salabim** [comment]
a8334e9 should fix this. Now also accepts `FALSE` to suppress popups.
