### ISSUE TITLE
Grey map on zoom in with empty mapview()

### ISSUE THREAD

**Issue by Jellest** [r-spatial/mapview#185]
When I run `mapview()` without any arguments, I get a grey map after zooming in. I get this for all the different standard provided basemaps in the layer switcher. Is this normal?

![empty map view](https://user-images.githubusercontent.com/6051312/46154786-28b9e100-c276-11e8-8286-68be74847a5d.png)

Running mapview 2.5 on R 3.5 on a Linux machine.

**Comment by tim-salabim** [comment]
Yes, totally normal and intended.
Background tiles are usually only available for zoom levels up until 18/19. Everything beyond that will be a grey background. The default leaflet settings will not allow you to scroll past zoom 18/19. mapview on the other hand allows this, as sometimes geometries can be very small (e.g. sliver polygons created via intersection).

**Comment by Jellest** [comment]
Thank you for your quick response. Yes, I’m aware that maps only have certain zoom levels but not that mapview has no default max zoom levels, which I was expecting. Thanks for clearing that up.

**Comment by tim-salabim** [comment]
The max zoom level is set to 100 in mapview https://github.com/r-spatial/mapview/blob/develop/R/leafletControls.R#L193
