### ISSUE TITLE
Coordinates of TiledImage

### ISSUE THREAD

**Issue by NHPatterson** [r-spatial/mapview#186]
Hello

I am using the recently rolled out ```addTiledImages()``` but wondering if the coordinates are supposed to be projected? I'm trying to place objects on the non-georeferenced tiled image based on the pixel coordinates of the image..

Also, I am serving the tiles locally so I have sort of removed some of the code
```R
require(leaflet)
require(mapview)

leafmap = leaflet(
  options = leaflet::leafletOptions(
    crs = leafletCRS(
      crsClass = "L.CRS.Simple"
    )
  )
)
#I modified this to reflect my locally served tiles
leafmap$dependencies <- c(leafmap$dependencies,
                          mapview:::rastercoordsDependency())

#local http server running at 7800 with tiles..
leafmap <- leaflet::invokeMethod(leafmap, leaflet::getMapData(leafmap), 'rastercoords',
                                 width, height, 7, "http:/localhost:7800/tiles_AFtest/{z}/{x}/{y}.png") %>% 
  addMouseCoordinates()

```

All of this works for display, but my coordinates run from x - 0:130, y - 0:-130 and I can't add objects like polygons specified in pixel coordinates from the image. Maybe I am missing some critical information. It appears that rastercoords is working by the image being bounded correctly, but leaflet still projects the coordinates..

Any advice?

**Comment by tim-salabim** [comment]
Hi, we never included `addTiledImage()` in any CRAN release and the functionality has been removed from mapview as it was simply too slow. Therefore, we never implemented any additional functionality to put features on top of unprojected tiled images. It can be done using `rastercoords` which has a method to project coordinates to pixel coordinates but, as I said, I've never bothered looking into it. What you would need to do is provide a js binding for `addMarkers` etc. that uses the project-to-pixel-coordinates javascript method provided by `rastercoords`. 
Maybe it would be the best to wrap this in a package, as you would need to provide dedicated functions for markers, circlemarkers, polylines, polygons etc.
