### ISSUE TITLE
Sizing of panels using sync

### ISSUE THREAD

**Issue by JimShady** [r-spatial/mapview#190]
Hello,

I'm trying to make a sync'd mapview of three panels in RMarkdown. The default width isn't wide enough for me. But when I increase the width, it only seems to effect one panel. Reproducible example below, and PNG output of the result. Grateful for any ideas/tips on how to solve this.

n.b. each of the code chunks below are actually rmarkdown chunks. I couldn't get GitHub to style them as that properly. I hope it's clear enough.

```{r setup, include=FALSE}
library(devtools)
devtools::install_github("r-spatial/mapview@develop")
library(mapview)
library(leaflet)
library(sf)
```

```{r data, include=F}
thames <- st_read('https://raw.githubusercontent.com/KCL-ERG/useful_geography/master/thames.geojson')
```

```{r plot, echo=F}

mapviewOptions(leafletWidth = 700)

panel_1 <- mapview(thames, map.types = c("OpenStreetMap.BlackAndWhite"))
panel_2 <- mapview(thames, map.types = c("OpenStreetMap.BlackAndWhite"))
panel_3 <- mapview(thames, map.types = c("OpenStreetMap.BlackAndWhite"))

sync(panel_1, panel_2, panel_3, ncol = 3)
```

![image](https://user-images.githubusercontent.com/2901470/47005060-e247fb80-d12a-11e8-9336-3efb569571f5.png)

**Comment by tim-salabim** [comment]
Sorry for the late reply! I'll look into this, but likely not before December.

**Comment by JimShady** [comment]
Cool thanks @tim-salabim

**Comment by tim-salabim** [comment]
@JimShady sorry that nothing has happened regarding this issue. If you're still interested in a solution, could I please ask you to open an issue at [leafsync](https://github.com/r-spatial/leafsync/issues)?

Closing here, to clean up some clutter in this repo
