### ISSUE TITLE
Dynamic Time slider

### ISSUE THREAD

**Issue by ochee** [r-spatial/mapview#191]
Hi,

I was wondering if there is a way to add a time slider (as a widget ) on a mapwiew map.
I would like to add a slider, to see value dynamically over time. I didn't see anything about in help page web.

Here an example :

`library(sp)`
`library(mapview)`

`dat=data.frame(lon=c(4,4.5,5,4,4.5,5,4,4.5,5),
lat=c(60,65,58,60,65,58,60,65,58),
time=c(1,1,1,2,2,2,3,3,3),
value=c(120,105,90,50,20,70,30,10,5))`

`coordinates(dat) <- c("lon", "lat")`
`proj4string(dat) <- CRS("+init=epsg:4326")`
`mapview(dat,zcol="value")`

Thank you for this useful package and your help,
Ochee

**Comment by tim-salabim** [comment]
Sorry, this is currently not possible and is not high on my priority list.
