### ISSUE TITLE
Error with addResourcePath for new version of mapview and leaflet

### ISSUE THREAD

**Issue by earthcli** [r-spatial/mapview#193]
I have created a mapview object(large size raster) and  built in one package of myself, and it was load by data(m) and then passed to the shinyserver, so that it will take less time when opening the shiny web. This works well before I updated the R to version 3.5, and at the same time the mapview, leaflet, and shinydashboard was updated to the new version. The error information is as below:
```r
Error:Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'Riceland-1'; `directoryPath` = 'C:/Users/QIN/AppData/Local/Temp/RtmpOOwtEr/data_stars54582e64147_8942d6'
```

I have debuged that code and find that this may be caused by the temporary file created by the leaflet package,  for m1 loaded from my package, and m2 caculated in real time,the below test is not TRUE,
```r
identical(m1@map$dependencies[[3]],m2@map$dependencies[[3]])

for m1: file: chr "C:/Users/QIN/AppData/Local/Temp/RtmpOAzKgi/data_stars321845fb3c20_58f926"
for m2: file: chr "C:/Users/QIN/AppData/Local/Temp/RtmpwFMY1f/data_stars13105c55332c_8b5e3a"
```
And I also find that encoding problem(such as layer name with chinese character rather UTF-8)also cause addResourcePath erro for the new version package, while it does not for the former versions. 
How can I solve this problem, would you please give me some advice, thanks!

**Comment by tim-salabim** [comment]
I don't think you can do that! Clearly you're depending on data that resides in a temporyry folder which will be deleted when you close your R Session. I am surprised that ever worked. I guess what you need to do is save the map as a .html file and somehow include that in your package.

Is your package online somewhere? Maybe I can have a look and understand better what you are trying to do.

**Comment by earthcli** [comment]
@tim-salabim Thanks for your response.

I have done this with the below sample code:

shinyServer(function(input, output, session){
  data(m,package="my")
   output$mapplot <- renderLeaflet({m@map}) 
}
while in former version I use "output$mapplot <- renderMapview(m)"
m is a mapview object containing three layers: land use type(two layer), and weather stations in point.

My package is not submitted to the cran, so I can not give an exact example for test.

The map is server as a homepage of my shiny web, if I can save it as a html and then load, how can I do it, would you give me a piece of code for example?

**Comment by earthcli** [comment]
![shiny web screen](https://user-images.githubusercontent.com/5924370/47291118-13e22a80-d635-11e8-9159-ea18ddc3e52c.png)

**Comment by tim-salabim** [comment]
The way I see it is that `addImageQuery` - the function that gives you the raster values on mouseover - is causing the issue as it writes data to a temporary folder on disk. This folder is deleted once you close your R Session, hence the dependency cannot be found anymore. 

What you can try is to manually copy the `data_starsXXXXX...` file(s) to where the map is served. You would need to make sure that the folder structure relative to where the index.html is served is identical to the one in the `RTmpXXX` folder. That way, your application should find the necessary data when it is served. 

I have no idea how you could do that from within a package though...

**Comment by earthcli** [comment]
Thanks for your suggestion @tim-salabim .
I will try to copy it to a relative path.
I agree that it may be related with the temporary files created by the new version leaflet, while it seems that there is no temporary files created by the former version.

**Comment by tim-salabim** [comment]
What was your former version of mapview? The temporary file is created by mapview, introduced in [2.3.0](https://github.com/r-spatial/mapview/blob/develop/NEWS.md#mapview-230)

**Comment by earthcli** [comment]
sorry, the former ‘mapview’ version is 1.2.25 on my server computer.

while it is an excellent package that helps me a lot in my work, I have use it for more than three years, thanks for your work.

**Comment by tim-salabim** [comment]
So, can we close this issue here then?

**Comment by earthcli** [comment]
Of course. Please close this issue.
Thanks a lot @tim-salabim.
