### ISSUE TITLE
Mapview gsub error; "Invalid UTF-8"

### ISSUE THREAD

**Issue by ddheart** [r-spatial/mapview#194]
Hello, I'm running mapview on a dataframe (or rather two dataframes: mapview(df1) + mapview(df2)) and I'm seeing this error instead of any Viewer panel output in RStudio:

Error in gsub("</", "\\u003c/", payload, fixed = TRUE) : 
  input string 1 is invalid UTF-8

I'm running mapview_2.5.0, and as far as I can tell similar issues were addressed and resolved in previous PRs, so I'm not exactly sure what to do here.

**Comment by tim-salabim** [comment]
Can you provide a reproducible example? 
I don't think this is an issue related to mapview, but I can only be sure with a reprex.

**Comment by ddheart** [comment]
For sure here's what I have. I isolated the observation causing the error and called `dput()` on it but strangely the behavior changes depending on whether I assign `dput(x)` directly to a variable or copy-paste the full structure you need for reproducibility...I don't understand why there's a difference in whether the error shows up...

library(mapview); library(tibble); library(dplyr)
x <- testdat[443,] %>% select(Asset) # me, taking observation that causes error
mapview(x)
#> Error in gsub("</", "\\u003c/", payload, fixed = TRUE) : 
#> input string 1 is invalid UTF-8
dputoutput1 <- dput(x) # get dput and directly assign it to variable
# Now, assigning equivalent raw dput output to variable
dputoutput2 <- structure(list(Asset = "Schwabm\xfcnchen, DE", geometry = structure(list(
  structure(c(12.83, 49.07), class = c("XY", "POINT", "sfg"
  ))), class = c("sfc_POINT", "sfc"), precision = 0, bbox = structure(c(xmin = 12.83, 
                                                                        ymin = 49.07, xmax = 12.83, ymax = 49.07), class = "bbox"), crs = structure(list(
                                                                          epsg = 4326L, proj4string = "+proj=longlat +datum=WGS84 +no_defs"), class = "crs"), n_empty = 0L)), row.names = c(NA, 
                                                                                                                                                                                            -1L), class = c("sf", "tbl_df", "tbl", "data.frame"), sf_column = "geometry", agr = structure(c(Asset = NA_integer_), .Label = c("constant", 
                                                                                                                                                                                                                                                                                                                             "aggregate", "identity"), class = "factor"))
mapview(dputoutput1)
#> Error in gsub("</", "\\u003c/", payload, fixed = TRUE) : 
#> input string 1 is invalid UTF-8
mapview(dputoutput2) # works??? why??

**Comment by ddheart** [comment]
More specifically, it looks like it's having a problem with the ü (u umlaut) character, here shown escaped with \xfc, where FC is the valid hexcode for ü.

**Comment by ddheart** [comment]
For some reason it wasn't reproducible using `dput()`, but if you change this .txt file's extension to .RData and call `load()` on the path in R, it should load a variable called `samp`. `mapview(samp)` should return this error:

`Error in gsub("</", "\\u003c/", payload, fixed = TRUE) : 
  input string 1 is invalid UTF-8`

[errordata.txt](https://github.com/r-spatial/mapview/files/2582358/errordata.txt)

**Comment by pdeffebach** [comment]
I also got this error. I wouldn't mind some brute-force method of just skipping these characters to be honest.

**Comment by tim-salabim** [comment]
@pdeffebach can you provide a reproducible example?

**Comment by pdeffebach** [comment]
Sure. I don't trust my abilities to make a shapefile on my own for this. Can I email you the shapfile I've been using for this?

**Comment by tim-salabim** [comment]
Yes, E-Mail is fine

**Comment by pdeffebach** [comment]
I apologize but I can't find an email anywhere. Does r-spatial have an email for this kind of thing?

**Comment by tim-salabim** [comment]
The email of the maintainer is available form the DESCRIPTION file https://github.com/r-spatial/mapview/blob/develop/DESCRIPTION (the CRAN page also shows it).

**Comment by pdeffebach** [comment]
Thank you!  I sent the email. Here is my `sessionInfo()`

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2.2  mapview_2.6.3   rio_0.5.16      forcats_0.3.0   stringr_1.3.1   dplyr_0.7.8     purrr_0.2.5    
 [8] readr_1.2.1     tidyr_0.8.2     tibble_1.4.2    ggplot2_3.1.0   tidyverse_1.2.1 sf_0.7-2       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0         lubridate_1.7.4    lattice_0.20-35    png_0.1-7          class_7.3-14      
 [6] utf8_1.1.4         assertthat_0.2.0   digest_0.6.18      mime_0.6           R6_2.3.0          
[11] cellranger_1.1.0   plyr_1.8.4         backports_1.1.2    stats4_3.5.1       e1071_1.7-0       
[16] httr_1.3.1         pillar_1.3.0       rlang_0.3.0.1      lazyeval_0.2.1     curl_3.2          
[21] readxl_1.1.0       rstudioapi_0.8     data.table_1.11.8  raster_2.8-4       webshot_0.5.1     
[26] foreign_0.8-70     htmlwidgets_1.3    munsell_0.5.0      shiny_1.2.0        broom_0.5.0       
[31] compiler_3.5.1     httpuv_1.4.5       modelr_0.1.2       pkgconfig_2.0.2    base64enc_0.1-3   
[36] htmltools_0.3.6    tidyselect_0.2.5   codetools_0.2-15   fansi_0.4.0        viridisLite_0.3.0 
[41] crayon_1.3.4       withr_2.1.2        later_0.7.5        grid_3.5.1         lwgeom_0.1-5      
[46] satellite_1.0.1    nlme_3.1-137       jsonlite_1.5       xtable_1.8-3       gtable_0.2.0      
[51] DBI_1.0.0          magrittr_1.5       units_0.6-2        scales_1.0.0       zip_1.0.0         
[56] cli_1.0.1          stringi_1.2.4      promises_1.0.1     sp_1.3-1           leaflet_2.0.2     
[61] xml2_1.2.0         openxlsx_4.1.0     RColorBrewer_1.1-2 tools_3.5.1        glue_1.3.0        
[66] hms_0.4.2          crosstalk_1.0.0    yaml_2.2.0         colorspace_1.3-2   classInt_0.3-1    
[71] rvest_0.3.2        bindr_0.1.1        haven_2.0.0       
```

**Comment by tim-salabim** [comment]
Ok, thanks for sending the data via mail. This is a tricky issue as we need to know the encoding in which the data was saved. The following dirty piece of code works on my (linux) machine, but I simply guessed that the encoding used to write the shapefile was 'latin1'. Therefore, I don't think it is feasible to try and do something like this in mapview... 

```r
library(mapview)

tst = st_read("/home/timpanse/software/testing/mapview/utf_issue/Sectores/sectores_final.shp",
              stringsAsFactors = FALSE)

# subset to column "descriptio" for testing
tst2 = tst[, "descriptio"]

# doesn't work
mapview(tst2)

# try converting from latin1 to utf8
tst2$descriptio = iconv(tst2$descriptio, "latin1", "UTF-8")

# works now
mapview(tst2)


# now for whole data set
# delete sticky geometry list column (will re-add later)
tst3 = st_set_geometry(tst, NULL)

# function to check for 
f = function(x) x == "character"

# which columns are of class character?
charcols = sapply(sapply(tst3, class), f)

# convert those columns from latin1 to utf8 encoding
# note that it is actually necessary to know the original encoding (here guessed
# to be latin1)
tst3[, charcols] = sapply(tst3[, charcols], iconv, from = "latin1", to = "UTF-8", sub = "")

# re-add geometry column and convert back to sf
tst3$geometry = st_geometry(tst)
tst3 = st_as_sf(tst3)

# works
mapview(tst3)
```

**Comment by pdeffebach** [comment]
Thank you! This was enormously helpful. I have added this snippet, with attribution, to my importing code as with an optional argument.

**Comment by tim-salabim** [comment]
Can we close this then?

**Comment by pdeffebach** [comment]
Yeah we should close this, with the recommendation being "Mapview needs UTF-8 and there are a variety of methods to getting your data into the right encoding for it to work"
