### ISSUE TITLE
mapshot .html file cannot be shared?

### ISSUE THREAD

**Issue by vjjan91** [r-spatial/mapview#196]
Hello,

I am trying to share a .html file that I saved using the function mapshot, but my collaborator is unable to view it. Is the only option of sharing this map via RPubs? Is there any other way I can save this .html file and share it?

**Comment by tim-salabim** [comment]
Did you also share the `_files` folder?

**Comment by vjjan91** [comment]
I see. That's a lot of folders to share over e-mail. Do they have to download each one to view this in their desktop? Thanks!

**Comment by tim-salabim** [comment]
Its one folder with subfolders depending on your mapview call. This is how `saveWidget` works which mapshot is a wrpper for. And yes the files folder is needed.
