### ISSUE TITLE
showMethods("mapview") breaks RStudio 1.1.456

### ISSUE THREAD

**Issue by YsoSirius** [r-spatial/mapview#199]
Executing these 2 lines will break down RStudio 1.1.456

```
library(mapview)
showMethods("mapview")
```

Before shuttig down, multiple

> Error during wrapup: 

are shown in the console.

**Comment by tim-salabim** [comment]
Works for me using RStudio 1.2.1114 so seems like an RStudio issue.

Does `showMethods("mapView")` work? (with a capital `V`)

**Comment by YsoSirius** [comment]
on another PC with RStudio 1.1.463 both methods work but show different results.
```
> showMethods("mapView")
Function: mapView (package mapview)
x="bbox"
x="data.frame"
x="list"
x="missing"
x="numeric"
x="RasterLayer"
x="RasterStackBrick"
x="Satellite"
x="sf"
x="sfc"
x="SpatialGridDataFrame"
x="SpatialLines"
x="SpatialLinesDataFrame"
x="SpatialPixelsDataFrame"
x="SpatialPoints"
x="SpatialPointsDataFrame"
x="SpatialPolygons"
x="SpatialPolygonsDataFrame"
x="stars"
x="XY"
x="XYM"
x="XYZ"
x="XYZM"
```

and 
```
> showMethods("mapview")
Function: mapview (package mapview)
...="ANY"
```

I will test in the evening with the other computer and report again, but it might be an RStudio problem only.

**Comment by YsoSirius** [comment]
Capital V does not work with RStudio 1.1.456.

I'll just update to the new version.
