### ISSUE TITLE
Large sets of points (greater than a threshold) rendering below polygons

### ISSUE THREAD

**Issue by emochoa** [r-spatial/mapview#201]
Greetings.

I'm wondering if there is a known fix for an issue I'm running into.  Here's the situation:

I'm plotting points and polygons together in a single mapview map:  the desired behavior is that the points are plotted above the polygons.

The polygons are always fixed, but the size of the point set is variable.  If the point set grows over a certain threshold (which, to complicate matters, seems to vary with the dataset), then the points are plotted _underneath_ the polygons; the points are visible through transparent polygons or if the polygon layer is turned off via the pop-up menu—but if the polygons are opaque, then the points will not be visible by default.

Here is a reproducible example:

```
library(sf)
library(mapview)
library(tidyverse)

set.seed(100)

# Yield of this spatial join is about 50%, so
# generate about twice as many points as needed
rounds = 17500

points <- data.frame(x = runif(rounds, 8.97, 12.25),
                     y = runif(rounds, 48.75,50.55)) %>%
          st_as_sf(coords = c('x','y'),
                   crs = st_crs(franconia))

points.within <- st_join(points, franconia, st_within, left = FALSE)

# These points show up on top, as intended
points.yes <- points.within %>% sample_n(8451)

mapview(franconia,
        alpha.regions = 1,
        legend = FALSE,
        col.regions = 'green') + 
  mapview(points.yes, cex = .1,
          layer.name = 'points',
          lwd = 0,
          col.regions = 'black',
          legend = FALSE)


# These points are plotted below the polygons
points.no <- points.within %>% sample_n(8452)

mapview(franconia,
        alpha.regions = 1,
        legend = FALSE,
        col.regions = 'red') + 
  mapview(points.no,
          cex = .1,
          layer.name = 'points',
          lwd = 0,
          col.regions = 'black',
          legend = FALSE)
```

![image](https://user-images.githubusercontent.com/22716026/50534228-575a8880-0aff-11e9-8075-a9de3ad71e13.png)
![image](https://user-images.githubusercontent.com/22716026/50534248-a56f8c00-0aff-11e9-81a2-a10d69d8cc70.png)

The threshold here seems to be 8,452; in the dataset I'm using, it's 10,001.

I would appreciate it if you have any ideas, please.  Thank you for your time.

Best,

Erin

**Comment by tim-salabim** [comment]
Hi erin, thanks for the comprehensive example. I am currently not at a computer so can verify all I'm saying. 

You can try to set `canvas = FALSE` in both mapview calls to force the usual behaviour of points above polygons. The threshold when mapview sets canvas to true internally should be 10000 for points. Note that for very many points you may experience slow map responsiveness.
