### ISSUE TITLE
Multi-line labels

### ISSUE THREAD

**Issue by gillesgerlo** [r-spatial/mapview#202]
Is there any way to get line breaks in the hover labels? 
html content is only evaluated in the popup, but not in the label.

**Comment by gillesgerlo** [comment]
As I write the issue I finally get it to work, sorry about that. Seems the HTML function does the trick:

`
 htmltools::HTML(paste('line 1', 'line 2: ', sep = '<br/>')
`

**Comment by natearoe** [comment]
This does make <br> tags work, but it causes all of the labels to be shown for every point, instead of just the labels that are related to each point.
