### ISSUE TITLE
detailed mouse position information

### ISSUE THREAD

**Issue by maxbre** [r-spatial/mapview#205]
this is a follow-up of the thread in stackoverflow:
https://stackoverflow.com/questions/54559604/mouse-coordinate-information-at-top-of-map-with-leaflet-mapview-in-r?noredirect=1#comment95958989_54559604

I'm here opening a request (checking the possibility) to display detailed mouse position information when setting up the map via leaflet

thanks

**Comment by tim-salabim** [comment]
The current version now supports native coordinates when leaflet map is set up with `L.CRS.Simple`. For obvious reasons, we cannot know what the `crs` is, as we don't necessarily have access to the data being shown. If you need that information, `mapview(x, native.crs = TRUE)` is your best option.

**Comment by tim-salabim** [comment]
Does this solve your issue @maxbre?

**Comment by maxbre** [comment]
yes, thank you
you can consider the thread closed
