### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by andzandz11** [r-spatial/mapview#209]
https://r-spatial.github.io/mapview/articles/articles/mapview_04-popups.html#interactive-popups

This gives me a 404 in the popup.

![grafik](https://user-images.githubusercontent.com/19622117/53018145-e0cc6e00-3451-11e9-8548-15aa80c1bbfe.png)

**Comment by tim-salabim** [comment]
This is a long standing issue. I have yet to find a suitable solution. Thanks for the reminder.

**Comment by tim-salabim** [comment]
I will revisit the articles once I get the build of mapview to not fail anymore
