### ISSUE TITLE
NA bloats up legend [feature request]

### ISSUE THREAD

**Issue by andzandz11** [r-spatial/mapview#210]
![grafik](https://user-images.githubusercontent.com/19622117/53018776-86cca800-3453-11e9-8e2f-1f0e6c3a1343.png)

Please make it so NA is displayed below the legend and not to the right of it because this causes a lot of space to be lost (whitespace).

For example here:
https://r-spatial.github.io/mapview/articles/articles/mapview_02-advanced.html#multiple-layers

**Comment by tim-salabim** [comment]
I agree that it looks ugly, however, even if we could control the `NA` placement (which we can't), it wouldn't solve the white-space issue, as the legend title is the culprit of the white space. We could, however, place the attribute column name ('founded') underneath the layer name ('breweries'). This would also solve the `NA` placement. The only disadvantage this may cause is that legends will become a little longer meaning that some content may be lost at the bottom of the screen.

I'll look into it and see what is the better option here.

**Comment by tim-salabim** [comment]
This has been resolved in the latest dev version
