### ISSUE TITLE
zcol information hides map [feature request]

### ISSUE THREAD

**Issue by andzandz11** [r-spatial/mapview#211]
![grafik](https://user-images.githubusercontent.com/19622117/53018854-b11e6580-3453-11e9-82b2-1b3c9ec66ad7.png)

Please make the zcol information 1) scrollable (it is cut off right now) 2) hideable ( like the bar on the left: https://spatial.ala.org.au/# )  3) prevent linebreaks.

**Comment by tim-salabim** [comment]
Thanks for the suggestions. I fear there is little I can do on mapview side to address this. This is all inherited behaviour from [leafletjs](https://leafletjs.com). I totally agree that a proper hidable side-panle would be ideal, but as long as there is no proper JavaScript solution for leafletjs available, this is beyond the scope of mapview. If you find a suitable plugin, please let us know.
