### ISSUE TITLE
Using popupIframe with mp4

### ISSUE THREAD

**Issue by maxlavoie** [r-spatial/mapview#218]
In this example:

```
pnt <- data.frame(x = 174.764474, y = -36.877245)

coordinates(pnt) <- ~ x + y
proj4string(pnt) <- "+init=epsg:4326"
```

`mapview(pnt, popup = mapview:::popupIframe("https://www.youtube.com/embed/iApz08Bh53w?autoplay=1", width = 300, height = 225))`

Would it be possible to replace the youtube video with a mp4? I actually tried it but it did not workout. `popupImage` does not take very well a mp4 extension. It's part of Rmarkdown document. It is working very well with several images, but would like to include some videos.
Thanks!

**Comment by tim-salabim** [comment]
Hi, thanks for the suggestion. I am currently in the process of breaking mapview up into several smaller, more maintainable packages. Next on my list is `leafpop` providing all the popup functions currently contained in mapview. Once we have that on CRAN, I'll have a look into non-online video sources. Please remind me about this issue in case I should forget.

**Comment by tim-salabim** [comment]
You can follow progress here #206

**Comment by tim-salabim** [comment]
Closing here, please file an issue in **leafpop** for local video support.
