### ISSUE TITLE
multiple images on the same popup

### ISSUE THREAD

**Issue by lucabirigazzi** [r-spatial/mapview#220]
Dear developers,

thank you very much for this great package,
I have visited a set of locations and in each location I have taken four photos (N, E, W, S).
I would like to show these four images (jpg) in a popup for each location.
I see that I can already show two images for each point using the slideView function. 
But I am not sure how to have this done when one has three or more images.
Are you planning to add this feature?

Thank you,

Luca

**Comment by tim-salabim** [comment]
Just to clarify, are you asking how to 

1. show multiple images in a popup? 
2. show more than 2 images in slideview?

**Comment by lucabirigazzi** [comment]
Hi,
show multiple image in a popup

**Comment by tim-salabim** [comment]
Ok, I think the easiest would be to use e.g. the [magick package](https://github.com/ropensci/magick) to create a collage of your images and show that in the popup. 

Other than that we would need to introduce a proper js library to flick through multiple images. I am open to that idea, but only after I have separated out the popup functions from mapview and put them in their own package (soon to happen).

**Comment by lucabirigazzi** [comment]
Thank you very much Tim,
Hence, I will go for the magic package option.
and will wait for the release of the new package...
