### ISSUE TITLE
Support tilefolders

### ISSUE THREAD

**Issue by Robinlovelace** [r-spatial/mapview#222]
One question: if you have pre-built tiles, would be possible to point mapview to the folder and use that to visualise large raster datasets? Could be useful! 

Example tile pyramid: https://github.com/npct/pct-lsoa-vis/releases/download/0.0.2/bicycle-tiles.zip there are other (bigger ones) here, representing cyclable routes to work across England and Wales: https://github.com/npct/pct-lsoa-vis/releases/

Many thanks!

**Comment by tim-salabim** [comment]
A first implementation... Please test with a few more tile collections (ideally of different locations and different zoom levels). Cheers!

**Comment by Robinlovelace** [comment]
Reprex suggests this works a treat, great work sir (the ouput of `gdal2tile.py` is strange for this input dataset, nothing to do with `mapview`):

``` r
# Aim: test mapview's tile folder functionality
devtools::install_github("r-spatial/mapview", "develop")
#> Skipping install of 'mapview' from a github remote, the SHA1 (ce76b06c) has not changed since last install.
#>   Use `force = TRUE` to force installation
raster::writeRaster(spDataLarge::nz_elev, "nz_elev.tif")
system("gdal2tiles.py nz_elev.tif")
pth = file.path(getwd(), "nz_elev")
m = mapview::mapview(pth)
library(leaflet)
m@map
```

![](https://i.imgur.com/mg8U8RH.png)

<sup>Created on 2019-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by tim-salabim** [comment]
The issue I am most worried about is the inference of the proper calculation of the bounding box (used to set the initial view and homebutton view) from the tile structure. For this I have stolen @MilesMcBain 's implementation in [slippymath](https://github.com/MilesMcBain/slippymath/blob/master/R/slippymath.R#L69-L79) which I think is for the XYZ standard. `gdal2tiles` is TMS standard and hence needed a little adjusting. This is done [here](https://github.com/r-spatial/mapview/blob/develop/R/files.R#L52-L53) and needs more testing. With your above example I am not happy with the initial view for example.

**Comment by Robinlovelace** [comment]
I think it would be possible to extract that info from the html files generated by `gdal` itself, assuming the they exist. If not, the approximation is fine and the user can always specify the centre and zoom manually so I'd say no big deal.

**Comment by tim-salabim** [comment]
heads-up @Robinlovelace I've decided to include the base functionality for this in  [leafem::addTileFolder](https://github.com/r-spatial/leafem/blob/master/R/file.R#L157). From a `mapview` use perspective nothing should change, but people can now also use this without `mapview` on their own `leaflet` maps. Obviously, `mapview` will take care of setting appropriate options and views for you, which the `leafem::addTileFolder` will leave up to the user.

`leafem` has also gained a `addLocalFile` function which is blazingly fast if you point it to a `.geojson` file in the correct projection (4326).

**Comment by Robinlovelace** [comment]
Great work @tim-salabim, will install `leafem` and get going with that: sensible splitting-out of core functionality.
