### ISSUE TITLE
Is addLargeFeatures functionality gone?

### ISSUE THREAD

**Issue by JoshOBrien** [r-spatial/mapview#223]
Apparently, `addLargeFeatures` et al. were removed in 47cec7b7cb649d1d224b5cff7d1212b6d87e0bd8. If they are truly gone (rather than moved into internals or onto another development branch, etc.), it might be worth making note of that change in the `README`, `README.md`, and `NEWS.md` files as well as deleting the the mention of `addLargeFeatures` from https://r-spatial.github.io/mapview/index.html.

**Comment by tim-salabim** [comment]
Thanks for spotting this! The README has been updated to reflect the removal. The online manual will be auto-updated after the next successful Travis-build. Regarding the NEWS, it's there, but a little hidden I admit: 

https://github.com/r-spatial/mapview/blob/develop/NEWS#L84
