### ISSUE TITLE
Removing geometry description in popuptable

### ISSUE THREAD

**Issue by ggeniaux** [r-spatial/mapview#224]
Hello,
is there a way to remove the description of the geometry in popuptable while keeping all the other columns ?

```r
# example: x is a 6-column sf object, and the "geom" column appears in popuptable as a seventh column.
 
mapview(x,zcol='price',layer.name='price',legend=TRUE,popup=popupTable(x,zcol=1:6),row.numbers=FALSE,feature.id = FALSE))
```

Thanks.

**Comment by tim-salabim** [comment]
Moved to https://github.com/r-spatial/leafpop/issues/2

**Comment by tim-salabim** [comment]
Hi , please note that `popupTable` has been moved to its own package [here](https://github.com/r-spatial/leafpop). Therefore I have migrated the issue there. It should be fixed now, but you'd need to upgrade your packges to use the newest version of mapview and have the github version of `leafpop` installed.
