### ISSUE TITLE
What is happening with the 'mapview' package?

### ISSUE THREAD

**Issue by Aquinonesgis** [r-spatial/mapview#226]
I don't know what is happening to the viewer on the "mapview" package in R. Every time I display a map with mapview(), instead of showing the map on the viewer window in RStudio, its opening the map on a new window on the internet browser. I've updated the package to the new version (2.7) but I keep having this issue. Can someone reply as soon as possible? Thanks!

**Comment by tim-salabim** [comment]
`mapview` has an argument `viewer.suppress`. Set this to `FALSE` to prevent from opening in the browser. We're trying to be smart here so that whenever the data is qúite large, we're switching to the browser as the viewer can sometimes cause RStudio to crash (at least that was an issue).

**Comment by Aquinonesgis** [comment]
Thank you so much! I will try that!
