### ISSUE TITLE
webshot.js returned failure value after running mapview() on RStudio Cloud

### ISSUE THREAD

**Issue by drkamarul** [r-spatial/mapview#232]
Hi,

I posted this question on RStudio Community <https://community.rstudio.com/t/unable-to-knit-to-pdf-or-word-with-error-message-after-running-mapview-on-rstudio-cloud/35102?u=kim4597> but has not received any solution. My question is: my project includes a `mapview()` function from **mapview** package. 

The project (contains the Rmarkdown and other files) can be accessed here https://rstudio.cloud/spaces/20812/project/409030. I could knit the project to HTML, pdf and word  on my laptop. But the problem is, I could only knit to HTML on RStudio Cloud. If I try to knit to PDF or word, I will receive this error message.   

![image](https://user-images.githubusercontent.com/6749223/61173605-27209600-a5c8-11e9-8625-c33ef260f167.png)

I could trace the problem to Line 380 which is this - `mapview(nc["BIR74"], col.regions = sf.colors(10))`. If I remove this line or insert a hashtag at the front of the function, then I could knit to PDF and Word. 

My guess is `mapview()` triggers the error. How could I print a map using the `mapview()` on PDF in RStudio Cloud. Any help is very much appreciated.

KIM

**Comment by tim-salabim** [comment]
I have never worked with RStudio cloud, but my guess is that if you acll the `@map` slot of mapview as in `mapview(x)@map` to render your map everything should be fine.

**Comment by drkamarul** [comment]
I will give it a shot

**Comment by tim-salabim** [comment]
Closing here, feel free to reopen if you think this is not resolved

**Comment by KathaRRRina** [comment]
I am new here and I have a similar question with this title: mapshot error: webshot.js returned failure value: 1
