### ISSUE TITLE
viewRGB has different color than raster::plotRGB

### ISSUE THREAD

**Issue by dlebauer** [r-spatial/mapview#234]
With the attached file [test.tif.zip](https://github.com/r-spatial/mapview/files/3413104/test.tif.zip), if I download and unzip it and

```sh
unzip test.tif.zip
R
```

If I plot it with raster::plotRGB it appears to have the correct colors 

```r
library(raster)
a <- brick('test.tif')
plotRGB(a)
```

_note_ 
* this is a very tall, low res stitched image of a mature sorghum field so it should be green 
* since it is tall, I am only presenting a the top ~10% of the attached image
 
![image](https://user-images.githubusercontent.com/464871/61571947-780f0f00-aa4c-11e9-8aef-c6511d081fd5.png)

But if I plot it with viewRGB it looks like

```r
mapview::viewRGB(a)
```

![image](https://user-images.githubusercontent.com/464871/61571971-b3114280-aa4c-11e9-8343-f37393f1ee53.png)

After looking at the documentation I see that the default arguments for band order of the functions are reversed: `viewRGB(x, r = 3, g = 2, b = 1)` vs   `plotRGB(x, r = 1, g = 2, b = 3)`

However, this doesn't seem to fix the problem. Indeed, it isn't clear if these r, g, b arguments have any effect:

 
![image](https://user-images.githubusercontent.com/464871/61572141-2c5d6500-aa4e-11e9-8a0d-51b0b697071e.png)

Am I doing something wrong? Please advise!

**Comment by tim-salabim** [comment]
In `viewRGB` the images are streched between 0.02 and 0.98 quantiles by default. If you set this to `NULL` the result should be similar to `plotRGB`

```r
viewRGB(a, 1, 2, 3, quantiles = NULL)
```

**Comment by dlebauer** [comment]
Thanks!
