### ISSUE TITLE
feature request: click through timeseries interactively by arrows

### ISSUE THREAD

**Issue by przell** [r-spatial/mapview#235]
Dear Tim, 
I'm currently working on raster image timeseries (e.g, NDVI). For quality assessment and validation it would be great to have the possibility to do the following:
give list of rasters or or stack to mapview
get the option to have arrows on both sides of the map to click back and forth through the timeseries.

[Here's](https://stackoverflow.com/questions/49734639/producing-a-moving-time-sequence-in-raster) an example of a similar implementation with shiny.

Here's an example of the arrows I mean. Just to give you an idea:
![image](https://user-images.githubusercontent.com/51962348/62527630-d05f5280-b83b-11e9-9ca8-b41ca2eededf.png)

**Comment by tim-salabim** [comment]
Have you tried `cubeview::cubeview()`? No map, but you can flick through the layers using up/down, left/right, pageup/pagedown keys

**Comment by przell** [comment]
I've tried it now. Really cool tool! Solved my current issue. Worked out of the box. Thanks.
Still for presentations, meetings etc. the map background would be a nice feature. ;)
Feel free to close if the feature has no priority atm.
Thanks, 
Peter

**Comment by tim-salabim** [comment]
@przell I just had a thought that it should be possible to mimic what happens when you use the layer switcher in the layers control and bind that to a keyboard stroke, say 'Ctrl + arrow up'. This would make it behave similar to `cubeview`. Would that be acceptable? No promises as to when I can get to implementing this though :-)

**Comment by przell** [comment]
Hi Tim, 
thanks for the follow up. 
For my special use case the implementation of the arrows to navigate would be preferable. Just to give the users the same feel of the usual web image navigators. It was intended for the use in dashboards.
But anyhow, this has no priority in any way for me and I can't estimate if this is even relevant for anybody else in the community. 
So personally I don't have a use case for the implementation of the "arrow key solution".
Thanks again Tim!

**Comment by tim-salabim** [comment]
Ok, I'm closing this here then. Feel free to reopen or remind me if necessary
