### ISSUE TITLE
Mapview 'leaflet' layers not working

### ISSUE THREAD

**Issue by RussellGrayxd** [r-spatial/mapview#236]
I've had this problem in the past and it randomly resolved itself, but this time its been days and nothing has worked. I've updated R to v 3.6.1.; I've reinstalled mapview package, etc. 

So While I made a simple map with geompoints - lets call it "mapview(sp)" the map worked absolutely fine. Then I continued writing unrelated code, and went back to open the map, and it ran the error: "Error in browseURL(x, ...) : 'url' must be a non-empty character string"

I was also using bdvis package which uses LeafletR, so after reading up on the issues between the two programs, I deleted leaflet R and restarted my R console. After restarting, all of my mapview maps stopped showing the four default background layers and only show the geompoints. So now its just a grey background with points. 

I looked into it and it was said that this could be fixed by viewing in browser. Did that -- same thing, grey background with points. 

PLEASE HELP!

**Comment by tim-salabim** [comment]
Sorry for the late reply. I cannot help you unless you provide a reproducible example.
Have you checked that the "geompoints" have a proper CRS (i.e. not NA)?
