### ISSUE TITLE
mapview(stars_image) gives an error

### ISSUE THREAD

**Issue by edzer** [r-spatial/mapview#237]
Reprex:
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.7.1, GDAL 2.4.2, PROJ 5.2.0
example(read_stars, ask = FALSE, echo = FALSE)
library(mapview)
mapview(x1)
# Error in addRasterLegend(x = x, map = m, title = grp, group = grp, at = at,  : 
#   (list) object cannot be coerced to type 'logical'
# Calls: mapview ... mapView -> .local -> leaflet_stars -> addRasterLegend
# In addition: Warning messages:
# 1: 'mapview::addImageQuery' is deprecated.
# Use 'leafem::addImageQuery' instead.
# See help("Deprecated") and help("mapview-deprecated"). 
# 2: In any(is.na(vals)) : coercing argument of type 'list' to logical
# Execution halted
```
What works is:
```r
mapview(x1, legend = FALSE)
```

**Comment by tim-salabim** [comment]
This now works also with `legend = TRUE` (the default). Note, currently only the first band gets displayed as we don't handle stars "bricks/stacks" yet. What you can do manually as a workaround is:

```r
m = mapview(x1, band = 1)

for (i in 2:6) {
  m = m + mapview(x1, band = i)
}

m    
```
It's ugly, I know, but for the time being it's at least working :-/

**Comment by tim-salabim** [comment]
@edzer if we're implementing a method for multiband stars objects, how should we deal with many bands/layers? If we render each individually, it will take a long time! Should we limit the number of bands to say 6 or so and throw a warning (maybe alluding to cubeview)? Any other ideas?

**Comment by edzer** [comment]
I agree that large numbers do not make sense -- you'd want a slider to browse through them probably; `sf::plot.sf` also stops at 9 maps or so and gives a warning message how to plot all of them. 

There is one special case: (how) can we do RGB composites of sets of three bands?

**Comment by tim-salabim** [comment]
We can already do

```r
library(stars)
library(mapview)

tif = system.file("tif/L7_ETMs.tif", package = "stars")
(x1 = read_stars(tif))

viewRGB(x1, 3, 2, 1) + viewRGB(x1, 6, 5, 4)
```
So far, it's up to the user to chain these together. Did you have in mind to somehow combine this into one call? 

Maybe

```r
viewRGB(x1, rgb = list(c(3, 2, 1), c(6, 5, 4)))
```
could be a solution?

**Comment by edzer** [comment]
Oh, cool, so that is already there - thanks!

**Comment by tim-salabim** [comment]
@edzer can you think of any student of yours that would be interested in trying to tackle to provide a JavaScript solution for adding a slider to flick through layers/bands?

**Comment by tim-salabim** [comment]
Closing here, feel free to reopen here or elsewhere if you think stars is not yet properly handled
