### ISSUE TITLE
Feature requests: add grid/graticule, cex options, and additional shape options

### ISSUE THREAD

**Issue by sdlapoint** [r-spatial/mapview#241]
Hello and thank you for a useful and straightforward package.

I'm an amateur R user trying to make publication quality maps showing spatial data. I have had good luck so far with mapview() and mapshot(). My target is a static map, something saved as a .png that can be a figure in a manuscript.

My questions/requests:
1. I have a continuous variable that I would like to map via cex. These data are counts at sites (long, lat), ranging from 73 - 167 . At present, it looks like setting cex = "counts" displays these data at predefined breaks (possibly 5?). Can that be changed?

2. I see other post(s) have requested the ability to set the display shape to something other than a circle. You've given the "manual" option, but will shape be added as an option to mapview() in the future? For example, in my case, it would be nice to display the site location with shape = season (1 of 4) and size to "count". 

3. Is it possible to add long/lat grids or graticules within mapview()? Possibly also with the feature of adding axis labels, ticks, etc.?

Many thanks! Hoping to move away from ggmap...

**Comment by tim-salabim** [comment]
Hi @sdlapoint 
thanks for those requests. For publication-quality static maps I recommend you have a look at the [tmap package](https://github.com/mtennekes/tmap). It can produce much nicer static maps than you will ever be able to produce by taking a screenshot of a mapview map. It has a nice [vignette](https://cran.r-project.org/web/packages/tmap/vignettes/tmap-getstarted.html) to get you started. Another good resource for tmap can be fund in [chapter 8](https://geocompr.robinlovelace.net/adv-map.html) of the Geocomputation with R book. Not sure if graticules are part of those resources, but I know that tmap supports those. Point scaling is also supported with the added benefit of a proper legend in static maps.

Regarding your second point, I don't have solid plans to integrate this into mapview, but this has been a reoccurring issue, so may try to tackle it at some stage.

**Comment by tim-salabim** [comment]
@sdlapoint can we close this?

**Comment by sdlapoint** [comment]
Apologies, yes, this can be closed.

I'm exploring tmap with some success. Looking forward to seeing shape options in mapview().
