### ISSUE TITLE
mapview options for homebuttons

### ISSUE THREAD

**Issue by Pindar777** [r-spatial/mapview#242]
mapview adds automaticaaly homebuttons (zoom-buttons) for included layers. I'd like to change the standard position of them as it is possible in this function https://www.rdocumentation.org/packages/leafem/versions/0.0.1/topics/addHomeButton without the necessity of specifying the extents (which up until now I did not manage either...).
Is there already a way to do that?

**Comment by tim-salabim** [comment]
This is currently not possible. We could add this as a option so it can be controlled via `mapviewOptions`. Would this be acceptable. I am more than hesitant to add more arguments to `mapview()` as I feel it has too many as it is.
