### ISSUE TITLE
Can I use color palettes defined by other packages (e.g. in RColorBrewer) with mapviewPalette?

### ISSUE THREAD

**Issue by inder-tg** [r-spatial/mapview#245]
I would like to utilize color palettes that have been defined in other packages, e.g. the "Reds" palette of RColorBrewer, in combination with mapviewPalette. In my mind this will produce maps with continuous colors similar to those that can be defined through colorNumeric and then used in leaflet but with mapview's functionality.

I think that one way to get close to what I want is via viridis, but this function seems to have a reduce number of colormap options.  

I appreciate any input on this idea.

**Comment by tim-salabim** [comment]
You can use any palette function you want. You can create them with `colorRampPalette`. I might be able to help more if you provided an example highlighting what you want to achieve.

**Comment by inder-tg** [comment]
Hi Tim, I figured it out, thanks, the results can be seen at https://conabio.shinyapps.io/viSTA/
Cheers!

**Comment by tim-salabim** [comment]
Nice!
