### ISSUE TITLE
 labels for Esri.WorldImagery

### ISSUE THREAD

**Issue by FelipeCarrillo** [r-spatial/mapview#246]
Hi;
This is not really an issue but I am just wondering how to add labels to a map.types=Esri.WorldImagery and how to control zooming in or out at the time of rendering the map. I have looked all over the web about the label option for this type of map and could not find anything.
For example:
```
library(tmaptools)
  library(sf)
  library(mapview)
  geocode_OSM("Sacramento, California")
  location <- data.frame(place="Sacramento, CA",lat=-121.49440,lon=38.58157)
  location
  locations <- st_as_sf(location, coords = c("lat", "lon"), crs = 4326)
   str(locations)
 mapview(locations,map.types = "Esri.WorldImagery")
```

**Comment by tim-salabim** [comment]
If you install [leafem](https://github.com/r-spatial/leafem) from github with

```r
remotes::install_github("r-spatial/leafem")
```

you can do

```r
mapview(locations, map.types = "Esri.WorldImagery")@map %>%
  leaflet::addProviderTiles("CartoDB.PositronOnlyLabels", group = "labels") %>%
  leafem::updateLayersControl(addOverlayGroups = "labels")
```

![Screenshot from 2019-11-13 20-33-23](https://user-images.githubusercontent.com/2826432/68797439-e3609a80-0654-11ea-81d7-bb0c9d6e5dfa.png)

Is that what you are looking for?

**Comment by FelipeCarrillo** [comment]
Yes, this is great thanks. Is there s way to custom zoom with code? Or pushing the  + - signs is tje only way to zoom in/out?

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 13, 2019 at 11:34 AM, tim-salabim<notifications@github.com> wrote:   
If you install leafem from github with
remotes::install_github("r-spatial/leafem")
you can do
mapview(locations, map.types = "Esri.WorldImagery")@map %>%
  leaflet::addProviderTiles("CartoDB.PositronOnlyLabels", group = "labels") %>%
  leafem::updateLayersControl(addOverlayGroups = "labels")


Is that what you are looking for?

**Comment by tim-salabim** [comment]
you can use `leaflet::setView` for custom zoom definition at render time, or this little snippet that let's you adjust the zoom level after the map has rendered:

https://gist.github.com/tim-salabim/7c4c5a98335f2b41f8a6b26e96825c8f#adjust-zoom-level

**Comment by FelipeCarrillo** [comment]
This is really helpful...thanks for the great work on these packages. 

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 13, 2019 at 11:44 AM, tim-salabim<notifications@github.com> wrote:   
you can use leaflet::setView for custom zoom definition at render time, or this little snippet that let's you adjust the zoom level after the map has rendered:

https://gist.github.com/tim-salabim/7c4c5a98335f2b41f8a6b26e96825c8f#adjust-zoom-level

**Comment by tim-salabim** [comment]
You're welcome! If this resolved your issue, please close. Thanks
