### ISSUE TITLE
multiple csv files on same leaflet map

### ISSUE THREAD

**Issue by FelipeCarrillo** [r-spatial/mapview#250]
Hi;
I have multiple csv files that I need to visualize on the same map. Can someone point out to an example on how to achieve that? I don't have a reproducible example at the moment but I could extract a few records from my csv files if necessary.

**Comment by tim-salabim** [comment]
Without seeing what they look like, I can't help. I usually advise to just throw stuff at mapview and see what happens. So what happens when you do:

```r
mapview("/path/to/csv.csv")
```
?

**Comment by FelipeCarrillo** [comment]
Will try that. Otherwise, will post 4 small csv files with lat and lon coordinates.

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 9, 2019 at 10:48 PM, tim-salabim<notifications@github.com> wrote:   
Without seeing what they look like, I can't help. I usually advise to just throw stuff at mapview and see what happens. So what happens when you do:
mapview("/path/to/csv.csv")
?
