### ISSUE TITLE
Piping into leaflet::hideGroup

### ISSUE THREAD

**Issue by kbvernon** [r-spatial/mapview#251]
If I have two rasters, r1 and r2, the following code throws up an error re: leaflet not handling the mapview S4 class:

    mapview(r1, layer.name = "r1") +
      mapview(r2, layer.name = "r2")  %>%
      leaflet::hideGroup(group = "r2")

It would be nice, however, if this functionality were available, instead of having to use `@map` to push the leaflet map through the pipe, especially as this seems like a common use case.

On that note, it would be really helpful if you all mentioned in your R documentation that layer.name is sent to the group parameter in the leaflet::addRasterImage call. That was not obvious, and I had to dig through your code to find it.

Thanks  in advance! Also, mapview is awesome!

**Comment by tim-salabim** [comment]
Thanks for bringing this up. This is a rather long standing issue. In retrospect, the design choice to use S4 class for mapview wasn't the smartest, but it is what it is at the moment. I don't think there is an easy way to solve this without changing either mapview or leaflet substantially. 

Regarding your second comment, how would you feel about submitting a PR that makes it clear that `layer.name` is passed on to the `group` argument in leaflet (which is true for both rater and vector data)?

**Comment by kbvernon** [comment]
Hi, Tim. Thanks for your reply. I will submit a PR for this soon. (May take a minute as I'm new to Github, so I'm still learning my way around.)

**Comment by tim-salabim** [comment]
@kbvernon in the current description of the `layer.name` argument we have:

```
the name of the layer to be shown on the map. By default this is the character version of whatever is passed to x. NOTE: This is being passed to underlying leaflet functions as the group argument. So if you use mapview to set up a map and want to refer to a certain layer later on, this is what you should refer to in group.
```
Is this clear enough?

**Comment by kbvernon** [comment]
Hi, @tim-salabim, thanks. That's a great update. Apologies for not offering a pull request myself. Still haven't quite figured it out... Do I close this issue now, or is that up to you?

**Comment by tim-salabim** [comment]
I'm not sure if there is a rule for who's supposed to close issues. I guess it's mostly about mutual agreement. I usually close when I feel it is sufficiently solved with a note to "feel free to reopen" (as I'm doing now :-) ).
