### ISSUE TITLE
setting 'max.size' to Inf doesn't work

### ISSUE THREAD

**Issue by ervanSTRI** [r-spatial/mapview#255]
Hi there,

I am struggling to overlay several "large" rasters of 8mio pixels each. I keep getting an error message saying: 
"Error in leaflet::addRasterImage(map = m, x = x, colors = pal, project = FALSE,  : 
  Raster image too large; 7777234 bytes is greater than maximum 4194304 bytes"

To overcome the problem, I have compressed each raster to ~1.5 Mb and set the mapviewOptions to Inf as recommended on the [help page](https://rdrr.io/cran/leaflet/man/addRasterImage.html)
 > mapviewOptions()
platform            : leaflet 
basemaps            : CartoDB.Positron CartoDB.DarkMatter OpenStreetMap Esri.WorldImagery OpenTopoMap 
raster.size         : Inf 
mapview.maxpixels   : Inf 
plainview.maxpixels : Inf 

, but nothing works and I keep getting an error message. Any hint?
Thanks
Ervan

**Comment by tim-salabim** [comment]
Can you provide one of the raster images? Offline via mail is fine

**Comment by ervanSTRI** [comment]
Hi Tim,

I have tried to plot each raster separetely and that one poses problem. It is available [here](https://www.dropbox.com/s/cv3sd096gzhvk82/G24-25_SOLL_300m_binary_07.01.20.tif?dl=0)
Thanks
Ervan

**Comment by ervanSTRI** [comment]
@tim-salabim : By the way, I encounter another strange behaviour of mapview. I rasterized as systematic grid using "grid id" as raster value through fasterize::fasterize(..,field="grid.id"), and when I project it through mapview I got very odd values (with decimals whereas grid id are integers.

In mapview the grid id is: 6578010.3626...
![image](https://user-images.githubusercontent.com/20225141/72051551-cdbdc900-32c3-11ea-85bf-cadca8660a60.png)

, when it should be: 6569259
![image](https://user-images.githubusercontent.com/20225141/72051658-fd6cd100-32c3-11ea-9bd2-84a6cb386eae.png)

Any idea on what is going on here?

**Comment by tim-salabim** [comment]
I think you need to set `method = "ngb"` in the mapview call. By default it is set to `"bilinear"` which will interpolate ids (in your case) linearly and hence produce floats. See the respective help page for `projectRaster`

**Comment by ervanSTRI** [comment]
Great! Thanks! Any hint regarding the raster size issue?

**Comment by tim-salabim** [comment]
Haven't looked at it yet

**Comment by ervanSTRI** [comment]
Hi Tim. Just noticed that you were [advertising ](https://twitter.com/TimSalabim3/status/1264474432787165186) the new flatgeobuf format and already wrote a addFGB() function. Do you know if there is yet a way to convert sf objects into .fgb ?? 
Thanks

**Comment by tim-salabim** [comment]
If you have GDAAL 3.1.0 installed you can use `st_read` & `st_write` like for any other format.

**Comment by ervanSTRI** [comment]
Thanks Tim. I know it's not the best place to ask, but I could not upgrade gdal to 3.1 (nor compile sf with gdal 3.1) on Windows 10. I have tried through conda, but it didn't work. I know you are on Linux, but do have any clue regarding Windows? Seems a bit too fresh to be available yet... Thanks a lot for your help.

**Comment by ervanSTRI** [comment]
(by the way, shall we close this issue? Seems a bit outdated with all the recent development)

**Comment by tim-salabim** [comment]
I did compile GDAL 3.1.0 on linux from source. Judging from this,
https://trac.osgeo.org/gdal/wiki/BuildingOnWindows
compiling from source seems a little more involved on windows, which doesn't surprise me... There's a reason I am on linux :-)

Feel free to close if you think this is no longer an issue...

**Comment by ervanSTRI** [comment]
Thanks Tim! but it seems to be gdal1.4, not 3.1 :(
I agee that is a good reason to finally migrate on Linux...

**Comment by ervanSTRI** [comment]
Hi Tim,
A quick question: do you know how to round "mouse-over" information (aka "Layer GRID.ID" in the image below)?

![image](https://user-images.githubusercontent.com/20225141/83871033-972f9180-a72f-11ea-887a-5155cd6116af.png)

Those IDs are integers, and shouldn't have decimals... I have tried round(), but it obviously doesnt' work.

`mapview::mapview(round(grid2),legend = F,maxpixels =8061452,na.color="transparent",layer.name="GRID ID",method = "ngb",alpha.region=0)`

Any hint?? Many thanks
E

**Comment by tim-salabim** [comment]
Use parameter `query.digits` to control the rounding of the raster value query. Another option is to set `method = "ngb"` to use nearest neighbor interpolation in the reprojection of the grid.
