### ISSUE TITLE
Legend Not Accurate

### ISSUE THREAD

**Issue by Hansbrolo2k** [r-spatial/mapview#257]
I was working with South Sudan refugee crisis data and I'm having an issue with my code. The legend colors don't line up with the State colors I set for them. Any help would be appreciated.
[R Help.zip](https://github.com/r-spatial/mapview/files/4143381/R.Help.zip)

```r
#Install and access
# install.packages("tidyverse")
# install.packages("ggmap")
# install.packages("sf")
# install.packages("sp")
# install.packages("mapview")
# install.packages("ggrepel")
# install.packages("devtools")
library(devtools)
library(ggrepel)
library(tidyverse)
library(ggmap)
library(sf)
library(mapview)
# devtools::install_github("r-spatial/mapview@develop")

#google key and read files
register_google(key="...")
S.Sudan.Data <- read.csv(".../DTM_SSD_VNA_R6.csv")
chi_shape <- st_read(".../ssd_admbnda_adm1_imwg_nbs_20180817.shp")
as_tibble(chi_shape)

#subset the data and clean it up a bit
S.Sudan.Data.Subset <- S.Sudan.Data[c(13,12,9,8,95,23)]
S.Sudan.Data.Subset<- rename(S.Sudan.Data.Subset, Prior.place.of.habitual.residence=Place.of.habitual.residence.before.displacement.of.largest.IDP.group..state.)
S.Sudan.Data.Subset$Total.Refugees <- S.Sudan.Data$X..of.returnees..individuals.+S.Sudan.Data$X..of.IDPs..individuals.

#Prep for mapview and create a map with background as state boundaries
Place <- st_as_sf(S.Sudan.Data.Subset, coords = c("Longitude", "Latitude"),crs = 4326)
x <- mapview(chi_shape, zcol = "ADM1_EN", legend=T) + mapview(Place, zcol="Prior.place.of.habitual.residence", col.regions = c("red1", "forestgreen", "cornflowerblue", 'gold','darkorchid2','royalblue4','springgreen','darkorange','mediumvioletred','magenta','chartreuse'), legend=T, cex = "Total.Refugees")
x
```

**Comment by tim-salabim** [comment]
Sorry, I can't help you if you don't provide the data I need to reproduce the issue. Where can I find `ssd_admbnda_adm1_imwg_nbs_20180817.shp`?

**Comment by Hansbrolo2k** [comment]
I attached them as a zip file [DTM_SSD_VNA_R6.zip](https://github.com/r-spatial/mapview/files/4101888/DTM_SSD_VNA_R6.zip)
[ssd_adminboundaries_tabulardata.zip](https://github.com/r-spatial/mapview/files/4101891/ssd_adminboundaries_tabulardata.zip)

**Comment by tim-salabim** [comment]
There's no `.shp` file in those zips

**Comment by Hansbrolo2k** [comment]
Sorry about that. I just put them both into this file.
[R Help.zip](https://github.com/r-spatial/mapview/files/4113066/R.Help.zip)

**Comment by tim-salabim** [comment]
Sorry, but this is still not enough! A shapefile consists of at least 3 files, so as long as you don't also provide the `.prj` and `.dbf` files, I cannot read the `.shp` file.

See http://switchfromshapefile.org/ for details and some better alternatives.

**Comment by Hansbrolo2k** [comment]
I'm really sorry about that. Thank you for bearing with me. 
[R Help.zip](https://github.com/r-spatial/mapview/files/4143380/R.Help.zip)

**Comment by tim-salabim** [comment]
Before I jump into any unnecessary debugging, can you please install the latest development version and try again. I've just pushed an update for a similar issue, so maybe that solves it already

```r
remotes::install_github("r-spatial/mapview@develop")
```

**Comment by Hansbrolo2k** [comment]
Okay. I added some more comments and installed that package. It hasn't solved the problem yet.

**Comment by tim-salabim** [comment]
@Hansbrolo2k the above commit should solve your issue at least partly. Colors should now be correctly displayed. The only thing that is missing is a legend entry for NAs. At this stage I am not sure how to solve this, but maybe I'll have a revelation soon.

Can you please re-test and report back if it works for you now?

**Comment by Hansbrolo2k** [comment]
Hello, I've been trying to get it to work for the last few days, but I'm having trouble with the mapview legend function.  I keep getting an error for using it saying, "no applicable method for 'droplevels' applied to an object of class "character"". I believe I want to insert a list rather than a character class, but I'm probably just using it wrong. Here is what I have been trying: 
mapviewLegend(Place, colors=c("red1", "forestgreen", "cornflowerblue", 'gold','darkorchid2','royalblue4','springgreen','darkorange','mediumvioletred','magenta','chartreuse'), values=c('Abyei Administrative Area','Central Equatoria','Eastern Equatoria','Jonglei','Lakes','Northern Bahr El Ghazal','Unity','Upper Nile','Warrap','Western Bahr El Ghazal','Western Equatoria'))

Thank you again for all your help.

**Comment by tim-salabim** [comment]
You shouldn' need to use `mapviewLegend` directly. Your example above works for me now. Doesn't it for you?

**Comment by Hansbrolo2k** [comment]
No. I'm still having the same problem. I'm using R x64 3.6.2 if that makes a difference. Here is what I have now
#Install and access
#install.packages("tidyverse")
#install.packages("ggmap")
#install.packages("sf")
#install.packages("sp")
#install.packages("mapview")
#install.packages("ggrepel")
#install.packages("devtools")
library(devtools)
library(ggrepel)
library(tidyverse)
library(ggmap)
library(sf)
library(mapview)
devtools::install_github("r-spatial/mapview@develop")

#google key and read files
register_google(key="...")
S.Sudan.Data <- read.csv(".../DTM_SSD_VNA_R6.csv")
chi_shape <- st_read(".../ssd_admbnda_adm1_imwg_nbs_20180817.shp")
as_tibble(chi_shape)

#subset the data and clean it up a bit
S.Sudan.Data.Subset <- S.Sudan.Data[c(13,12,9,8,95,23)]
S.Sudan.Data.Subset<- rename(S.Sudan.Data.Subset, Prior.place.of.habitual.residence=Place.of.habitual.residence.before.displacement.of.largest.IDP.group..state.)
S.Sudan.Data.Subset$Total.Refugees <- S.Sudan.Data$X..of.returnees..individuals.+S.Sudan.Data$X..of.IDPs..individuals.

### factor ================================================================
factorPalette <- function(palette,
                          domain,
                          na.color,
                          ...) {
  leaflet::colorFactor(palette = palette,
                       domain = domain,
                       na.color = na.color,
                       ...)
}
factorLegend <- function(map,
                         position,
                         values,
                         colors,
                         na.color,
                         layer.name) {
  pal <- factorPalette(palette = zcolColors(x = values,
                                            colors = colors,
                                            na.color = na.color,
                                            return.sorted = TRUE),
                       domain = values,
                       na.color = na.color)
  mvAddLegend(isAvailableInLeaflet()$leggrp,
              layer.name,
              map = map,
              position = position,
              pal = pal,
              values = values,
              opacity = 1,
              title = ifelse(length(values) > 1, layer.name, ""))
}
### character =============================================================
characterLegend <- function(map,
                            position,
                            values,
                            colors,
                            na.color,
                            layer.name) {
  if( is.function(colors)) {
    vals = unique(values[!is.na(values)])
  } else {
    vals = values
  }
  pal <- factorPalette(palette = zcolColors(x = vals,
                                            colors = colors,
                                            na.color = na.color,
                                            return.sorted = TRUE),
                       domain = values,
                       na.color = na.color)
  mvAddLegend(isAvailableInLeaflet()$leggrp,
              layer.name,
              map = map,
              position = position,
              pal = pal,
              values = values,
              opacity = 1,
              title = ifelse(length(values) > 1, layer.name, ""))
}
### numeric ===============================================================
numericPalette <- function(palette,
                           domain,
                           na.color,
                           ...) {
  leaflet::colorNumeric(palette = palette,
                        domain = domain,
                        na.color = na.color,
                        ...)
}
binPalette <- function(palette,
                       domain,
                       bins,
                       na.color,
                       ...) {
  leaflet::colorBin(palette = palette,
                    domain = domain,
                    bins = bins,
                    na.color = na.color,
                    ...)
}
numericLegend <- function(map,
                          position,
                          values,
                          colors,
                          at,
                          na.color,
                          layer.name) {
  n_unique <- ifelse(is.null(at), length(unique(values)), length(at))
  if (is.null(at)) {
    atc <- lattice::do.breaks(range(values, na.rm = TRUE),
                              length(unique(values)))
  } else atc <- at
  if (is.null(at) & n_unique <= 11 & all(unique(values) %% 1 == 0, na.rm = TRUE)) {
    factorLegend(map = map,
                 values = as.factor(unique(values)),
                 colors = colors,
                 position = position,
                 layer.name = layer.name,
                 na.color = na.color)
  } else if (n_unique <= 11) {
    if (anyNA(values)) values <- c(atc, NA) else values <- atc
    pal <- binPalette(palette = colors(n_unique),
                      domain = atc,
                      bins = atc,
                      na.color = na.color)
    mvAddLegend(isAvailableInLeaflet()$leggrp,
                layer.name,
                map = map,
                position = position,
                pal = pal,
                values = values,
                opacity = 1,
                title = ifelse(length(values) > 1, layer.name, ""))
  } else {
    pal <- numericPalette(palette = colors(n_unique),
                          domain = values,
                          na.color = na.color)
    mvAddLegend(isAvailableInLeaflet()$leggrp,
                layer.name,
                map = map,
                position = position,
                pal = pal,
                values = values,
                opacity = 1,
                title = ifelse(length(values) > 1, layer.name, ""))
  }
}
mvAddLegend = function(grp_avail = isAvailableInLeaflet()$leggrp,
                       layer.name, ...) {
  if (grp_avail) leaflet::addLegend(..., group = layer.name) else
    leaflet::addLegend(...)
}
### mapviewLegend =========================================================
mapviewLegend <- function(values,
                          colors,
                          at,
                          na.color,
                          layer.name,
                          position = mapviewGetOption("legend.pos")) {
  if (!is.function(colors) &
      inherits(colors, "character") &
      length(colors) > 1) {
    if (length(colors) == length(values)) {
      clrs = unique(colors)
      indx = as.numeric(unique(droplevels(values)))
      colors = clrs[order(indx)]
    } else {
      colors = colors[sort(as.numeric(unique(values)))]
    }
    if (is.factor(values)) values = droplevels(values)
    colors = grDevices::colorRampPalette(colors)(length(levels(values)))
  }

  if (is.function(colors))
    colors = colors(length(unique(values)))

  function(map) {

    # if values inherits from more than one class, select
    value.class = class(values)[length(class(values))]
    switch(value.class,
           factor = factorLegend(map,
                                 position = position,
                                 values = levels(values),
                                 colors = unique(colors),
                                 na.color = na.color,
                                 layer.name = layer.name),
           character = characterLegend(map,
                                       position = position,
                                       values = values,
                                       colors = colors,
                                       na.color = na.color,
                                       layer.name = layer.name),
           numeric = numericLegend(map,
                                   position = position,
                                   values = values,
                                   colors = colors,
                                   at = at,
                                   na.color = na.color,
                                   layer.name = layer.name),
           units = numericLegend(map,
                                 position = position,
                                 values = as.numeric(values),
                                 colors = colors,
                                 at = at,
                                 na.color = na.color,
                                 layer.name = layer.name),
           integer = numericLegend(map,
                                   position = position,
                                   values = values,
                                   colors = colors,
                                   at = at,
                                   na.color = na.color,
                                   layer.name = layer.name))
  }
}
### legacy ================================================================
addVectorLegend <- function(x,
                            map,
                            zcol,
                            at,
                            col.regions,
                            na.color) {
  is.fact <- is.factor(x@data[, zcol])
  if (is.fact) {
    vals <- as.character(x@data[, zcol])
  } else {
    vals <- x@data[, zcol] # orig values needed for legend creation later on
  }
  if (is.null(at)) {
    if (is.fact) {
      at <- vals
    } else {
      at <- lattice::do.breaks(range(vals,
                                     na.rm = TRUE),
                               length(vals))
    }
  }
  if (any(is.na(vals))) {
    leg_vals <- c(at, NA)
  } else leg_vals <- at
  if (is.function(col.regions)) col.regions <- col.regions(length(at))
  if (is.fact) {
    pal2 <- leaflet::colorFactor(palette = col.regions,
                                 domain = at,
                                 na.color = col2Hex(na.color))
  } else {
    if (length(at) > 11) {
      pal2 <- leaflet::colorNumeric(palette = col.regions,
                                    domain = at,
                                    na.color = col2Hex(na.color))
    } else {
      pal2 <- leaflet::colorBin(palette = col.regions,
                                bins = at, #length(at),
                                domain = at,
                                na.color = col2Hex(na.color))
    }
  }
  m <- leaflet::addLegend(map = map,
                          position = mapviewGetOption("legend.pos"),
                          values = leg_vals,
                          pal = pal2,
                          opacity = 1,
                          labFormat = labelFormat(big.mark = ""),
                          title = zcol)
  return(m)
}
### raster
addRasterLegend <- function(x,
                            map,
                            title,
                            group,
                            at,
                            col.regions,
                            na.color) {
  is.fact <- is.factor(x)
  if (is.fact) {
    vals <- as.character(x[])
  } else if (inherits(x, "stars")) {
    vals = as.vector(x[, , , 1][[1]][])
  } else {
    vals <- x[] # orig values needed for legend creation later on
  }
  if (is.null(at)) {
    if (is.fact) {
      at <- vals
    } else {
      at <- lattice::do.breaks(range(vals,
                                     na.rm = TRUE),
                               length(vals))
    }
  }
  if (any(is.na(vals))) {
    leg_vals <- c(at, NA)
  } else leg_vals <- at
  if (is.function(col.regions)) col.regions <- col.regions(length(at))
  if (is.fact) {
    pal2 <- leaflet::colorFactor(palette = col.regions,
                                 domain = at,
                                 # levels = as.character(levels(x)[[1]][, 2]),
                                 na.color = col2Hex(na.color))
  } else {
    if (length(at) > 11) {
      pal2 <- leaflet::colorNumeric(palette = col.regions,
                                    domain = at,
                                    na.color = col2Hex(na.color))
    } else {
      pal2 <- leaflet::colorBin(palette = col.regions,
                                bins = at, #length(at),
                                domain = at,
                                na.color = col2Hex(na.color))
    }
  }
  if (isAvailableInLeaflet()$leggrp) {
    m <- leaflet::addLegend(map = map,
                            position = mapviewGetOption("legend.pos"),
                            values = leg_vals,
                            group = group,
                            pal = pal2,
                            opacity = 1,
                            labFormat = labelFormat(big.mark = ""),
                            title = title)
  } else {
    m <- leaflet::addLegend(map = map,
                            position = mapviewGetOption("legend.pos"),
                            values = leg_vals,
                            pal = pal2,
                            opacity = 1,
                            labFormat = labelFormat(big.mark = ""),
                            title = title)
  }
  return(m)
}
## legend for plainview, slideview, cubeview ==============================
rasterLegend <- function(key) {
  draw.colorkey(key = key, draw = TRUE)
}

#Prep for mapview and create a map with background as state boundaries
Place <- st_as_sf(S.Sudan.Data.Subset, coords = c("Longitude", "Latitude"),crs = 4326)
x <- mapview(chi_shape, zcol = "ADM1_EN", legend=T) + mapview(Place, zcol="Prior.place.of.habitual.residence", col.regions = c("red1", "forestgreen", "cornflowerblue", 'gold','darkorchid2','royalblue4','springgreen','darkorange','mediumvioletred','magenta','chartreuse'), legend=T, cex = "Total.Refugees")
x

And I'm still getting the wrong colors in the regions
![image](https://user-images.githubusercontent.com/60213081/74509783-571e7780-4ed0-11ea-9051-426873764bc3.png)

**Comment by tim-salabim** [comment]
This should work now. Please feel free to reopen if the issue still persists
