### ISSUE TITLE
Background maps not displayed with current R 3.6.2/RStudio 1.2.5033 versions

### ISSUE THREAD

**Issue by nekronaut** [r-spatial/mapview#259]
After updating to the current R/RStudio versions (R 3.6.2 and RStudio 1.2.5033) background maps are no longer displayed in the RStudio viewer window. I have tried numerous providers, so that I believe all background maps to be affected. The only workaround is to use the  `viewer.suppress = TRUE` option, which I find rather inconvienient. I have given detailed session info [here](https://stackoverflow.com/questions/60074695/mapview-leaflet-background-maps-not-visible-in-r-3-6-2-rstudio-1-2-5033). Is this just me, or have other experienced similar problems?

**Comment by tim-salabim** [comment]
I can't reproduce this behaviour. Everything works fine for me. From your SO post it sounds more like a firewall/proxy issue. Maybe your organisation's IT is hardwiring software version numbers into exceptions? Happened to me once...

**Comment by nekronaut** [comment]
Thanks for the reply! At least I now know that the issue is specific to my environment and I will see, if our IT can do something about it.

**Comment by tim-salabim** [comment]
In case you find it's not, feel free to reopen
