### ISSUE TITLE
Shift in raster projection

### ISSUE THREAD

**Issue by ervanSTRI** [r-spatial/mapview#261]
Hi,

I am experiencing a strange behaviour of mapview, when plotting a raster.
In the picture below, the shaded area is the raster (as it is projected), but when I pass the pointer below it, I do have a grid id (LAYER GRID ID) while it shouldn't. My gut feeling is that location from the pointer is right, but the "image" is shifted up.

![image](https://user-images.githubusercontent.com/20225141/74539502-6b995900-4f3e-11ea-8168-4bdc720b9c0e.png)

I am using the following code:
`mapview::mapview(grid,legend = F,maxpixels =  7694880,na.color="transparent",layer.name="GRID ID",method = "ngb",alpha.region=0.2)`

Any idea of what could cause this?
Thanks

**Comment by ervanSTRI** [comment]
Hi, 
Let me develop the issue a bit (might not be the most suitable place though). I have a raster projected in EPSG:21781 (avaiable [here](https://www.dropbox.com/s/k4ncaz25eb9b0mr/grid100.tif?dl=0)) that I'd like to display with mapview. Raster values correspond to the grid id, and need to be preserved.
If I understood correctly, mapview is calling leaflet::addRasterImage() to do so, and reproject the raster into EPSG:3857 (pseudo-mercator) through raster::projectRaster(). 
The first problem is that the reprojection is done through a 'bilinear' method (by default) whereas I need the nearest-neighbor method. To overcome this problem, I have reprojected the raster manually using the following command:

`grid <- raster::raster("~/grid100.tif")`
`grid2 <- projectRaster(grid,crs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs",method="ngb")`  # corresponding to epsg 3857

`summary(values(grid))`
 Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      1 1035406 2070572 2074309 3111142 4157490 3554337 

`summary(values(grid2))`
Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      1 1056410 2097896 2093243 3133844 4157490 3917853 

`table(is.na(match(values(grid),values(grid_ra2))))`
FALSE    TRUE 
6206341 1488539 

Conclusion: 1'488'539 cells are dropped after reprojection... 
Any idea of what is going on here?
Thanks

**Comment by tim-salabim** [comment]
you can set the method to ngb in `mapview(x, method = "ngb")`

**Comment by ervanSTRI** [comment]
Hi Tim,
Thanks for getting in touch. Indeed I was using mapview(x,method="ngb") will plotting my raster. The problem while doing this is that it end up with grid cells (pixels) missing after reprojection. I need to keep/show all cells from my original raster, but I guess this is due to the distorsion going from a "planar" to a "hemi-spherical" projection...

**Comment by tim-salabim** [comment]
If you want a basemap with mapview, you have two options:

1. the usual reprojection to 3857 with all consequences
2. find a wmts tile provider that meets the projection requirements and use that (have a look [here](http://api3.geo.admin.ch/services/sdiservices.html#wmts) for swiss options).

The other thing you can do is set `native.crs = TRUE` which will plot the original raster without a basemap

**Comment by ervanSTRI** [comment]
Really appreciate your helpful comment. Will explore these options.
Thanks for all!

**Comment by tim-salabim** [comment]
You're right actually. I forgot that leaflet doesn't support native crs for rasters, only vector data. My bad. What you could try is to convert your raster to polygons and try to plot them with `leafgl`. Not sure if it will work, but worth a shot.

**Comment by ervanSTRI** [comment]
Great thanks! Will give it a try.

**Comment by ervanSTRI** [comment]
@tim-salabim: For your personnal record, I have tried to plot my data with leafgl, but did not succeed (nothing appears, even after reprojecting manually into EPSG 3857). However, mapview did the job smoothly. It took 75 sec to generate and about the same to print a leaflet  with 5 layers, 154'176 polygons each, totaling 242.3 Mb. Not bad!! (I have a 32 Gb RAM machine though) Good to know.

**Comment by tim-salabim** [comment]
For leafgl the data need to be in 4326, not 3857. But good to hear that mapview did the job!

**Comment by ervanSTRI** [comment]
One more thing: why not providing a way to specify a grouping factor to generate layers for vectors/sf?
So is done with rasterStacks or in addGlPolygons(x,group=XX). But to do the same in mapView, sf objects needs either to be split(), or subsetted/plotted by group individually... not super efficient.

**Comment by tim-salabim** [comment]
I am not quite sure what you mean... The group equivalent in mapview is layer.name. If you want to plot multiple layers at once and have a grouping column, you can use `burst`. See

https://r-spatial.github.io/mapview/articles/articles/mapview_02-advanced.html#using-burst

Or are you thinking of something else?

**Comment by ervanSTRI** [comment]
I see. I will have to reshape my object then, as I have a column specifying the different groups. I am using a combination of data.table and sf, and a melt-like approach. As far as I understand, `burst` does use the different columns as layers, but not a colum (with grouping factors) to filter and return corresponding rows into various layers, or I am missing something here?

**Comment by tim-salabim** [comment]
Hm... that seems like a scenario that we should support. Would you mind opening another issue with a reprex for that scenario?

**Comment by ervanSTRI** [comment]
Sure. Thanks

**Comment by tim-salabim** [comment]
Thanks!

**Comment by ervanSTRI** [comment]
The issue is open here: https://github.com/r-spatial/mapview/issues/269#issue-574654667
