### ISSUE TITLE
[feature request] use webshot2 instead of webshot in mapshot

### ISSUE THREAD

**Issue by baldeagle** [r-spatial/mapview#262]
Phantom.js has been end of life for a while.  Lets move on to headless chrome.

**Comment by tim-salabim** [comment]
AFAIKT, webshot2 is not on CRAN. Once it is, I'd appreciate a PR for this...

**Comment by baldeagle** [comment]
When trying to integrate it into my local fork, I get a error in s$close - not a function.
Is there a guide or tutorial to learn how to troubleshoot R pacakges?  I would like to make a pull request, but I'm new at this.

**Comment by tim-salabim** [comment]
Sorry I don't know. But I wouldn't worry until it is released on cran. I won't merge the pr before anyways

**Comment by tim-salabim** [comment]
Just checked, webshot2 is still not on CRAN. I'll close the issue here & integrate it once it hits CRAN
