### ISSUE TITLE
mapview static labels offset and direction

### ISSUE THREAD

**Issue by maxbre** [r-spatial/mapview#263]
it seems to me not working neither the offset of static labels nor the direction 

```
mapview(breweries)%>%
  addStaticLabels(label = breweries$brewery,
                  noHide = TRUE,
                  direction = 'auto',
                  offset=c(100,100),
                  textOnly = TRUE,
                  textsize = "10px",
                  permanent=TRUE)

```

**Comment by tim-salabim** [comment]
Thanks, you're right. In [this line](https://github.com/r-spatial/leafem/blob/master/R/labels.R#L96) we need to reverse the arguments passed to `modifyList`, then things should work... I'll get to it soon

**Comment by maxbre** [comment]
that's great, keeep on going with the excellent work, thank you

**Comment by tim-salabim** [comment]
Should work now if you reinstall **leafem** from github

**Comment by maxbre** [comment]
perfect!
