### ISSUE TITLE
Exporting map to html with embedded png-popups

### ISSUE THREAD

**Issue by nekronaut** [r-spatial/mapview#264]
According to the package documentation, a mapview object with locally stored popup images can be exported to html. The documentation states the following: 

> NOTE 2: In case you want to save a map with popupGraphs or popupImages the respective graph/image files will be located one level above the specified target location. In case you want to move the html file, make sure to also move the respective *-graphs folder one level above.

I interpret this to mean that the images are stored one level up in the file tree hierarchy, NOT inside the folder containing the remaining files connected to the html. Unfortunately, I don't see any folder/image files saved one level up and my html-map only produces greyed out popups. There is also a reference to the issue [here](https://github.com/r-spatial/mapview/issues/168#issuecomment-409223508). Is there anything I else need to specify in the `mapshot` command.?

    library(sf)
    library(dplyr)
    library(mapview)

    pnt <- data.frame(x = 174.764474, y = -36.877245) %>% 
      st_as_sf(coords = c("x", "y"), crs = 4326)

    img = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Mount_Eden.jpg/640px-Mount_Eden.jpg"
    download.file(img,destfile=paste0(getwd(), "/mounteden.jpg"))
    img_local = paste0(getwd(), "/mounteden.jpg")

    m = mapview(pnt, popup = leafpop::popupImage(img_local))
    mapshot(m,url = paste0(getwd(), "/testmap.html"))

**Comment by tim-salabim** [comment]
Please see [this example](https://github.com/r-spatial/leafpop#addpopupimages--popupimage) in the **leafpop** repository. For exactly the reason that you describe here, we've re-implemented the popup functions as `add*` functions so that the images are actually saved in the correct place. This approach should also work with mapview, e.g.

```r
library(sf)
library(dplyr)
library(mapview)

pnt <- data.frame(x = 174.764474, y = -36.877245) %>% 
  st_as_sf(coords = c("x", "y"), crs = 4326)

img = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Mount_Eden.jpg/640px-Mount_Eden.jpg"
download.file(img,destfile=paste0(getwd(), "/mounteden.jpg"))
img_local = paste0(getwd(), "/mounteden.jpg")

m = mapview(pnt, popup = FALSE) %>%
  addPopupImages(img_local, group = "pnt"))

mapshot(m, url = paste0(getwd(), "/testmap.html"))
```

Please let me know if this works for you...
Maybe we can make this a little more intuitive in mapview...

**Comment by nekronaut** [comment]
Thanks a lot for pointing out the `addPopupImages`! It's not always easy to stay on top of the most up-to-date syntax. This works for me:

    m = mapview(pnt, popup = FALSE)
    m = m@map %>% 
      leafpop::addPopupImages(img_local, group = "pnt")
    mapshot(m, url = paste0(getwd(), "/testmap.html"))

Interestingly, including `layer.name = "Mount Eden"` in the `mapview` call doesn't, i.e. not popup appears. Everything else worked just fine!

**Comment by tim-salabim** [comment]
Yeah, this is something that has popped up in the past. In mapview layer.name is passed on to leaflet as group, so if you adjust group in addPopupImages, it should work.

**Comment by nekronaut** [comment]
Ah, now I understand. Yes, that worked.

**Comment by tim-salabim** [comment]
That's what happens if you start programming away without thinking about design principles... I should at least document that properly somewhere! 

Thus, I'm leaving this open as a note to self!!

**Comment by alaindanet** [comment]
This example of leafpop respository unfortunately fails on my computer.

``` r
library(reprex)
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.0, PROJ 5.2.0
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(mapview)
#> Warning in (function (n) : input string '/home/alain/Téléchargements/R-4.0.5/
#> library/methods/R/methods' cannot be translated to UTF-8, is it valid in
#> 'ANSI_X3.4-1968'?
#> Warning in (function (n) : input string '/home/alain/Téléchargements/R-4.0.5/
#> library' cannot be translated to UTF-8, is it valid in 'ANSI_X3.4-1968'?
library(leafpop)

pnt <- data.frame(x = 174.764474, y = -36.877245) %>% 
  st_as_sf(coords = c("x", "y"), crs = 4326)

img = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Mount_Eden.jpg/640px-Mount_Eden.jpg"
download.file(img,destfile=paste0(getwd(), "/mounteden.jpg"))
img_local = paste0(getwd(), "/mounteden.jpg")

m = mapview(pnt, popup = FALSE) %>%
  addPopupImages(img_local, group = "pnt")
#> Error: $ operator not defined for this S4 class

mapshot(m, url = paste0(getwd(), "/testmap.html"))
#> Error in mapshot(m, url = paste0(getwd(), "/testmap.html")): objet 'm' introuvable

sessionInfo()
#> R version 4.0.5 (2021-03-31)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Debian GNU/Linux 10 (buster)
#> 
#> Matrix products: default
#> BLAS:   /home/alain/.Renv/versions/4.0.5/lib/R/lib/libRblas.so
#> LAPACK: /home/alain/.Renv/versions/4.0.5/lib/R/lib/libRlapack.so
#> 
#> locale:
#>  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
#>  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
#>  [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] leafpop_0.1.0   mapview_2.10.0  dplyr_1.0.4     sf_0.9-7       
#> [5] reprex_1.0.0    nvimcom_0.9-122
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.6              svglite_2.0.0           lattice_0.20-41        
#>  [4] png_0.1-7               class_7.3-18            leaflet.providers_1.9.0
#>  [7] assertthat_0.2.1        digest_0.6.27           utf8_1.2.2             
#> [10] R6_2.5.1                backports_1.2.1         stats4_4.0.5           
#> [13] evaluate_0.14           e1071_1.7-4             highr_0.9              
#> [16] pillar_1.6.4            rlang_0.4.12            uuid_1.0-3             
#> [19] raster_3.4-5            rmarkdown_2.11          styler_1.4.1           
#> [22] webshot_0.5.2           stringr_1.4.0           htmlwidgets_1.5.3      
#> [25] munsell_0.5.0           compiler_4.0.5          xfun_0.28              
#> [28] pkgconfig_2.0.3         systemfonts_1.0.0       base64enc_0.1-3        
#> [31] htmltools_0.5.1.1       tidyselect_1.1.1        tibble_3.1.6           
#> [34] codetools_0.2-18        fansi_0.5.0             crayon_1.4.2           
#> [37] grid_4.0.5              satellite_1.0.4         lifecycle_1.0.1        
#> [40] DBI_1.1.1               magrittr_2.0.1          units_0.6-7            
#> [43] scales_1.1.1            KernSmooth_2.23-18      stringi_1.7.6          
#> [46] fs_1.5.1                leaflet_2.0.4.1         sp_1.4-5               
#> [49] ellipsis_0.3.2          brew_1.0-6              generics_0.1.0         
#> [52] vctrs_0.3.8             RColorBrewer_1.1-2      tools_4.0.5            
#> [55] leafem_0.1.6            glue_1.5.1              purrr_0.3.4            
#> [58] crosstalk_1.1.1         yaml_2.2.1              colorspace_2.0-0       
#> [61] classInt_0.4-3          knitr_1.36
```

<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by tim-salabim** [comment]
@alaindanet where in the leafpop repo did you find that example?

**Comment by alaindanet** [comment]
Dear Tim,

sorry my first message was misleading. I just used the example that you provided above on this thread.

I was looking to do a heavy local map (not enough RAM for selfcontained one).
It did not work as the html created by `mapshot` was looking at a image directory that did not exist.
I ran a grep on the html created by mapshot 
`grep "png" map_abundance.html` 
 `<image src='../graphs/tot_abun_site_S9987.png'`
So the html was looking for a directory above the html directory which is called `graphs`. Then I have just symlinked the actual directory containing the images to `../graphs`. 

This workaround works but I can imagine that it becomes more complicated if you have several maps which relies on images that exists in different directory.

**Comment by tim-salabim** [comment]
Ok,
the above code should work if you explicitly call the `@map` slot of the mapview object:

```r
m = mapview(pnt, popup = FALSE)@map %>%
  addPopupImages(img_local, group = "pnt")
```

**Comment by alaindanet** [comment]
It works, thank you.

However, the html is still looking for a folder named "graphs" that was not created.

```
grep "jpg" testmap.html
>  <image src='../graphs/mounteden.jpg' width=300 height=200.15625>
```
So it is still necessary to create a folder called `graphs`, above the location of the map, and put the images in.
