### ISSUE TITLE
Error in collapse(tmp, indent = indent) : R character strings are limited to 2^31-1 bytes

### ISSUE THREAD

**Issue by astraetech** [r-spatial/mapview#265]
Hi,
Thank you for a fantastic package! 
It seems when I have 123099 points the mapview is giving this error. I can't share the data unfortunately so can't build a reprex.

```r
mapv_file_limp_1_1 <- mapview(filter(land_imp_1,!is.na(land_longitude)),
   xcol = "land_longitude",
   ycol = "land_latitude", color="magenta", col.regions="blue",maxpoints = 1000000,  selfContained = FALSE) # Worksd!
```
This is the actual output from Rstudio console. The error persists when I remove the maxpoints and selfContained arguments. I can plot parts of this file, like random 40k obs, but can't plot the whole file.

```r
> mapv_file_limp_1_1 <- mapview(filter(land_imp_1,!is.na(land_longitude)),
   xcol = "land_longitude",
   ycol = "land_latitude", color="magenta", col.regions="blue",maxpoints = 1000000,  selfContained = FALSE) # Worksd!
> mapv_file_limp_1_1 
Error in collapse(tmp, indent = indent) : 
  R character strings are limited to 2^31-1 bytes
```
I haven't been able to find this error referenced anywhere else, so I apologize in advances if it is a well-known issue/feature. Thank you for any help! Your package is a lifesaver as I'm trying to meet a grant deadline.

**Comment by tim-salabim** [comment]
It is not easy without a reprex. In any case, I don't think this is a mapview issue...
What happens if you assign your filtering to a variable first and try to plot that?

**Comment by astraetech** [comment]
It seems when I select just the lon and lat and obs_id, it manages to render a plot. So maybe a dataset size problem?

**Comment by tim-salabim** [comment]
Maybe... I can't help you if you don't provide a reproducible example! 
Why are you using `x_col` and `y_col`? What is `land_imp_1`? Is it a `sf` object? In any case, I don't think you will have much luck plotting 100k+ features with mapview. For this we have either [mapdeck](https://github.com/SymbolixAU/mapdeck) or [leafgl](https://github.com/r-spatial/leafgl)

**Comment by tim-salabim** [comment]
@astraetech in case you're still waiting for this to be resolved here, feel free to reopen, but I'd need a reprex...
