### ISSUE TITLE
cex is not changing with the proper amount 

### ISSUE THREAD

**Issue by beausoleilmo** [r-spatial/mapview#266]
I'm using a a function to change the size of points like this: 

`idsp$cex.activity = ifelse(idsp$pointtype=="Seen",1,2)`
![Screen Shot 2020-02-21 at 14 44 54](https://user-images.githubusercontent.com/15717151/75066514-fc30e580-54b8-11ea-8554-979b2e204f4f.png)

But even if I change that number, I get the same thing. Is that normal? 
`idsp$cex.activity = ifelse(idsp$pointtype=="Seen",1,3)`

![Screen Shot 2020-02-21 at 14 47 42](https://user-images.githubusercontent.com/15717151/75066611-271b3980-54b9-11ea-8d38-4f0c2803c9ec.png)

I used this code: 
```
    mapview(subidsp,
            zcol = "pointtype", 
            cex = "cex.activity",
            alpha = 0,
            color = pal(4),
            col.regions = pal(4),
            layer.name=("Activity"))

```

**Comment by tim-salabim** [comment]
Hi & sorry for the late reply. What you are after is possible, but currently not documented anywhere.

```r
mapview(subidsp,
            zcol = "pointtype", 
            cex = "cex.activity",
            min.rad = 1,
            max.rad = 2,
            alpha = 0,
            color = pal(4),
            col.regions = pal(4),
            layer.name=("Activity"))
```
should do what you want (though radii of 1&2 are really small). We internally map cex to radii between 3 and 15 with the exception of NA values whcih get mapped to 2. This is, however, likely to change soon, as we need a different approach when using flatgeobuf enoding to process things internally. One that change is made I will document it properly.

Does this solve your issue (for now)?

**Comment by beausoleilmo** [comment]
OK good to know. That works for the moment!
