### ISSUE TITLE
Legend and point not coloured the same way in mapview

### ISSUE THREAD

**Issue by beausoleilmo** [r-spatial/mapview#267]
I have a map where the point in the map and the legend doesn't correspond. 

![Screen Shot 2020-02-21 at 14 50 04](https://user-images.githubusercontent.com/15717151/75066853-c2acaa00-54b9-11ea-9b50-553204bff1aa.png)

"Roosting" should be orange, but the point should be orange as well... 

Here is the code: 

    pal = mapviewPalette("mapviewRasterColors")
    mapview(subidsp,
            zcol = "pointtype", 
            cex = "cex.activity",
            alpha = 0,
            color = pal(4),
            col.regions = pal(4),
            layer.name=("Activity"))

When I changed the factors of "pointtype" to numeric, I was able to get the same colour between the 2, but I got the wrong colour! It should be orange. 

    mapview(subidsp,
            zcol = "pttnum", 
            cex = "cex.activity",
            alpha = 0,
            color = pal(4),
            col.regions = pal(4),
            layer.name=("Activity"))

`pttnum` is the vector with the numeric values of the factors. 

The colour vector is that one: 
`c("#000004FF", "#781C6DFF", "#ED6925FF", "#FCFFA4FF")`

I guess there is a subsetting or indexing issue with the colour vector.

**Comment by tim-salabim** [comment]
Can you provide a reproducible example?

**Comment by elgabbas** [comment]
Hello,
I have the same issue in the legend in a shiny app. After filtering the data, it seems that the colours in the legend do not properly match the data. The colours of the points seem to be alright, but the interactive legend has an issue.

This is a reprex code:
```
library(shiny)
library(dplyr)
library(mapview)

breweries2 <- breweries %>% 
  mutate(
    ColCode = sample(c("#ff0000", "#008000", "#0000ff", "#808080", "#ffffff"), 224, replace = T),
    Col = ColCode,
    Col = str_replace(Col, "ff0000", "red"),
    Col = str_replace(Col, "008000", "green"),
    Col = str_replace(Col, "0000ff", "blue"),
    Col = str_replace(Col, "808080", "grey"),
    Col = str_replace(Col, "ffffff", "white"),
  )

ui <- fluidPage(
  selectizeInput(
    inputId = "Col", label = NULL,
    choices = c("red" = "#ff0000",
                "green" = "#008000",
                "blue" = "#0000ff",
                "grey" = "#808080",
                "white" = "#ffffff"),
    multiple = TRUE,
    options = list(
      placeholder = 'Enter colour')),
  
  leafletOutput("OutMapView", 750, 550)
)

server <- function(input, output) {
  breweries3 <- reactive({
    breweries2 %>%
      dplyr::filter(ColCode %in% input$Col)
  })
  
  output$OutMapView <- renderLeaflet({
    if(nrow(breweries3()) > 0){  
      mapView(
        breweries3(), legend = T, zcol = "Col",
        col = "black",
        col.regions = {
          breweries3() %>%
            pull(ColCode)
        },
        layer.name = "breweries3"
      )@map
    } else {
      mapview()@map
    }
  })
}

shinyApp(ui = ui, server = server)
```
When filtering multiple colours not in the same order, points were plotted nicely but see the legend.
![000](https://user-images.githubusercontent.com/7375051/84558333-61dc0280-ad32-11ea-8bc9-a324c3974e66.png)

> Please note that I am relatively beginner for both shiny and mapview, then the code I wrote might be not perfect.

**Comment by tim-salabim** [comment]
Thanks, should be solved now.
