### ISSUE TITLE
feature request: general 3D plots

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/mapview#27]
Hi, this is two-fold, one a heads-up about the "quadmesh" capability for WebGL via rgl and techniques in R that can generate its data structures from "spatial stuff", and two a request for more general 3D plotting for grids. 

Many rgl plots for raster are limited to regular grids, but if we use the features more directly there's no need for the mesh to be regular, but it does need to be a densified mesh of vertices. 

EDIT: updated to actually work, and use package on CRAN MDS 

Here is an example, using 'quadmesh': 

``` R
## install.packages('quadmesh")

library(quadmesh)
library(raster)
r <- setExtent(raster(volcano), c(0, nrow(volcano), 0, ncol(volcano)) * 2)
qm <- quadmesh(r, z = r)

library(rgl)
scl <- function(x) (x - min(x)) / diff(range(x))
nc <- 50
shade3d(qm, col = terrain.colors(nc)[(scl(qm$vb[3,]) * (nc - 1) + 1)][qm$ib])
```

In combination with the features of cubeView this would be incredibly powerful. 

I'm hoping to learn more about how to do this as well!

**Comment by mdsumner** [comment]
On reflection, why is cubeView in mapview? Perhaps better separated?

**Comment by fdetsch** [comment]
Any news on this matter yet? I'd love to see a **mapview** version of 

```{r}
library(rgl)
library(rasterVis)

## define a Raster object
data(volcano)
r <- raster(volcano)
extent(r) <- c(0, 610, 0, 870)

## extract sample points
xy <- sampleRandom(r, 100, xy = TRUE)     

## display them
plot3D(r, adjust = FALSE)
points3d(xy)
```

(taken from [SO](https://stackoverflow.com/questions/38926796/adding-point-locations-to-a-3d-dem-plot-in-r), credit to Oscar Perpiñán) which permits to ... well, throw a fancier look at DEMs as compared to **rgl**.

**Comment by mdsumner** [comment]
Discussion here, nothing concrete:

https://github.com/ropenscilabs/rivis

plotly is probably the most advanced now, for me nothing does the mesh in the native way that rgl uses. I have quadmesh for raster to mesh, sfdct for triangulations but nothing for vector mesh on CRAN yet. webgobe, icosa also relevant

**Comment by fdetsch** [comment]
Will have a deeper look into this, thanks!

Am 03.08.2017 5:02 nachm. schrieb "Michael Sumner" <notifications@github.com

**Comment by mdsumner** [comment]
The best for now is `rgl::rglwidget` which catches the current scene to file.
