### ISSUE TITLE
legend control the thousand separator

### ISSUE THREAD

**Issue by maxbre** [r-spatial/mapview#270]
by considering this reproducible example

`mapview(breweries, zcol = "founded")`

is there any way to control the thousand separator in the legend?

I've been trying this rough approach but without much success (apparently with none effect at all, neither an error or a warning is thrown out)

```
library(leaflet)
mapview(breweries, zcol = "founded",  labFormat=labelFormat(big.mark="."))
```

thanks

**Comment by tim-salabim** [comment]
This should work now. You can now pass `labFormat` via `...` to `leaflet::addLegend` (or any valid argument for that matter)
