### ISSUE TITLE
upcoming sf breaks mapview on CRAN

### ISSUE THREAD

**Issue by edzer** [r-spatial/mapview#271]
See
* https://www.r-spatial.org/r/2020/03/17/wkt.html
* https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt

It seems that mapview is not robust against the upcoming change in crs objects. Let me know if you need help!

**Comment by tim-salabim** [comment]
Is the above commit a future-proof change? If not, I think I would need some help...

**Comment by tim-salabim** [comment]
Seems resolved... ?
