### ISSUE TITLE
Cannot work with raster data 

### ISSUE THREAD

**Issue by jennasage** [r-spatial/mapview#275]
Mapview is not allowing me to plot my raster. The error I am getting is basically leafem::addHomeButton(m, ext, layer.name = layer.name) : 
  unused argument (layer.name = layer.name)

I know there was a recent update, so it may be a bug that I can get around. I just haven't used the package enough to trouble-shoot it myself

**Comment by tim-salabim** [comment]
```r
remotes::install_github("r-spatial/mapview@develop")
```
should solve the problem.
New version should hit CRAN soon.
