### ISSUE TITLE
mapview crashes on raster visualization if specifying col.regions

### ISSUE THREAD

**Issue by lbusett** [r-spatial/mapview#276]
Hi @tim-salabim 

   just noticed that this crashes on recently updated `mapview` (2.7.8 - on Ubuntu) : 

``` r
library(raster)
library(mapview)
f <- system.file("external/test.grd", package="raster")
r <- raster(f)
pal <- grDevices::colorRampPalette(RColorBrewer::brewer.pal(5, "RdYlGn"))
mapview(r, col.regions= pal(10))
```

, with error: 

> Error in col.regions(length(vals)) : 
>   could not find function "col.regions"

Removing the legend, works: 

``` r
library(raster)
library(mapview)
f <- system.file("external/test.grd", package="raster")
r <- raster(f)
pal <- grDevices::colorRampPalette(RColorBrewer::brewer.pal(5, "RdYlGn"))
mapview(r, col.regions= pal(10), legend = FALSE)
```

Culprit seems changes introduced in:

https://github.com/r-spatial/mapview/blob/28abca4d9fe8fcc73d1a73091e37ae125bb1e89d/R/raster.R#L147 

on latest commits.

HTH,

Lorenzo

**Comment by tim-salabim** [comment]
I assume this was just a toy example? 10 colors is not enough for the raster to be properly displayed. 

In any case this should now work (again) with either a color vector as in `col.regions = pal(10)` or just the function `col.regions = pal`. The latter is preferred as it lets mapview take care of the color mapping. Everything else is pretty much guesswork as to what the user intended. 

In your example, what should we do with a vector of 10 colors? Should we recycle? Should we try to be smart and expand the provided colors via `colorRampPalette` to the whole range of the data? Currently, mapview does the former, but I favour the latter, especially for numeric values... Opinions?

**Comment by lbusett** [comment]
Thanks for looking into this!

Yes, that was just a toy example. In the "real" code that brokw I had pal(100). However, I'll also check now the use of `col.regions = pal`: thanks for the hint. 

Regarding "what should we do with a vector of 10 colors", I agree that recycling makes little sense - expanding to the whole range seems much more better also to me.

**Comment by lbusett** [comment]
Ok. Tested and now working again as before. Thanks.

**Comment by tim-salabim** [comment]
> Regarding "what should we do with a vector of 10 colors", I agree that recycling makes little sense - expanding to the whole range seems much better also to me.

Done
