### ISSUE TITLE
Mapview usage issue : Error in if (!is.na(getProjection(lst[[i]]))) { :  l'argument est de longueur nulle

### ISSUE THREAD

**Issue by alain-onf** [r-spatial/mapview#277]
Hello,
I am trying to use the mapview package to plot 2 sf feature
For example my code is:
```
library(mapview)
mapview(franconia) + mapview(breweries)
```
The result returns the error:
```
Error in if (!is.na(getProjection(lst[[i]]))) { : 
  l'argument est de longueur nulle
```
This code worked a few weeks ago, before the update of "sf" (v0.8-0 -> v0.9-0)
Do you have an idea or a solution to solve this problem?
Thank you in advance for your reply

**Comment by edzer** [comment]
Have you updated mapview?

**Comment by alain-onf** [comment]
I'm using R v 3.6.1 in RStudio with mapview v 2.7.0

**Comment by tim-salabim** [comment]
current mapview on CRAN is 2.7.8

**Comment by alain-onf** [comment]
How to do ?
When I do "install.package" in R 3.6 automatically installs version 2.7.0

**Comment by tim-salabim** [comment]
If you're on windows or mac, you may need to wait a few days until the binaries are available for 2.7.8. If you're sure that the required system libraries (GDAL, PROJ, GEOS) are installed correctly on your computer, you can also do

```r
remotes::install_github("r-spatial/mapview@develop")
```

**Comment by alain-onf** [comment]
Thank you
I will wait for the release of v 2.7.8 for windows

**Comment by tim-salabim** [comment]
It should be up now. At least I got the email that it was build for windows

**Comment by alain-onf** [comment]
Thank-you for your prompt response
Now version 2.7.8 is loaded
But there is an installation problem under windows
So i open a new issue
