### ISSUE TITLE
where is coords2Polygons?

### ISSUE THREAD

**Issue by carzamora** [r-spatial/mapview#281]
Hi, 

this package has the coords2Polygons function right? why isn't now? where can I found the function now? 

thanks!

**Comment by fdetsch** [comment]
Hi, 

`coords2Polygons()` and also `coords2Lines()` have been moved to package [**Orcs**](https://CRAN.R-project.org/package=Orcs). Simply run `install.packages("Orcs")` to continue using these functions.

**Comment by tim-salabim** [comment]
Thanks @fdetsch !  I will include these functions in `mapview-defunct` and the `README` to document these changes.

**Comment by RealePrimavera** [comment]
Hello, even after installing package Orcs, it doesn't work.

**Comment by tim-salabim** [comment]
What exactly do you mean with it doesn't work? Can you be a little more specific?

**Comment by RealePrimavera** [comment]
Error: unable to find an inherited method for function ‘coords2Polygons’ for signature ‘"character"

**Comment by tim-salabim** [comment]
Can you post a reproducible example? Your data should either be a numeric matrix or a sp `Polygon` object.

**Comment by RealePrimavera** [comment]
Hello, one of the many trials I ran was like this:
**labpoly <- coords2Polygons(c("X","Y"),data=labeldata3)**

but I also tried to specify this function in other ways and received the same error.

Sample dataset can look like:

**nutsid <- c('AT342','AT335','AT332','AT323','AT322','AT315')
output <- c(15,1,188,85,2,3)
gdp <- c(15688,13665,16227,23170,8397,19686)
X <- c(9.7221,12.0047,11.346,13.2114,12.9093,13.6794)
Y <- c(47.3907,47.3871,47.2034,47.7486,47.3085,47.8468)
labeldata <- data.frame(nutsid,output,gdp,X,Y)**

**Comment by tim-salabim** [comment]
Works for me:

``` r
library(Orcs)
#> Loading required package: raster
#> Loading required package: sp

nutsid <- c('AT342','AT335','AT332','AT323','AT322','AT315')
output <- c(15,1,188,85,2,3)
gdp <- c(15688,13665,16227,23170,8397,19686)
X <- c(9.7221,12.0047,11.346,13.2114,12.9093,13.6794)
Y <- c(47.3907,47.3871,47.2034,47.7486,47.3085,47.8468)
labeldata <- data.frame(nutsid,output,gdp,X,Y)

pls = coords2Polygons(coords = cbind(X, Y), ID = "A")

mapview::mapview(pls)
```

![](https://i.imgur.com/bwMeERy.png)

<sup>Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
