### ISSUE TITLE
Raster legend not updated if specifying manual breaks

### ISSUE THREAD

**Issue by lbusett** [r-spatial/mapview#282]
Hi, 

   on current mapview@develop, the raster legend is apparently not properly updated when manually specifying breaks. For example: 

``` r 
library(raster)
library(mapview)
f <- system.file("external/test.grd", package="raster")
r <- raster(f)
pal <- grDevices::colorRampPalette(RColorBrewer::brewer.pal(5, "RdYlGn"))
mapview(r, col.regions= pal)
```

gives: 

![image](https://user-images.githubusercontent.com/4480397/79328783-e539cd00-7f16-11ea-82e6-f5fae48a7fb1.png)

, but if we manually specify breaks, the map is modified, but the legend is no longer "correct": 

``` r 
brks <- classInt::classIntervals(1:10000,
                                 style = "fixed",
                                 fixedBreaks = seq(0,10000,500),
                                 intervalClosure = "right")
mapview(r, col.regions= pal, at = brks$brks)
```

![image](https://user-images.githubusercontent.com/4480397/79328935-27630e80-7f17-11ea-8d1a-5041881143c4.png)

I may be wrong, but I think previous `mapview` behaviour was different, and the legend followed the specified "breaks". Am I wrong? 

HTH, 

Lorenzo

**Comment by lbusett** [comment]
__UPDATE__

 I tried to see if I was able to "fix" this but without success... sorry. FYI: if it helps, I saw that "old" behaviour can be "restored" easily by uncommenting here. 

https://github.com/r-spatial/mapview/blob/0a3517f764e8e42cebff2bd71013f74e53430fc5/R/raster.R#L164

**Comment by tim-salabim** [comment]
I know, legends are the hill I'm gonna die on... I'll have a look at this on the weekend.

**Comment by lbusett** [comment]
Thanks... and sorry for the bad news. I tried to work on this but failed. 
By the way: I just noticed that also the behaviour you get by reinstating `addRasterLegend` does not appear to be correct, unless you set a small number of breaks (e.g., 10), leading to a "discrete" legend instead of a colourbar.

**Comment by lbusett** [comment]
Oh, sorry: With low number of breaks, also current mapview is ok:

``` r 
f <- system.file("external/test.grd", package="raster")
r <- raster(f)
pal <- grDevices::colorRampPalette(RColorBrewer::brewer.pal(5, "RdYlGn"))
brks <- classInt::classIntervals(1:10000,
                                 style = "fixed",
                                 fixedBreaks = seq(0,10000,1000),
                                 intervalClosure = "right")
mapview(r, col.regions= pal, at = brks$brks)
```

![image](https://user-images.githubusercontent.com/4480397/79474130-5310f200-8006-11ea-9e32-ca5405c70285.png)

**Comment by tim-salabim** [comment]
Sorry for the long silence. I think this is a deliberate choice of mine (though the exact reasons escape me as it is long ago I made the decision). IIRC, I read somewhere that the human brain can perceptually not distinguish meaningfully between more than ~12 shades of a colour. That's why we map to a continuous legend when there are more than 12 (maybe 11) breaks. Also, not restricting this means that the legend can become quite useless if too many breaks are specified (as the bottom of the legend will disappear from the window). 

Therefore, I am a bit reserved about changing this behaviour. After all, mapview is intended for quick views/checks of the data. If someone needs a different legend, they can easily omit it in the mapview call and add it explicitly using `leaflet::addLegend`.

What do you think @lbusett ?

**Comment by lbusett** [comment]
@tim-salabim 

  having a discrete legend when the number of breaks is low and a continuos one when it is high seems fine to me. 

My main concern here was that when specifying a high number of breaks (to get a continuous legend), the legend  is no longer correct: the raster is shown using the correct "colors" based on the breaks, while the legend shows the values we would get if breaks were not set. 
My use-case for that is to be able to specify a legend/palette with fixed range irrespective of a raster "real" values. Maybe there is a easier way to set min-max to achieve this?

**Comment by tim-salabim** [comment]
The above commit should at least partly solve this issue. Not sure if we should limit the breaks to the range of the data or simply go with what the user specifies. Thoughts?

**Comment by lbusett** [comment]
@tim-salabim 

 thanks, Iìll try to check it out tomorrow. In my opinion it would be better to go with what the user specifies (that's what's already happening with the discrete legend, apparently). That would allow for example that we want to use colors to reflect "absolute" values of a variable within a specified range rather than its "relative" variations within the extent. If I am not mistaken ,  limiting the breaks to the range of data would more or less mimic what already happens if breaks are not specified (i.e., first figure in my first post).

**Comment by tim-salabim** [comment]
Ok, I think I now (sort of) understand what's going on... `pal = leaflet::colorNumeric(...)` in conjunction with `leaflet::addLegend(..., pal = ...)` seems to only evaluate the palette until the maximum of the `domain`, hence neglecting all values beyond its max value. Therefore, I opted to always use `leaflet::colorBin` when specifying breaks (at), i.e. remove the distinction between < or > than 12 distinct color values. 

This now gives for your example above:

```r
library(raster)
library(mapview)

f <- system.file("external/test.grd", package="raster")
r <- raster(f)
pal <- grDevices::colorRampPalette(RColorBrewer::brewer.pal(5, "RdYlGn"))
mapview(r, col.regions= pal)

brks <- classInt::classIntervals(1:10000,
                                 style = "fixed",
                                 fixedBreaks = seq(0,10000,500),
                                 intervalClosure = "right")

mapview(r, col.regions= pal, at = brks$brks)
```

![Screenshot from 2020-06-29 21-19-48](https://user-images.githubusercontent.com/2826432/86046906-4ff6a100-ba4e-11ea-9e40-355efda9b65a.png)

which seems correct. 

Let's see what will come up in other use-cases. This whole legend thing really seems to go round and round. Fixing something here, likely means breaking something somewhere else... Sigh. Though, at least I feel it's headed in the right direction.

**Comment by lbusett** [comment]
@tim-salabim 

 Hi, I was finally testing this out, but i have a problem: After updating my "develop" fork , trying to do `devtools::load_all()` yields: 

`Loading mapview
 Error in setMethod("plainView", signature(x = "RasterLayer"), function(x,  : 
  no existing definition for function ‘plainView’ `

Am I doing something wrong? 

Lorenzo

**Comment by tim-salabim** [comment]
I never use `devtools::load_all()`, I just build the package (ctrl + shift + b in RStudio). Never seen this error before

**Comment by lbusett** [comment]
Ok, I'll try again. It's just that i did not want to mess with my currently installed mapview version.

**Comment by lbusett** [comment]
Ok, I managed to have it working (just by loading "plainview" beforehand. 

Now the example with fixed breaks works ok (thanks). However, unfortunately now I a m seeing this if I do not specify the breaks: 

```
library(raster)
library(mapview)
f <- system.file("external/test.grd", package="raster")
r <- raster(f)
mapview(r)
```
![image](https://user-images.githubusercontent.com/4480397/86354260-ff0ec480-bc68-11ea-8927-81017b90e66c.png)


Below, my session info: 

- Session info ------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United Kingdom.1252 
 ctype    English_United Kingdom.1252 
 tz       Europe/Paris                
 date     2020-07-02                  

- Packages ----------------------------------------------------------------------------------------------------------------------
 ! package           * version date       lib source                            
   abind               1.4-5   2016-07-21 [1] CRAN (R 3.6.0)                    
   assertthat          0.2.1   2019-03-21 [1] CRAN (R 3.6.3)                    
   backports           1.1.7   2020-05-13 [1] CRAN (R 3.6.3)                    
   base64enc           0.1-3   2015-07-28 [1] CRAN (R 3.6.0)                    
   brew                1.0-6   2011-04-13 [1] CRAN (R 3.6.0)                    
   callr               3.4.3   2020-03-28 [1] CRAN (R 3.6.3)                    
   class               7.3-17  2020-04-26 [1] CRAN (R 3.6.3)                    
   classInt            0.4-3   2020-04-07 [1] CRAN (R 3.6.3)                    
   cli                 2.0.2   2020-02-28 [1] CRAN (R 3.6.3)                    
   codetools           0.2-16  2018-12-24 [2] CRAN (R 3.6.3)                    
   colorspace          1.4-1   2019-03-18 [1] CRAN (R 3.6.1)                    
   crayon              1.3.4   2017-09-16 [1] CRAN (R 3.6.3)                    
   crosstalk           1.1.0.1 2020-03-13 [1] CRAN (R 3.6.3)                    
   curl                4.3     2019-12-02 [1] CRAN (R 3.6.3)                    
   DBI                 1.1.0   2019-12-15 [1] CRAN (R 3.6.3)                    
   desc                1.2.0   2018-05-01 [1] CRAN (R 3.6.3)                    
   devtools            2.3.0   2020-04-10 [1] CRAN (R 3.6.3)                    
   digest              0.6.25  2020-02-23 [1] CRAN (R 3.6.3)                    
   e1071               1.7-3   2019-11-26 [1] CRAN (R 3.6.3)                    
   ellipsis            0.3.1   2020-05-15 [1] CRAN (R 3.6.3)                    
   fansi               0.4.1   2020-01-08 [1] CRAN (R 3.6.3)                    
   farver              2.0.3   2020-01-16 [1] CRAN (R 3.6.3)                    
   foreach             1.5.0   2020-03-30 [1] CRAN (R 3.6.3)                    
   fs                  1.4.1   2020-04-04 [1] CRAN (R 3.6.3)                    
   gdalUtils           2.0.3.2 2020-02-13 [1] CRAN (R 3.6.3)                    
   gdtools             0.2.2   2020-04-03 [1] CRAN (R 3.6.3)                    
   glue                1.4.1   2020-05-13 [1] CRAN (R 3.6.3)                    
   htmltools           0.4.0   2019-10-04 [1] CRAN (R 3.6.3)                    
   htmlwidgets         1.5.1   2019-10-08 [1] CRAN (R 3.6.3)                    
   iterators           1.0.12  2019-07-26 [1] CRAN (R 3.6.3)                    
   jsonlite            1.6.1   2020-02-02 [1] CRAN (R 3.6.3)                    
   KernSmooth          2.23-17 2020-04-26 [1] CRAN (R 3.6.3)                    
   lattice             0.20-41 2020-04-02 [1] CRAN (R 3.6.3)                    
   leafem              0.1.1   2020-04-05 [1] CRAN (R 3.6.3)                    
   leaflet             2.0.3   2019-11-16 [1] CRAN (R 3.6.3)                    
   leaflet.providers   1.9.0   2019-11-09 [1] CRAN (R 3.6.3)                    
   leafpop             0.0.5   2019-12-09 [1] CRAN (R 3.6.3)                    
   lifecycle           0.2.0   2020-03-06 [1] CRAN (R 3.6.3)                    
   lwgeom              0.2-4   2020-05-20 [1] CRAN (R 3.6.3)                    
   magrittr            1.5     2014-11-22 [1] CRAN (R 3.6.3)                    
 P mapview           * 2.8.1   2020-06-03 [?] Github (r-spatial/mapview@0902f70)
   memoise             1.1.0   2017-04-21 [1] CRAN (R 3.6.3)                    
   munsell             0.5.0   2018-06-12 [1] CRAN (R 3.6.3)                    
   pkgbuild            1.0.8   2020-05-07 [1] CRAN (R 3.6.3)                    
   pkgload             1.1.0   2020-05-29 [1] CRAN (R 3.6.3)                    
   plainview         * 0.1.0   2019-03-22 [1] CRAN (R 3.6.3)                    
   png                 0.1-7   2013-12-03 [1] CRAN (R 3.6.0)                    
   prettyunits         1.1.1   2020-01-24 [1] CRAN (R 3.6.3)                    
   processx            3.4.2   2020-02-09 [1] CRAN (R 3.6.3)                    
   ps                  1.3.3   2020-05-08 [1] CRAN (R 3.6.3)                    
   R.methodsS3         1.8.0   2020-02-14 [1] CRAN (R 3.6.2)                    
   R.oo                1.23.0  2019-11-03 [1] CRAN (R 3.6.2)                    
   R.utils             2.9.2   2019-12-08 [1] CRAN (R 3.6.3)                    
   R6                  2.4.1   2019-11-12 [1] CRAN (R 3.6.3)                    
   raster            * 3.3-9   2020-07-02 [1] Github (rspatial/raster@1d33eb0)  
   RColorBrewer        1.1-2   2014-12-07 [1] CRAN (R 3.6.0)                    
   Rcpp                1.0.4.6 2020-04-09 [1] CRAN (R 3.6.3)                    
   remotes             2.1.1   2020-02-15 [1] CRAN (R 3.6.3)                    
   rgdal               1.5-10  2020-06-09 [1] CRAN (R 3.6.3)                    
   rlang               0.4.6   2020-05-02 [1] CRAN (R 3.6.3)                    
   rprojroot           1.3-2   2018-01-03 [1] CRAN (R 3.6.3)                    
   rstudioapi          0.11    2020-02-07 [1] CRAN (R 3.6.3)                    
   satellite           1.0.2   2019-12-09 [1] CRAN (R 3.6.3)                    
   scales              1.1.1   2020-05-11 [1] CRAN (R 3.6.3)                    
   sessioninfo         1.1.1   2018-11-05 [1] CRAN (R 3.6.3)                    
   sf                  0.9-3   2020-05-04 [1] CRAN (R 3.6.3)                    
   sp                * 1.4-2   2020-05-20 [1] CRAN (R 3.6.3)                    
   stars               0.4-1   2020-04-07 [1] CRAN (R 3.6.3)                    
   svglite             1.2.3   2020-02-07 [1] CRAN (R 3.6.3)                    
   systemfonts         0.2.2   2020-05-14 [1] CRAN (R 3.6.3)                    
   testthat          * 2.3.2   2020-03-02 [1] CRAN (R 3.6.3)                    
   units               0.6-6   2020-03-16 [1] CRAN (R 3.6.3)                    
   usethis             1.6.1   2020-04-29 [1] CRAN (R 3.6.3)                    
   uuid                0.1-4   2020-02-26 [1] CRAN (R 3.6.3)                    
   viridisLite         0.3.0   2018-02-01 [1] CRAN (R 3.6.3)                    
   webshot             0.5.2   2019-11-22 [1] CRAN (R 3.6.3)                    
   withr               2.2.0   2020-04-20 [1] CRAN (R 3.6.3)                    
   yaml                2.2.1   2020-02-01 [1] CRAN (R 3.6.3)

**Comment by tim-salabim** [comment]
I see the same & I know where the issue lies. Just don't know how complicated it is to fix... Hopefully will get to it over the weekend

**Comment by lbusett** [comment]
Ok. Sorry for always reporting problems... ;-)

**Comment by tim-salabim** [comment]
Nah, it's perfect! Someone to keep me in check :-)

**Comment by tim-salabim** [comment]
Can you please retry and see if I'm making process here? Might have broken stuff elsewhere again...

**Comment by lbusett** [comment]
@tim-salabim 

 Tested a bit (not extensively) and seems good to me. It would be nice so be able to get a continuous legend with "custom" min-max, but one can not have everything! I'd guess if I really need it I can always re-classify raster values over the desired range. 

One unrelated thing: I noticed that using mapview over a "proxy" stars object currently fails:

```
f <- system.file("external/test.grd", package="raster")
r <- stars::read_stars(f, proxy = T)
mapview(r)

 Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘mapView’ for signature ‘"stars_proxy"’ 
```

Therefore, also this fails: 

```
r <- raster(f)
r <- stars::st_as_stars(r)
mapview(r)

 Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘mapView’ for signature ‘"stars_proxy"’ 
```

Consider that I fear therefore that mapview will always fail over large stars objects unless "proxy = FALSE" is specified explicitly.

**Comment by tim-salabim** [comment]
Ok, thanks! If you have a good idea how to make legend creation easier and more consistent, I'm all ears. Though I am a bit reluctant to introduce more arguments to mapview. We really need to be cautious about scope-creep.
Can we close this issue and move the proxy to its own issue?

**Comment by lbusett** [comment]
Ok. Closing here, and moving the issue to a new one.

**Comment by lbusett** [comment]
Sorry that I have to reopen this... While working on the "proxy" issue, I noticed that legend over "stars" rasters are apparently not fixed by https://github.com/r-spatial/mapview/commit/da11756b90c8cea5adc3ce3cfbf2f43c19c6ad81

```
library(raster)
library(mapview)
library(stars)
f <- system.file("external/test.grd", package="raster")
r <- stars::read_stars(f, proxy = F)
mapview(r)
```

![image](https://user-images.githubusercontent.com/4480397/86942586-967e8680-c145-11ea-8b1c-ed9f0c3420dc.png)

**Comment by tim-salabim** [comment]
No worries, that fix should be easy (identical to raster).

**Comment by lbusett** [comment]
Thx. I tried to have a look, but got rapidly lost in `at`, `atv`, `atc`  ;-)

**Comment by tim-salabim** [comment]
No worries, my internal documentation definitely needs to be improved. I will have a go at this tonight

**Comment by lbusett** [comment]
ok. By the way: I did not mean to criticize your work! I know well how hard it is to maintain a code base, and yours is definitely more complicated than what I usually do!

**Comment by tim-salabim** [comment]
I did not take your comment as criticism. I really appreciate all your input in the various places!
