### ISSUE TITLE
at least one of the following columns not found

### ISSUE THREAD

**Issue by ctfysh** [r-spatial/mapview#285]
I ran the examples in https://r-spatial.github.io/mapview/articles/articles/mapview_01-basics.html and found errors as follows:

```
mapview(breweries, zcol = c("brewery", "village", "founded"))
ERROR: 
at least one of the following columns: 
brewery, village, founded
not found in x[[i]]
```

I ran the codes both in the MacOS and Windows 10, both results in errors. I could not understand why this happened. Is it a bug?

**Comment by tim-salabim** [comment]
Seems like a bug. I'll have a look later

**Comment by zlehmann** [comment]
I can report having the same issue. Only if you pass in a vector for zcol. Otherwise it works fine.

**Comment by tim-salabim** [comment]
Yeah, I've messed with the `list` method the other day... Will revisit this weekend. 

https://github.com/r-spatial/mapview/issues/287 is related

**Comment by tim-salabim** [comment]
Should work again
