### ISSUE TITLE
mapshot works ...

### ISSUE THREAD

**Issue by under-score** [r-spatial/mapview#286]
but deploying now the html version of a German map comes at an inacceptable size of 20 Mb plus another 500K of javascript stuff. How can this reduced to about 10%? Any option for a minified version of JS sources , dropping all comments, etc.?

**Comment by tim-salabim** [comment]
Not that I know of. The sources are out of our control. You can set `selfcontained = FALSE` to move the js sources to attached scripts rather than including them in the html. That's about all you can do...

**Comment by under-score** [comment]
thank you - good starting point - so I could use library(curl) and reach out to https://javascript-minifier.com/curl

**Comment by tim-salabim** [comment]
I don't think you will have control about minifying the source files, they are dynamically attached from the provided sources of the different libraries (leaflet etc.). Unless you do this manually in the created html

**Comment by under-score** [comment]
the last 2 scripts need to be outsourced as well using `selfcontained = FALSE`

![screen](https://user-images.githubusercontent.com/2796454/80776155-efd4a300-8b61-11ea-96b3-96c0d32345e4.jpg)

**Comment by tim-salabim** [comment]
Sorry, but this is really an issue you need to raise with **htmlwidgets**. `mapshot` simply wraps `htmlwidgets::saveWidget` and that is where you can set `selfcontained = FALSE`. If you'd like that to behave differently, it needs to be solved in **htmlwidgets**.

Closing this issue. If you open a new issue with **htmlwidgets** please link back to this one, so we can follow any developments.
