### ISSUE TITLE
argument burst throwing an error in mapview 2.7.8

### ISSUE THREAD

**Issue by hewag1975** [r-spatial/mapview#287]
Hi TIm,
hope your doing well. Just encountered an issue with the argument burst throwing an error after updating to mapview 2.7.8. Here´s a reprex:
``` r
library("mapview")
library("dplyr")
#> 
#> Attache Paket: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

breweries %>% 
  slice(1:10) %>% 
  mapview(burst = "zipcode")
#> Error in .subset(x, j): ungültiger Indextyp 'list'
```

<sup>Created on 2020-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Can you have a look at this?
Thanks,
Hendrik

**Comment by tim-salabim** [comment]
Should work again
