### ISSUE TITLE
issue 287 seems to persists after  commit e8066778

### ISSUE THREAD

**Issue by FrogBoss74** [r-spatial/mapview#288]
Dear Tim
Thank you for maintaining this very useful package. i also came across issue 287 but could not fix it with last commit. Burst =T or else is still throwing an error. 

```
devtools::install_github("r-spatial/mapview@develop")
```
> Skipping install of 'mapview' from a github remote, the SHA1 (e8066778) has not changed since last install.
>   Use `force = TRUE` to force installation
Error in fetch(key) : 
  lazy-load database 'C:/Users/xxx/Documents/R/win-
library/3.6/mapview/help/mapview.rdb' is corrupt
```
library(dplyr)
library(mapview)
breweries %>% 
+     slice(1:10) %>% 
+     mapview(burst = "zipcode")
```
>Error in .subset(x, j) : invalid subscript type 'list'

______________________
Should work again

_Originally posted by @tim-salabim in https://github.com/r-spatial/mapview/issues/287#issuecomment-622940800_

**Comment by tim-salabim** [comment]
Works for me. I think your re-install from guthub wasn't successful

**Comment by FrogBoss74** [comment]
I think the issue was when I restarted the R session for installing, it reloaded mapview from the .Rdata file which for some reasons messed up the installation. I deleted the .Rdata file, uninstalled mapview and reinstalled from github and this seems to work now. 
Thanks, sorry for taking your time on this.

**Comment by tim-salabim** [comment]
No problem. Glad it works
