### ISSUE TITLE
mapview() with R 4.0.0

### ISSUE THREAD

**Issue by maklaskarlos** [r-spatial/mapview#289]
**devtools::install_github("r-spatial/mapview@develop")** # installing it i got the following error:

WARNING: Rtools is required to build R packages, but the version of Rtools previously installed in C:/rtools40 has been deleted.

Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
Skipping install of 'mapview' from a github remote, the SHA1 (e8066778) has not changed since last install.
  Use `force = TRUE` to force installation

#I force it

These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: sf    (0.9-2 -> 0.9-3) [CRAN]
5: rlang (0.4.5 -> 0.4.6) [CRAN]

Enter one or more numbers, or an empty line to skip updates:

#I select All and get the following error

sf    (0.9-2 -> 0.9-3) [CRAN]
rlang (0.4.5 -> 0.4.6) [CRAN]
Installing 2 packages: sf, rlang
Installing packages into ‘C:/Users/karlo/OneDrive/Documentos/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There are binary versions available but the source versions are later:
      binary source needs_compilation
sf     0.9-2  0.9-3              TRUE
rlang  0.4.5  0.4.6              TRUE

  Binaries will be installed
probando la URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/sf_0.9-2.zip'
Content type 'application/zip' length 39862059 bytes (38.0 MB)
downloaded 38.0 MB

probando la URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/rlang_0.4.5.zip'
Content type 'application/zip' length 1112530 bytes (1.1 MB)
downloaded 1.1 MB

package ‘sf’ successfully unpacked and MD5 sums checked
**Error: Failed to install 'mapview' from GitHub:
  (convertido del aviso) cannot remove prior installation of package ‘sf’**

Can you help me please?

**Comment by daauerbach** [comment]
did you read the linked page? Rtools has been substantially updated and you need the new rtools40 installed and in your PATH

**Comment by maklaskarlos** [comment]
Not worries. I got the new rtools40 installed and also the old one deleted (rtools).

**Comment by daauerbach** [comment]
Glad to hear. I am curious if you or others reading this issue thread are seeing the cryptic blank white/empty viewer that I'm getting. For example, `r breweries %>% slice(1:10) %>% mapview()` appears to run without errors or warnings, but the result isn't the expected map. This seems to be related to Rstudio though, since it works fine in a session from command line. 

mapview 2.8.1
Rstudio 1.3.878

**Comment by a8dx** [comment]
@daauerbach Same situation here, albeit with RStudio 1.2.5042.

**Comment by daauerbach** [comment]
Okay, appreciate hearing that @a8dx 

Assuming we're not the only ones, @tim-salabim, any specific requests/thoughts on how to help troubleshoot this? I _can_ work without mapview, but I'd rather not...  :wink:

**Comment by tim-salabim** [comment]
> I can work without mapview, but I'd rather not... 😉

That's nice to hear, but I think that until the patched version of R 4.0.1 is out you may need to. You can however set `mapviewOptions(viewer.suppress = TRUE)` in the meantime to try and avoid the issue. I am at this stage not sure if it will help (I haven't migrated to R 4.0.0 myslf yet).

The two main threads to follow in case you're intersted in the nitty-gritty details about this are:

https://github.com/rstudio/rstudio/issues/6737

and

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17773

So, there's already a proposed patch for this porblem in R itself. From a **mapview** point of view, we can only wait and hope it will be resolved soon.

**Comment by daauerbach** [comment]
Thanks to the pointer to the main rstudio thread, lots of helpful info there. Good to see the underlying issue(s) look resolvable/resolved with forthcoming patches.

The mapview package is as awesome as ever!

**Comment by tim-salabim** [comment]
> [edit] appears fixed in current Rstudio preview release: v1.3.957

Good to know!
