### ISSUE TITLE
compatibility with sf 0.9

### ISSUE THREAD

**Issue by ervanSTRI** [r-spatial/mapview#291]
Hi Tim,

Have you found a way to make mapview compatible with the sf projection??
Thanks
E

**Comment by tim-salabim** [comment]
Can you be more explicit as to what you think is not working?

**Comment by ervanSTRI** [comment]
Sorry, a bit too focused. I was refering to [this issue](https://github.com/r- spatial/mapview/issues/271#issue-585168854). 
I have recently updated R (4.0) and the sf package (v.0.9), and nothing happens when I plot sf objects through mapview...
Might be a totally different issue, but I am just starting to dig into this. Thanks for any suggestion.
Cheers

**Comment by tim-salabim** [comment]
You mean the viewer is empty/white (assuming you are using RStudio)?

If so, it is a big in RStudio and is fixed in recent preview versions

**Comment by ervanSTRI** [comment]
Indeed, I have a wite/empty viewer in RStudio (and in Chrome)...
Will check my RStudio version. Thanks
