### ISSUE TITLE
Mapview function won't work in R 4.0.0

### ISSUE THREAD

**Issue by nexusal** [r-spatial/mapview#292]
After updating  R from 3.6.3 ( did pretty well in this version )  to 4.0.0 ,  cpu utilization almost reach to 100% when run this function, even with the franconia data still didn't work (return blank window)  , is this a common problem?

**Comment by tim-salabim** [comment]
You're likely experiencing an RStudio issue, see https://github.com/rstudio/rstudio/issues/6737

Upgrading RStudio to the latest preview version should solve your issue

**Comment by MartinBeal** [comment]
Downloading the latest preview version of Rstudio solved the high CPU usage issue, but now I am getting what I believe is this [https://github.com/rstudio/rstudio/issues/6893](https://github.com/rstudio/rstudio/issues/6893) issue, where the mapview() function runs, showing no error, but nothing appears in the viewer panel. 

Is there a known solution to this issue?

**Comment by tim-salabim** [comment]
Ok, this is not a mapview issue, so there's little we can do btu wait for it to be fixed. In the meantime you can set `mapviewOptions(viewer.suppress = FALSE)` which should tell mapview to always open in the browser rather than the RStudio viewer pane.
