### ISSUE TITLE
Cannot install mapview version 2.7.8

### ISSUE THREAD

**Issue by alliesaizan** [r-spatial/mapview#295]
Hi there,

I am trying to install mapview, but no matter which way I install it (via install.packages, from source, or using devtools), I keep getting an error from R. I am running R 4.0.0 on a Windows machine and my session info is below:

![image](https://user-images.githubusercontent.com/15962391/83568007-80e7c280-a4f0-11ea-8f5a-65335564b8b0.png)

The messages I am getting during install are below. Ultimately, the install errors out with "Error in installed packages: cannot open the connection".

![image](https://user-images.githubusercontent.com/15962391/83568039-90ffa200-a4f0-11ea-9463-622a4c664361.png)

Can anyone please assist with this issue?

**Comment by tim-salabim** [comment]
You seem to have a problem with your internet connection. As shown in the message, the package has a size of 2.3 MB but you only downloaded a fraction of that 732 KB.

**Comment by zac-garland** [comment]
fwiw I run into the same issue mentioned above, but have no problem installing other packages

**Comment by tim-salabim** [comment]
What's the os? And what's the CRAN mirror you're using?

**Comment by zac-garland** [comment]
```
sessionInfo()
#> R version 3.5.2 (2018-12-20)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17763)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base   
```


```
install.packages("mapview",repos = "https://cloud.r-project.org/")
install.packages("mapview",repos = "http://cran.r-project.org")
```

**Comment by alliesaizan** [comment]
I ended up downloading the zip file and installing from source, and that worked for me.
