### ISSUE TITLE
zcol + burst on Windows

### ISSUE THREAD

**Issue by vmoprojs** [r-spatial/mapview#296]
Hi, I am trying to run the following:
`mapview(breweries,zcol = 'number.of.types',burst = TRUE)`
And I get this error: 
`Error in .subset(x, j) : invalid subscript type 'list'`
I tried the code on macOS and it works fine, but it does not on Windows. Any advice?

**Comment by tim-salabim** [comment]
Can you please try to install mapview from github 

```r
remotes::install_github("r-spatial/mapview@develop")
```
I think it is fixed there

**Comment by vmoprojs** [comment]
You're right, thanks!
