### ISSUE TITLE
polar projection

### ISSUE THREAD

**Issue by elgabbas** [r-spatial/mapview#298]
Hello,

I am planning to dynamically plot multiple `sf` objects using `mapview`  within a `shiny` app. 
The data used in the current project is on the Southern Ocean, projected at South Pole Lambert Azimuthal Equal Area projection `ESPG:102020`.

I have trouble overlaying the layers using `mapview`. The layers are on the same projection and plotted nicely using `sf` package.

```
require(mapview); require(sf); require(leaflet)
#Loading data 
load(url("https://github.com/elgabbas/Misc/blob/master/Data.RData?raw=true"))
plot(SFPoly1)
plot(SFPoly2, add = T)
plot(SFPoint, add = T, pch = 20, col="blue")
```
![1](https://user-images.githubusercontent.com/7375051/84211741-567fa180-aabc-11ea-81ea-6ec52657afce.jpg)

When I use `mapview`, each of the objects is plotted nicely in isolation. 
```
mapView(SFPoly1, native.crs = T)
mapView(SFPoly2, native.crs = T)
mapView(SFPoint, native.crs = T)
```
![2](https://user-images.githubusercontent.com/7375051/84211798-7ca54180-aabc-11ea-8542-ba057d549478.jpg) ![3](https://user-images.githubusercontent.com/7375051/84211834-947cc580-aabc-11ea-9eb9-d589b97c3f56.jpg) ![4](https://user-images.githubusercontent.com/7375051/84211841-9a72a680-aabc-11ea-9970-b6ef74b5747b.jpg)

But when I combine them in one plot., I was unable to view them unless I clicked on any of the layer names to zoom to it. The default zoom `zoom full` seems to be restricted to the boundaries of `c(-180,180,-90,90)`, not the actual boundaries of the data used.
```
mapView(SFPoly1, native.crs = T) +
  mapView(SFPoly2, native.crs = T) + 
  mapView(SFPoint, native.crs = T) 
```
![5](https://user-images.githubusercontent.com/7375051/84211895-be35ec80-aabc-11ea-86bc-96f2d06563a7.jpg)
Is it possible to automatically recognize the boundary range based on the combined extent of the data? or to provide this information manually (similar to `xlim` and `ylim` arguments of base R plot function).
</br></br>

I have another question regarding available `map.types`: does `mapview` supports base maps for poles, particularly the Southern Pole? 
I found the following code online to show the Antarctic_Imagery from `ArcGIS` and it seems to work for `leaflet`, but I was not able to add my objects to it. 
Is there any alternative solution using the `mapview` routine?
```
require(leaflet.esri)
leaflet() %>% 
  leaflet.esri::addEsriTiledMapLayer(
    "https://services.arcgisonline.com/arcgis/rest/services/Polar/Antarctic_Imagery/MapServer"
  ) %>% 
  setView(20, -20, 3)
```
![6](https://user-images.githubusercontent.com/7375051/84212068-21278380-aabd-11ea-983c-7f2e67fabe36.jpg)

Cheers,
Ahmed

**Comment by tim-salabim** [comment]
Thanks, should be fixed now. You also need to re-install leafem from github.

Regarding antarctic basemaps, we had the discussion long ago to not support any of this directly as it is beyond the general scope of mapview. That said, you should be able to use a combination of leaflet + leaflet.extras + mapview

**Comment by elgabbas** [comment]
Is it possible to disable zooming out beyond a certain extent when using `native.crs = T`.
In unprojected maps, the maximum zoom out is set to `c(-180,180,-90,90)`, but when using a metric unit without obvious maximum extent user can zoom out indefinitely.
Can I determine the maximum extent based on `bbox` or numeric values?

Cheers,
Ahmed

**Comment by tim-salabim** [comment]
Sorry for the late reply. Currently, this is hard-coded [here](https://github.com/r-spatial/mapview/blob/develop/R/leafletControls.R#L268-L280). Should not be too hard to enable passing of `leafletOptions` to control the map setup. I'll have a stab at this soon.
