### ISSUE TITLE
leaflet.extras2 dependency

### ISSUE THREAD

**Issue by cstepper** [r-spatial/mapview#304]
Hi Tim, 

this sidebyside option is so cool. Just tried to run your example from twitter.
I get the following error:

``` r
library(mapview)
mapviewOptions(fgb = FALSE)
#> Warning: option 'fgb' requires GDAL >= 3.1.0! Your version is 3.0.4. Setting fgb
#> = FALSE

m1 = mapview(franconia, zcol = "district")
m2 = mapview(breweries, cex = "founded", col.regions = "forestgreen")

m1 | m2
#> Loading required namespace: leaflet.extras2
#> Error in addSidebyside(m@map, layerId = "mvSideBySide", rightId = "right", : could not find function "addSidebyside"
```

<sup>Created on 2020-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think this is due to the missing `leaflet.extras2::` in the following line:
https://github.com/r-spatial/mapview/blob/967071e6cc66acd387e981926bf176dfc1eacd36/R/ops.R#L292

When I `library(leaflet.extras2)`, it works like a charm.

Cheers, Christoph

**Comment by tim-salabim** [comment]
Cheers, yeah at the moment I am simply trying to get things to work... Hope to have it generally usable by the end of the week.

**Comment by tim-salabim** [comment]
Closing, as now added
