### ISSUE TITLE
mapview with fgb data not working in shiny - resource path error

### ISSUE THREAD

**Issue by DavZim** [r-spatial/mapview#308]
When using mapview with fgb enabled inside a shiny app, the error `Error in addResourcePath: addResourcePath called with invalid prefix; please see documentation` gets thrown. When disabling fgb or leaving out the colouring argument, the code works fine.

```r
library(shiny)
library(leaflet)
library(mapview)
#> GDAL version >= 3.1.0 | setting mapviewOptions(fgb = TRUE)

# using
# mapviewOptions(fgb = FALSE)
# and the error disappears

ui <- fluidPage(
  leafletOutput("map")
)

server <- function(input, output, session) {
  output$map <- renderLeaflet(
    # when leaving out the zcol argument, the code works!
    mapview(franconia, zcol = "SHAPE_AREA")@map
  )
}

shinyApp(ui, server)
#> Listening on http://127.0.0.1:4374
#> Warning: Error in addResourcePath: addResourcePath called with invalid prefix; please see documentation
#>   [No stack trace available]
```

I think the issue is related to [`leafem`#24](https://github.com/r-spatial/leafem/issues/24).

To my understanding, the fgb functionality writes the polygons to some temporary file, which is not properly included into the shiny path, but I cant find the exact code. Using temporary files in shiny should work without changing the resource path.

**Comment by tim-salabim** [comment]
The layerid, if zcol is present, had spaces that caused shiny to be unhappy. Should be fixed now
