### ISSUE TITLE
Mapview scrambles factor labels?

### ISSUE THREAD

**Issue by pauljargo** [r-spatial/mapview#323]
![mapview_bug_perhaps](https://user-images.githubusercontent.com/70421353/91627377-ed098380-e984-11ea-83c4-2613e702eff8.JPG)

Take a look at the picture. It shows the same map in mapview and ggplot. The factor variable's labels are scrambled in mapview. They seem to be in alphanumeric order (1-9). But the actual categories are in the correct order (from smallest to largest). ggplot gets it right.  I know I could manually override the labels, but this behavior seems problematic. I am just learning R so my apologies if I'm doing something wrong. The code that produced the two maps is:

```r
mapview(tomap, zcol = "bigcat")

ggplot(tomap, aes(fill = factor(bigcat))
       ) +
  geom_sf() +
  scale_fill_brewer("Number of\n3+ Bedroom\nAparments\nFor Rent", 
                    palette = "OrRd") +
  theme(axis.title.x=element_blank(), 
        axis.text.x=element_blank(), 
        axis.ticks.x=element_blank()) +
  theme(axis.title.y=element_blank(), 
        axis.text.y=element_blank(), 
        axis.ticks.y=element_blank())
```
The variable:
```r
str(tomap$bigcat)
 Factor w/ 6 levels "6-19","20-49",..: 3 2 4 2 6 5 6 2 1 3 ...
```

**Comment by tim-salabim** [comment]
Could you provide a reproducible example? E.g. by sharing the data?

**Comment by pauljargo** [comment]
Sure. The code below produces the anomaly. The categories labels in the mapview map are scrambled. But if you hover over the the census tracts, the label displayed in the popup is correct.

Sorry if my code is wonky. I am new to R. 

```r

# reproduce.R
# Problem with scrambled legend in mapview

library(tidycensus)
library(tidyverse)
library(viridis)
library(mapview)

bedrooms <- get_acs(geography = "tract", 
                    state = "LA",
                    county = "Orleans Parish",  table = c("B25042"), 
  output = "wide", geometry = TRUE, 
  year = 2018
  ) 

# delete tracts with no rental units
bedrooms <- subset(bedrooms, B25042_009E > 0)

# delete big empty areas
bedrooms <- subset(bedrooms, str_count(NAME, " 6.12,") == 0)
bedrooms <- subset(bedrooms, str_count(NAME, " 17.30,") == 0)
bedrooms <- subset(bedrooms, str_count(NAME, " 17.33,") == 0)
bedrooms <- subset(bedrooms, str_count(NAME, " 17.34,") == 0)

# generate variable to be mapped
tomap <- bedrooms %>% 
  mutate(big = (B25042_013E + B25042_014E + B25042_015E)) %>% 
  mutate(bigcat = 1 + (big>=20) + (big>=50) + 
           (big>=100) + (big>=150) + (big>=200) ) %>% 
  mutate(bigcat = factor(bigcat,
                         labels = c("6-19",
                                    "20-49",
                                    "50-99",
                                    "100-149",
                                    "150-199",
                                    "200 or more")
                         )
         ) %>% 
    select(NAME, geometry, bigcat)

# bigcat (short for categorical version of number of big apartments)
# is the varible I want to map.
table(tomap$bigcat)
str(tomap$bigcat)


# two plots of bigcat
# mapview map scrambles the category labels
mapview(tomap, zcol = "bigcat")

# ggplot keeps the labels attached correctly
ggplot(tomap, aes(fill = factor(bigcat))
       ) +
  geom_sf() +
  scale_fill_brewer("Number of\n3+ Bedroom\nAparments\nFor Rent", 
                    palette = "OrRd") 

# To see the problem, look at the tract on upper right. It is the highest 
# category (200 or more). In the mapview map, that category is labelled 
# 6-19 in the legend. But if you hover over the tract, the correct label 
# is displayed! So it's only the legend where the categories are scrambled.
 
```

**Comment by pauljargo** [comment]
Just wondering if you were able to figure this out.  The code I submitted above should reproduce the problem.

**Comment by tim-salabim** [comment]
Not yet. And I will likely not have time for this before sometime next week.

**Comment by tim-salabim** [comment]
I just tried your example and it requires an API key. I don't consider that to be reproducible. Can you please provide an example that everyone can recreate?

**Comment by edzer** [comment]
I can reproduce this; data attached (zipped .RData file)

[data.zip](https://github.com/r-spatial/mapview/files/5179848/data.zip)

**Comment by tim-salabim** [comment]
The above commit should fix the issue. Hopefully it doesn't break anything else...

**Comment by pauljargo** [comment]
Thanks so much for looking into this! I am new to github, so could you explain what "the above commit should fix the issue" means?

**Comment by tim-salabim** [comment]
If you `remotes::install_github("r-spatial/mapview")` you should get the correct result for your example above.

**Comment by pauljargo** [comment]
It worked! Thanks again.
