### ISSUE TITLE
Changing date format in legend. Issue with years displaying as 2,020 instead of 2020.

### ISSUE THREAD

**Issue by aleszu** [r-spatial/mapview#326]
Wondering if anyone has a solution to formatting dates in the legend? Bonus points if someone can tell me how to drop the NA from the legend. Thanks!

<img width="148" alt="legend-years-issue" src="https://user-images.githubusercontent.com/6544861/92122582-9b6c5900-edc9-11ea-812a-7a5540b86e45.png">

**Comment by tim-salabim** [comment]
Formatting should be possible by passing a `labFormat` argument. https://github.com/r-spatial/mapview/issues/270#issuecomment-650589300

See `?leaflet::addLegend` for details.

**Comment by tim-salabim** [comment]
@aleszu can we close this?

**Comment by aleszu** [comment]
> @aleszu can we close this?

Thanks! Here's the map [in the wild](https://undark.org/2020/09/16/nicaragua-deforestation/).

**Comment by tim-salabim** [comment]
Wow! Great article! Though a very sad topic. Hopefully we will eventually change as a human race...
