### ISSUE TITLE
colors warning when length(at) == lenth(col.regions)

### ISSUE THREAD

**Issue by dpprdan** [r-spatial/mapview#327]
When I specify both `zcol` and `at` together with a `col.regions` vector, the same length as the `at` vector, I get a warning message:

    library(mapview)
    yrs <- seq(1400, 2200, 200)
    clrs <- mapviewGetOption("vector.palette")(length(yrs))
    identical(length(yrs), length(clrs))
    #> [1] TRUE
    mapview(breweries, zcol = "founded", at = yrs, legend = TRUE, col.regions = clrs)
    #> Warning: Found less unique colors (5) than unique zcol values (64)! 
    #> Interpolating color vector to match number of zcol values.

![](https://i.imgur.com/x6wqUIy.png)

IIUC `length(at) == length(col.regions)` should suffice, though, since no additional colours are used? In other words, I don't think that 64 unique colour values are required here. Therefore I think this warning is a bug. Or am I missing something important?
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> - Session info ---------------------------------------------------------------
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       Windows 10 x64              
    #>  system   x86_64, mingw32             
    #>  ui       RTerm                       
    #>  language en                          
    #>  collate  German_Germany.1252         
    #>  ctype    German_Germany.1252         
    #>  tz       Europe/Berlin               
    #>  date     2020-09-09                  
    #> 
    #> - Packages -------------------------------------------------------------------
    #>  package           * version    date       lib
    #>  assertthat          0.2.1      2019-03-21 [1]
    #>  backports           1.1.9      2020-08-24 [1]
    #>  base64enc           0.1-3      2015-07-28 [1]
    #>  brew                1.0-6      2011-04-13 [1]
    #>  callr               3.4.4      2020-09-07 [1]
    #>  class               7.3-17     2020-04-26 [2]
    #>  classInt            0.4-3      2020-04-07 [1]
    #>  cli                 2.0.2      2020-02-28 [1]
    #>  codetools           0.2-16     2018-12-24 [1]
    #>  colorspace          1.4-1      2019-03-18 [1]
    #>  cpp11               0.2.1      2020-08-11 [1]
    #>  crayon              1.3.4      2017-09-16 [1]
    #>  crosstalk           1.1.0.1    2020-03-13 [1]
    #>  curl                4.3        2019-12-02 [1]
    #>  DBI                 1.1.0      2019-12-15 [1]
    #>  desc                1.2.0      2018-05-01 [1]
    #>  devtools            2.3.1      2020-07-21 [1]
    #>  digest              0.6.25     2020-02-23 [1]
    #>  dplyr               1.0.2      2020-08-18 [1]
    #>  e1071               1.7-3      2019-11-26 [1]
    #>  ellipsis            0.3.1      2020-05-15 [1]
    #>  evaluate            0.14       2019-05-28 [1]
    #>  fansi               0.4.1      2020-01-08 [1]
    #>  farver              2.0.3      2020-01-16 [1]
    #>  fs                  1.5.0      2020-07-31 [1]
    #>  gdtools             0.2.2      2020-04-03 [1]
    #>  generics            0.0.2      2018-11-29 [1]
    #>  glue                1.4.2      2020-08-27 [1]
    #>  highr               0.8        2019-03-20 [1]
    #>  htmltools           0.5.0      2020-06-16 [1]
    #>  htmlwidgets         1.5.1      2019-10-08 [1]
    #>  httr                1.4.2      2020-07-20 [1]
    #>  jsonlite            1.7.1      2020-09-07 [1]
    #>  KernSmooth          2.23-17    2020-04-26 [2]
    #>  knitr               1.29       2020-06-23 [1]
    #>  lattice             0.20-41    2020-04-02 [1]
    #>  leafem              0.1.3      2020-07-26 [1]
    #>  leaflet             2.0.3      2019-11-16 [1]
    #>  leaflet.providers   1.9.0      2019-11-09 [1]
    #>  leafpop             0.0.5      2019-12-09 [1]
    #>  lifecycle           0.2.0      2020-03-06 [1]
    #>  magrittr            1.5.0.9000 2020-08-31 [1]
    #>  mapview           * 2.9.3      2020-09-08 [1]
    #>  memoise             1.1.0      2017-04-21 [1]
    #>  mime                0.9        2020-02-04 [1]
    #>  munsell             0.5.0      2018-06-12 [1]
    #>  pillar              1.4.6      2020-07-10 [1]
    #>  pkgbuild            1.1.0      2020-07-13 [1]
    #>  pkgconfig           2.0.3      2019-09-22 [1]
    #>  pkgload             1.1.0      2020-05-29 [1]
    #>  png                 0.1-7      2013-12-03 [1]
    #>  prettyunits         1.1.1      2020-01-24 [1]
    #>  processx            3.4.4      2020-09-03 [1]
    #>  ps                  1.3.4      2020-08-11 [1]
    #>  purrr               0.3.4      2020-04-17 [1]
    #>  R6                  2.4.1      2019-11-12 [1]
    #>  raster              3.3-13     2020-07-17 [1]
    #>  Rcpp                1.0.5      2020-07-06 [1]
    #>  remotes             2.2.0      2020-07-21 [1]
    #>  rlang               0.4.7      2020-07-09 [1]
    #>  rmarkdown           2.3        2020-06-18 [1]
    #>  rprojroot           1.3-2      2018-01-03 [1]
    #>  satellite           1.0.2      2019-12-09 [1]
    #>  scales              1.1.1      2020-05-11 [1]
    #>  sessioninfo         1.1.1      2018-11-05 [1]
    #>  sf                  0.9-5      2020-07-14 [1]
    #>  sp                  1.4-2      2020-05-20 [1]
    #>  stringi             1.4.6      2020-02-17 [1]
    #>  stringr             1.4.0      2019-02-10 [1]
    #>  svglite             1.2.3.2    2020-07-07 [1]
    #>  systemfonts         0.3.1      2020-09-08 [1]
    #>  testthat            2.3.2      2020-03-02 [1]
    #>  tibble              3.0.3      2020-07-10 [1]
    #>  tidyselect          1.1.0      2020-05-11 [1]
    #>  units               0.6-7      2020-06-13 [1]
    #>  usethis             1.6.1      2020-04-29 [1]
    #>  uuid                0.1-4      2020-02-26 [1]
    #>  vctrs               0.3.4      2020-08-29 [1]
    #>  webshot             0.5.2      2019-11-22 [1]
    #>  withr               2.2.0      2020-04-20 [1]
    #>  xfun                0.16       2020-07-24 [1]
    #>  xml2                1.3.2      2020-04-23 [1]
    #>  yaml                2.2.1      2020-02-01 [1]
    #>  source                             
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  Github (tidyverse/magrittr@15f6f07)
    #>  Github (r-spatial/mapview@3b0810b) 
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #> 
    #> [1] C:/Users/daniel/Documents/.R/win-library
    #> [2] C:/Program Files/R/R-4.0.2/library

</details>

**Comment by dpprdan** [comment]
I get the same warning, when `zcol` is not binned, i.e. when the colour vector is the same length as there are unique `zcol` values. 

(Also note that the legend is messed up, but that's a different issue, I suppose).

    library(mapview)
    library(tmaptools)
    ln <- length(unique(breweries$number.of.types))
    cl <- mapviewGetOption("vector.palette")(ln)
    length(ln) == length(cl)
    #> [1] FALSE
    mapview(breweries, zcol = "number.of.types", col.regions = cl)
    #> Warning: Found less unique colors (13) than unique zcol values (13)! 
    #> Interpolating color vector to match number of zcol values.

![](https://i.imgur.com/csIf9gC.png)

<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> - Session info ---------------------------------------------------------------
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       Windows 10 x64              
    #>  system   x86_64, mingw32             
    #>  ui       RTerm                       
    #>  language en                          
    #>  collate  German_Germany.1252         
    #>  ctype    German_Germany.1252         
    #>  tz       Europe/Berlin               
    #>  date     2020-09-24                  
    #> 
    #> - Packages -------------------------------------------------------------------
    #>  package           * version    date       lib
    #>  abind               1.4-5      2016-07-21 [1]
    #>  assertthat          0.2.1      2019-03-21 [1]
    #>  backports           1.1.9      2020-08-24 [1]
    #>  base64enc           0.1-3      2015-07-28 [1]
    #>  brew                1.0-6      2011-04-13 [1]
    #>  callr               3.4.4      2020-09-07 [1]
    #>  class               7.3-17     2020-04-26 [2]
    #>  classInt            0.4-3      2020-04-07 [1]
    #>  cli                 2.0.2      2020-02-28 [1]
    #>  codetools           0.2-16     2018-12-24 [1]
    #>  colorspace          1.4-1      2019-03-18 [1]
    #>  cpp11               0.2.1      2020-08-11 [1]
    #>  crayon              1.3.4      2017-09-16 [1]
    #>  crosstalk           1.1.0.1    2020-03-13 [1]
    #>  curl                4.3        2019-12-02 [1]
    #>  DBI                 1.1.0      2019-12-15 [1]
    #>  desc                1.2.0      2018-05-01 [1]
    #>  devtools            2.3.1      2020-07-21 [1]
    #>  dichromat           2.0-0      2013-01-24 [1]
    #>  digest              0.6.25     2020-02-23 [1]
    #>  dplyr               1.0.2      2020-08-18 [1]
    #>  e1071               1.7-3      2019-11-26 [1]
    #>  ellipsis            0.3.1      2020-05-15 [1]
    #>  evaluate            0.14       2019-05-28 [1]
    #>  fansi               0.4.1      2020-01-08 [1]
    #>  farver              2.0.3      2020-01-16 [1]
    #>  fs                  1.5.0      2020-07-31 [1]
    #>  gdtools             0.2.2      2020-04-03 [1]
    #>  generics            0.0.2      2018-11-29 [1]
    #>  glue                1.4.2      2020-08-27 [1]
    #>  highr               0.8        2019-03-20 [1]
    #>  htmltools           0.5.0      2020-06-16 [1]
    #>  htmlwidgets         1.5.1      2019-10-08 [1]
    #>  httr                1.4.2      2020-07-20 [1]
    #>  jsonlite            1.7.1      2020-09-07 [1]
    #>  KernSmooth          2.23-17    2020-04-26 [2]
    #>  knitr               1.29       2020-06-23 [1]
    #>  lattice             0.20-41    2020-04-02 [1]
    #>  leafem              0.1.3      2020-07-26 [1]
    #>  leaflet             2.0.3      2019-11-16 [1]
    #>  leaflet.providers   1.9.0      2019-11-09 [1]
    #>  leafpop             0.0.5      2019-12-09 [1]
    #>  lifecycle           0.2.0      2020-03-06 [1]
    #>  lwgeom              0.2-5      2020-06-12 [1]
    #>  magrittr            1.5.0.9000 2020-08-31 [1]
    #>  mapview           * 2.9.3      2020-09-08 [1]
    #>  memoise             1.1.0      2017-04-21 [1]
    #>  mime                0.9        2020-02-04 [1]
    #>  munsell             0.5.0      2018-06-12 [1]
    #>  pillar              1.4.6      2020-07-10 [1]
    #>  pkgbuild            1.1.0      2020-07-13 [1]
    #>  pkgconfig           2.0.3      2019-09-22 [1]
    #>  pkgload             1.1.0      2020-05-29 [1]
    #>  png                 0.1-7      2013-12-03 [1]
    #>  prettyunits         1.1.1      2020-01-24 [1]
    #>  processx            3.4.4      2020-09-03 [1]
    #>  ps                  1.3.4      2020-08-11 [1]
    #>  purrr               0.3.4      2020-04-17 [1]
    #>  R6                  2.4.1      2019-11-12 [1]
    #>  raster              3.3-13     2020-07-17 [1]
    #>  RColorBrewer        1.1-2      2014-12-07 [1]
    #>  Rcpp                1.0.5      2020-07-06 [1]
    #>  remotes             2.2.0      2020-07-21 [1]
    #>  rlang               0.4.7      2020-07-09 [1]
    #>  rmarkdown           2.3        2020-06-18 [1]
    #>  rprojroot           1.3-2      2018-01-03 [1]
    #>  satellite           1.0.2      2019-12-09 [1]
    #>  scales              1.1.1      2020-05-11 [1]
    #>  sessioninfo         1.1.1      2018-11-05 [1]
    #>  sf                  0.9-6      2020-09-13 [1]
    #>  sp                  1.4-2      2020-05-20 [1]
    #>  stars               0.4-3      2020-07-08 [1]
    #>  stringi             1.5.3      2020-09-09 [1]
    #>  stringr             1.4.0      2019-02-10 [1]
    #>  svglite             1.2.3.2    2020-07-07 [1]
    #>  systemfonts         0.3.1      2020-09-08 [1]
    #>  testthat            2.3.2      2020-03-02 [1]
    #>  tibble              3.0.3      2020-07-10 [1]
    #>  tidyselect          1.1.0      2020-05-11 [1]
    #>  tmaptools         * 3.1        2020-07-01 [1]
    #>  units               0.6-7      2020-06-13 [1]
    #>  usethis             1.6.1      2020-04-29 [1]
    #>  uuid                0.1-4      2020-02-26 [1]
    #>  vctrs               0.3.4      2020-08-29 [1]
    #>  viridisLite         0.3.0      2018-02-01 [1]
    #>  webshot             0.5.2      2019-11-22 [1]
    #>  withr               2.2.0      2020-04-20 [1]
    #>  xfun                0.17       2020-09-09 [1]
    #>  XML                 3.99-0.5   2020-07-23 [1]
    #>  xml2                1.3.2      2020-04-23 [1]
    #>  yaml                2.2.1      2020-02-01 [1]
    #>  source                             
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  Github (tidyverse/magrittr@15f6f07)
    #>  Github (r-spatial/mapview@3b0810b) 
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.2)                     
    #>  CRAN (R 4.0.0)                     
    #> 
    #> [1] C:/Users/daniel/Documents/.R/win-library
    #> [2] C:/Program Files/R/R-4.0.2/library

</details>

**Comment by tim-salabim** [comment]
Sorry for the late reply! I think the above commit should solve your issue(s) (including the scrambled color legend).

**Comment by dpprdan** [comment]
Perfect, thanks! 🎉
