### ISSUE TITLE
html_dependency error when knitting .Rmd with mapview() 

### ISSUE THREAD

**Issue by kstierhoff** [r-spatial/mapview#330]
Hi,
I recently ran into the following error when knitting a previously working .Rmd file that included mapview():

> Error: path for html_dependency not found: 

The code chunk below should reproduce the error. I'm running R v4.0.2 and mapview v2.9.0.

Thanks!

```
---
title: "mapview() debug"
author: "author"
date: "9/14/2020"
output: html_document
---
```

```{r setup, include=FALSE}
library(sf)
library(mapview)

nc <- st_read(system.file("shape/nc.shp", package="sf"))
mapview::mapview(nc)
```

**Comment by tim-salabim** [comment]
Thanks, see https://github.com/r-spatial/mapview/issues/312

I hope I can resubmit the fix to CRAN soon, but I want to update **leafpop** first to get the standard popup styles for mapview back.

**Comment by kstierhoff** [comment]
Thanks Tim, I had scanned the other issues but somehow missed it. Thanks
for the support. Great packages!
