### ISSUE TITLE
setting number of query digits doesn't work on RasterBrick 

### ISSUE THREAD

**Issue by laurens-put** [r-spatial/mapview#334]
I have mapviewOptions(query.digits = 3)
This works when creating a map from a RasterLayer, but not with a RasterBrick.

Looks like the map object doens't get the mapviewOptions setting. 

> r1 <- raster(nrows=108, ncols=21, xmn=0, xmx=10)
> raster::values(r1) <- rnorm(2268, 0, .5)
> Brick <- raster::brick(r1,r1) 
> Brick %>% class()
[1] "RasterBrick"
attr(,"package")
[1] "raster"
> Brickmap <- mapview(Brick)
> Brickmap@map$x$calls[[10]]$args[[4]]
[1] "null"
> Layer <- Brick[[1]]
> Layer %>% class()
[1] "RasterLayer"
attr(,"package")
[1] "raster"
> Layermap <- mapview(Layer)
> Layermap@map$x$calls[[10]]$args[[4]]
[1] 3

**Comment by tim-salabim** [comment]
Thanks, should be fixed now.
