### ISSUE TITLE
`mapview` function example not working

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/mapview#337]
The `mapview` function no lonmger works for me… I tried updating to the development version on GitHub but that didn’t resolve the issue. 

Will appreciate any help, thanks!

``` r
library(mapview)
library(sf)
```

    ## Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

``` r
mapview(breweries)
```

    ## Error in leafpop::popupTable(x, className = "mapview-popup"): unused argument (className = "mapview-popup")

Here is the session info:

``` r
sessionInfo()
```

    ## R version 4.0.2 (2020-06-22)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 18.04.5 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
    ## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets 
    ## [6] methods   base     
    ## 
    ## other attached packages:
    ## [1] sf_0.9-6      mapview_2.9.4
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] tidyselect_1.1.0   xfun_0.17          purrr_0.3.4       
    ##  [4] lattice_0.20-41    colorspace_1.4-1   vctrs_0.3.4       
    ##  [7] htmltools_0.5.0    stats4_4.0.2       yaml_2.2.1        
    ## [10] base64enc_0.1-3    rlang_0.4.7        leafpop_0.0.5     
    ## [13] e1071_1.7-3        pillar_1.4.6       glue_1.4.2        
    ## [16] DBI_1.1.0          gdtools_0.2.2      sp_1.4-2          
    ## [19] uuid_0.1-4         lifecycle_0.2.0    stringr_1.4.0     
    ## [22] munsell_0.5.0      raster_3.3-13      htmlwidgets_1.5.1 
    ## [25] codetools_0.2-16   evaluate_0.14      knitr_1.29        
    ## [28] crosstalk_1.1.0.1  class_7.3-17       leafem_0.1.3      
    ## [31] Rcpp_1.0.5         KernSmooth_2.23-17 scales_1.1.1      
    ## [34] classInt_0.4-3     satellite_1.0.2    cpp11_0.2.1       
    ## [37] leaflet_2.0.3      webshot_0.5.2      systemfonts_0.3.1 
    ## [40] brew_1.0-6         png_0.1-7          digest_0.6.25     
    ## [43] stringi_1.5.3      dplyr_0.8.5        grid_4.0.2        
    ## [46] tools_4.0.2        magrittr_1.5       tibble_3.0.3      
    ## [49] crayon_1.3.4       pkgconfig_2.0.3    ellipsis_0.3.1    
    ## [52] assertthat_0.2.1   rmarkdown_2.3      svglite_1.2.3.2   
    ## [55] R6_2.4.1           units_0.6-7        compiler_4.0.2

**Comment by tim-salabim** [comment]
Sorry for the inconveniences. Should work if you update leafpop.

**Comment by michaeldorman** [comment]
Great, works after updating :-) Thanks for the quick reply and the great package!


``` r
library(mapview)
library(sf)
```

    ## Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

``` r
mapview(breweries)
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/93719386-e7214f80-fb8a-11ea-8579-0096a2b2457c.png)

``` r
sessionInfo()
```

    ## R version 4.0.2 (2020-06-22)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 18.04.5 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
    ## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] sf_0.9-6      mapview_2.9.4
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] tidyselect_1.1.0        xfun_0.17               purrr_0.3.4            
    ##  [4] lattice_0.20-41         leaflet.providers_1.9.0 colorspace_1.4-1       
    ##  [7] vctrs_0.3.4             generics_0.0.2          htmltools_0.5.0        
    ## [10] stats4_4.0.2            yaml_2.2.1              base64enc_0.1-3        
    ## [13] rlang_0.4.7             leafpop_0.0.6           e1071_1.7-3            
    ## [16] pillar_1.4.6            glue_1.4.2              DBI_1.1.0              
    ## [19] gdtools_0.2.2           RColorBrewer_1.1-2      sp_1.4-2               
    ## [22] uuid_0.1-4              lifecycle_0.2.0         stringr_1.4.0          
    ## [25] munsell_0.5.0           raster_3.3-13           htmlwidgets_1.5.1      
    ## [28] codetools_0.2-16        evaluate_0.14           knitr_1.29             
    ## [31] callr_3.4.4             ps_1.3.4                crosstalk_1.1.0.1      
    ## [34] class_7.3-17            leafem_0.1.3            Rcpp_1.0.5             
    ## [37] KernSmooth_2.23-17      scales_1.1.1            classInt_0.4-3         
    ## [40] satellite_1.0.2         cpp11_0.2.1             jsonlite_1.7.1         
    ## [43] leaflet_2.0.3           webshot_0.5.2           systemfonts_0.3.1      
    ## [46] brew_1.0-6              png_0.1-7               digest_0.6.25          
    ## [49] stringi_1.5.3           processx_3.4.4          dplyr_1.0.2            
    ## [52] grid_4.0.2              tools_4.0.2             magrittr_1.5           
    ## [55] tibble_3.0.3            crayon_1.3.4            pkgconfig_2.0.3        
    ## [58] ellipsis_0.3.1          rmarkdown_2.3           svglite_1.2.3.2        
    ## [61] R6_2.4.1                units_0.6-7             compiler_4.0.2
