### ISSUE TITLE
Resampling issue with `mapview` and `stars`

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/mapview#339]
There is a difference between the way that `stars` rasters and the respective `Raster*` rasters are displayed, even though the values and spatial properties are identical. The problem seems to be when displaying `stars`, they are resampled with a higher resolution and consequently the arrangement of values does not match the original raster (compared to the conversion to `Raster*`).

In the following example, a small 6x6 `stars` raster with a particular pattern of `0`s and `1`s is created. When using `mapview` on the `stars` raster, directly, the raster is resampled to a higher resolution and consequently the proportions of the original pattern are lost. When converting to `Raster*`, the image is 6x6 like the original raster and correctly matches the original pattern.

Thank you very much!

``` r
library(mapview)
library(stars)
```

    ## Loading required package: abind

    ## Loading required package: sf

    ## Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

``` r
# Data
x = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
x
```

    ## stars object with 3 dimensions and 1 attribute
    ## attribute(s):
    ##   L7_ETMs.tif    
    ##  Min.   :  1.00  
    ##  1st Qu.: 54.00  
    ##  Median : 69.00  
    ##  Mean   : 68.91  
    ##  3rd Qu.: 86.00  
    ##  Max.   :255.00  
    ## dimension(s):
    ##      from  to  offset delta                       refsys point values x/y
    ## x       1 349  288776  28.5 UTM Zone 25, Southern Hem... FALSE   NULL [x]
    ## y       1 352 9120761 -28.5 UTM Zone 25, Southern Hem... FALSE   NULL [y]
    ## band    1   6      NA    NA                           NA    NA   NULL

``` r
# Subset
x = x[,20:25,20:25,1,drop=TRUE]
x
```

    ## stars object with 2 dimensions and 1 attribute
    ## attribute(s):
    ##   L7_ETMs.tif   
    ##  Min.   :55.00  
    ##  1st Qu.:57.00  
    ##  Median :59.50  
    ##  Mean   :62.47  
    ##  3rd Qu.:63.00  
    ##  Max.   :79.00  
    ## dimension(s):
    ##   from to  offset delta                       refsys point values x/y
    ## x   20 25  288776  28.5 UTM Zone 25, Southern Hem... FALSE   NULL [x]
    ## y   20 25 9120761 -28.5 UTM Zone 25, Southern Hem... FALSE   NULL [y]

``` r
# Pattern
x[[1]][] = 0
x[[1]][3,] = 1
x[[1]][,3] = 1
x[[1]][1,c(T,F)] = 1
x[[1]][c(T,F),1] = 1
plot(x)
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/94345128-7d8ebe80-002c-11eb-8f67-2661a4f1f04a.png)

``` r
# Map - as 'stars'
mapview(x)
```

![Screenshot from 2020-09-26 19-12-45](https://user-images.githubusercontent.com/9386655/94345141-8f706180-002c-11eb-8993-210413058b04.png)

``` r
# Map - as 'raster'
mapview(as(x, "Raster"))
```

![Screenshot from 2020-09-26 19-12-41](https://user-images.githubusercontent.com/9386655/94345147-95664280-002c-11eb-8a76-1e8e8bbab6a9.png)

Session info:

``` r
sessionInfo()
```

    ## R version 4.0.2 (2020-06-22)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 18.04.5 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
    ## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] stars_0.4-4   sf_0.9-6      abind_1.4-5   mapview_2.9.4
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] tidyselect_1.1.0        xfun_0.17               purrr_0.3.4            
    ##  [4] lattice_0.20-41         colorspace_1.4-1        vctrs_0.3.4            
    ##  [7] generics_0.0.2          leaflet.providers_1.9.0 htmltools_0.5.0        
    ## [10] stats4_4.0.2            yaml_2.2.1              base64enc_0.1-3        
    ## [13] rlang_0.4.7             e1071_1.7-3             pillar_1.4.6           
    ## [16] glue_1.4.2              DBI_1.1.0               sp_1.4-2               
    ## [19] lifecycle_0.2.0         stringr_1.4.0           munsell_0.5.0          
    ## [22] raster_3.3-13           htmlwidgets_1.5.1       codetools_0.2-16       
    ## [25] evaluate_0.14           knitr_1.29              callr_3.4.4            
    ## [28] ps_1.3.4                crosstalk_1.1.0.1       parallel_4.0.2         
    ## [31] class_7.3-17            leafem_0.1.3            Rcpp_1.0.5             
    ## [34] KernSmooth_2.23-17      scales_1.1.1            classInt_0.4-3         
    ## [37] satellite_1.0.2         lwgeom_0.2-5            jsonlite_1.7.1         
    ## [40] leaflet_2.0.3           webshot_0.5.2           farver_2.0.3           
    ## [43] png_0.1-7               digest_0.6.25           stringi_1.5.3          
    ## [46] processx_3.4.4          dplyr_1.0.2             grid_4.0.2             
    ## [49] rgdal_1.5-16            tools_4.0.2             magrittr_1.5           
    ## [52] tibble_3.0.3            crayon_1.3.4            pkgconfig_2.0.3        
    ## [55] ellipsis_0.3.1          rmarkdown_2.3           R6_2.4.1               
    ## [58] units_0.6-7             compiler_4.0.2

**Comment by tim-salabim** [comment]
Very interesting! Thanks for the great example! If you zoom out enough, things align correctly at some stage.
This is a result of the javascript library we now use for stars objects: https://github.com/GeoTIFF/georaster-layer-for-leaflet

This is a nice approach for large raster data, but apparently not ideal for small data sets. Not sure right now, what the best behaviour should be. Only use this new approach for data larger than some threshold? 

Pinging @DanielJDufour as this would best be addressed in the updtream JS lib. Could this be handled in georaster-layer-for-leaflet? It generally seems a little overkill to resample things that only have a few pixels. Of course the question is what a good threshold would be?

**Comment by michaeldorman** [comment]
Interesting! Thanks for the details about the underlying library. I now see that when displaying `Raster*` with `mapview` the raster appears as a fixed image, however, when displaying `stars`, the raster is transformed to tile collections, and at each zoom level the arrangement of pixels is slightly different. 

The `stars` method seems to introduce artefacts in large images too. For example when keeping the original size of image `x` (above) and just "drawing" a vertical line, the line appears duplicated and discontinuous in the `stars` approach:

```{r}
library(mapview)
library(stars)

# Data
x = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
x

# Subset
x = x[,,,1,drop=TRUE]                                    

# Pattern
x[[1]][100,] = 1

# Map - as 'stars'
mapview(x)

# Map - as 'raster'
mapview(as(x, "Raster"))
```

Map with `Raster*`:

![Screenshot from 2020-09-26 21-08-29](https://user-images.githubusercontent.com/9386655/94347400-78397000-003c-11eb-8039-c53825bd13d6.png)


Map with `stars`:

![Screenshot from 2020-09-26 21-09-08](https://user-images.githubusercontent.com/9386655/94347411-9901c580-003c-11eb-977c-2f3eecd3f218.png)

![Screenshot from 2020-09-26 21-09-23](https://user-images.githubusercontent.com/9386655/94347417-a7e87800-003c-11eb-9d9a-bd25c5972297.png)

Without knowing anything about the implementation details... Maybe this is just the result of using nearest-neighbor resampling (in `stars`) as opposed to an interpolation (in `Raster*`)? In any case, for small rasters the `Raster*` approach seems preferable to me... In fact the `stars` approach works slower and less smooth for me in the 350x350 example, although I imagine it can make it possible to display really large rasters, which is definitely an advantage! Perhaps there can be an option for the user to choose between methods? :-)

**Comment by tim-salabim** [comment]
I agree, we should make this an option (similar to `fgb`). This is early days in the dev of this method, so your feedback is much appreciated!

**Comment by michaeldorman** [comment]
Great, thank you very much!

**Comment by tim-salabim** [comment]
@michaeldorman the above commit now has a new `georaster` option for `mapviewOptions()`. Default is `FALSE` so standard `leaflet::addRasterImage` is used. If set to `TRUE` we use `leafem::addGeoRaster`. I think this makes more sense and when the `addGeoRaster` method is mature enough we can easily flip the switch to `TRUE` as the default option. 

Closing here, feel free to reopen.

**Comment by michaeldorman** [comment]
This is great, thank you very much @tim-salabim !

Works for me:

``` r
library(mapview)
library(stars)

# Data
x = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
x
```

    ## stars object with 3 dimensions and 1 attribute
    ## attribute(s):
    ##   L7_ETMs.tif    
    ##  Min.   :  1.00  
    ##  1st Qu.: 54.00  
    ##  Median : 69.00  
    ##  Mean   : 68.91  
    ##  3rd Qu.: 86.00  
    ##  Max.   :255.00  
    ## dimension(s):
    ##      from  to  offset delta                       refsys
    ## x       1 349  288776  28.5 UTM Zone 25, Southern Hem...
    ## y       1 352 9120761 -28.5 UTM Zone 25, Southern Hem...
    ## band    1   6      NA    NA                           NA
    ##      point values x/y
    ## x    FALSE   NULL [x]
    ## y    FALSE   NULL [y]
    ## band    NA   NULL

``` r
# Subset
x = x[,,,1,drop=TRUE]                                    

# Pattern
x[[1]][100,] = 1

# Map - method 1
mapviewOptions(georaster = FALSE)  ## Default
mapview(x)
```
![Screenshot from 2020-09-28 12-38-25](https://user-images.githubusercontent.com/9386655/94416548-a9728700-0187-11eb-920c-db890253dd1b.png)

``` r
# Map - method 2
mapviewOptions(georaster = TRUE)
mapview(x)
```

![Screenshot from 2020-09-28 12-38-23](https://user-images.githubusercontent.com/9386655/94416563-ad060e00-0187-11eb-954d-ba92b0987951.png)

Session info:

``` r
sessionInfo()
```

    ## R version 4.0.2 (2020-06-22)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 18.04.5 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
    ## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets 
    ## [6] methods   base     
    ## 
    ## other attached packages:
    ## [1] stars_0.4-4   sf_0.9-6      abind_1.4-5   mapview_2.9.4
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] tidyselect_1.1.0        xfun_0.17              
    ##  [3] purrr_0.3.4             lattice_0.20-41        
    ##  [5] colorspace_1.4-1        vctrs_0.3.4            
    ##  [7] generics_0.0.2          leaflet.providers_1.9.0
    ##  [9] htmltools_0.5.0         stats4_4.0.2           
    ## [11] yaml_2.2.1              base64enc_0.1-3        
    ## [13] rlang_0.4.7             e1071_1.7-3            
    ## [15] pillar_1.4.6            later_1.1.0.1          
    ## [17] glue_1.4.2              DBI_1.1.0              
    ## [19] sp_1.4-2                lifecycle_0.2.0        
    ## [21] stringr_1.4.0           munsell_0.5.0          
    ## [23] raster_3.3-13           htmlwidgets_1.5.1      
    ## [25] codetools_0.2-16        evaluate_0.14          
    ## [27] knitr_1.29              callr_3.4.4            
    ## [29] ps_1.3.4                httpuv_1.5.4           
    ## [31] crosstalk_1.1.0.1       parallel_4.0.2         
    ## [33] class_7.3-17            leafem_0.1.3           
    ## [35] Rcpp_1.0.5              KernSmooth_2.23-17     
    ## [37] scales_1.1.1            promises_1.1.1         
    ## [39] classInt_0.4-3          satellite_1.0.2        
    ## [41] lwgeom_0.2-5            leaflet_2.0.3          
    ## [43] webshot_0.5.2           jsonlite_1.7.1         
    ## [45] farver_2.0.3            servr_0.18             
    ## [47] png_0.1-7               digest_0.6.25          
    ## [49] stringi_1.5.3           processx_3.4.4         
    ## [51] dplyr_1.0.2             grid_4.0.2             
    ## [53] tools_4.0.2             magrittr_1.5           
    ## [55] tibble_3.0.3            crayon_1.3.4           
    ## [57] pkgconfig_2.0.3         ellipsis_0.3.1         
    ## [59] rmarkdown_2.3           rstudioapi_0.11        
    ## [61] R6_2.4.1                units_0.6-7            
    ## [63] compiler_4.0.2
