### ISSUE TITLE
Support for "terra" in mapview

### ISSUE THREAD

**Issue by gilbertocamara** [r-spatial/mapview#340]
Dear Tim, 
Given the advantages of the new "terra" package over the "raster" package, would it be possible to include support for "terra" in mapview? 

Thanks
Gilberto

**Comment by tim-salabim** [comment]
Definitely on my to-do-list. But I am currently starting to re-vamp internal raster processing to be based on stars and then simply use their coercion methods for other raster formats (raster, terra). This will, however, likely take a while... For the short term I fear you're stuck with coercing the terra object to raster before calling mapview.

**Comment by gilbertocamara** [comment]
Ok, no problem!

**Comment by fabeit** [comment]
I find the terra package very raw at the moment, especially when handling certain type of files such as ncdf, and also some of the functions really need to be polished or are just missing. I wouldn't prioritize until the package terra is out of beta.

**Comment by gilbertocamara** [comment]
Mileages may vary. I find terra to be a stable package for the basic functions and much faster than raster.

**Comment by fabeit** [comment]
I work with large global rasters with 1000+ layers and it has crashed on me several times, it badly integrates with other packages such as rasterVis, sf, etc. For basic stuff is nice, but once you work with large files it still needs work. I don't know why it was released in this state.

**Comment by kendonB** [comment]
I have just realised my workaround for this is likely to be perfectly acceptable for `mapview`. You just need to convert using `raster::raster()` then apply `mapview()`

**Comment by tim-salabim** [comment]
Closed with https://github.com/r-spatial/mapview/pull/435

**Comment by ejjunju** [comment]
Raster will be deprecated in 2023 according to a message i get when i load it!  has this workaround been implemnted in terra? I cant seem to find a solution in terra that works.

**Comment by ejjunju** [comment]
You are right about the message ( se below) but my assumption is that if the packages underpinning the package will be retired then the package itself may not work properly or may not be available?
```
> library(raster)
Loading required package: sp
The legacy packages maptools, rgdal, and rgeos, underpinning this package
will retire shortly. Please refer to R-spatial evolution reports on
https://r-spatial.org/r/2023/05/15/evolution4.html for details.
```

**Comment by edzer** [comment]
No, from https://cran.r-project.org/web/packages/raster/index.html you can see that `raster` does not depend in any way on `maptools`, `rgdal` or `rgeos`.
