### ISSUE TITLE
Problem with extendLimits test

### ISSUE THREAD

**Issue by simonbrewer** [r-spatial/mapview#345]
I ran into a problem with using mapview and specifying a variable for the col argument. For example:

```
library(mapview)
franconia$n <- rnorm(nrow(franconia))
mapview(franconia, zcol = "n")

Error in if (all.equal(lim[1], lim[2])) lim = lim * c(0.999, 1.001) : 
  argument is not interpretable as logical
```

I think the issue stems from the use of `all.equal` to test the range limits in the `extendLimits` function. This can't be used directly with `if`. I think this would work instead:

```
if (isTRUE(all.equal(lim[1], lim[2]))) lim = lim * c(0.999, 1.001)
```

For example
```
lim <- c(2, 2)
if (isTRUE(all.equal(lim[1], lim[2]))) lim = lim * c(0.999, 1.001)
print(lim)

[1] 1.998 2.002
```

**Comment by tim-salabim** [comment]
Thanks! This was indeed a hot fix I only introduced lately. Will fix asap.

**Comment by tim-salabim** [comment]
Should be fixed now. For the record, for some reason, the raster from #343 passed into `extendLimits` returns `FALSE` for `lim[1] == lim[2]`, despite the fact that both limits are 1. In any case, thanks for providing a more robust solution!

**Comment by simonbrewer** [comment]
Can confirm this fixed the issue I was having. Thanks for the quick fix!
