### ISSUE TITLE
Mapview ouput is no longer embedded in R Notebook files

### ISSUE THREAD

**Issue by jendrik20** [r-spatial/mapview#351]
Using RStudio and R notebooks, the output of mapview() is no longer embedded in the R notebook files but only send to the viewer. The map doesn't show in the .Rmd after running a code chunk, nor does it show in the .nb.html notebook file produced when saving your R notebook file. 

Maps do show when knitting with Knit to HTML. However, this changes the notebook to a regular rmarkdown file which is not the purpose of the r notebook file. So this is not the same issue as #337 

Mapview outputs were showing in notebook files with mapview 2.7.8. However older versions had other issues (see #312 ) when saving the notebook, which is why I updated. 

Here is an example using the standard header for a R notebook (.Rmd) and following simple code. 

```{r}
---
title: "R Notebook"
output: html_notebook
---
```

```{r}
library(mapview)
```

```{r}
mapview(breweries)
```

Here is mysession info as well. I am on the latest versions of R Rstudio and on mapview 2.9.4 and leafpop 0.0.6.

```{r}
# R version 4.0.3 (2020-10-10)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 19041)
# 
# Matrix products: default
# 
# locale:
#   [1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252
# [3] LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C
# [5] LC_TIME=Dutch_Netherlands.1252
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base
# 
# other attached packages:
#   [1] mapview_2.9.4
# 
# loaded via a namespace (and not attached):
#   [1] tidyselect_1.1.0        xfun_0.19
# [3] purrr_0.3.4             sf_0.9-6
# [5] lattice_0.20-41         colorspace_2.0-0
# [7] vctrs_0.3.4             generics_0.1.0
# [9] leaflet.providers_1.9.0 htmltools_0.5.0
# [11] stats4_4.0.3            yaml_2.2.1
# [13] base64enc_0.1-3         rlang_0.4.8
# [15] leafpop_0.0.6           e1071_1.7-4
# [17] pillar_1.4.6            glue_1.4.2
# [19] DBI_1.1.0               gdtools_0.2.2
# [21] sp_1.4-4                RColorBrewer_1.1-2
# [23] uuid_0.1-4              lifecycle_0.2.0
# [25] stringr_1.4.0           munsell_0.5.0
# [27] raster_3.3-13           htmlwidgets_1.5.2
# [29] codetools_0.2-18        evaluate_0.14
# [31] knitr_1.30              crosstalk_1.1.0.1
# [33] class_7.3-17            leafem_0.1.3
# [35] Rcpp_1.0.5              KernSmooth_2.23-17
# [37] scales_1.1.1            classInt_0.4-3
# [39] satellite_1.0.2         leaflet_2.0.3
# [41] webshot_0.5.2           jsonlite_1.7.1
# [43] systemfonts_0.3.2       brew_1.0-6
# [45] png_0.1-7               digest_0.6.27
# [47] stringi_1.5.3           dplyr_1.0.2
# [49] grid_4.0.3              tools_4.0.3
# [51] magrittr_1.5            tibble_3.0.4
# [53] crayon_1.3.4            pkgconfig_2.0.3
# [55] ellipsis_0.3.1          rmarkdown_2.5
# [57] svglite_1.2.3.2         rstudioapi_0.13
# [59] R6_2.5.0                units_0.6-7
# [61] compiler_4.0.3
```

**Comment by tim-salabim** [comment]
Thanks, can you please give me the output of `sf::extSoftVersion()`?

**Comment by jendrik20** [comment]
Thanks for the fast reply!
Here it is.  I don't know what this means though. 

```
> sf::extSoftVersion()
Error: 'extSoftVersion' is not an exported object from 'namespace:sf'
```

**Comment by tim-salabim** [comment]
Sorry, I meant `sf::sf_extSoftVersion()`

**Comment by jendrik20** [comment]
No problem, here it is
```
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.4"        "6.3.1"         "true"         "true" 
```

**Comment by tim-salabim** [comment]
Ok, so this is more complicated than I had hoped. Not sure when I'll be able to fix it. Hopefully on the weekend, but no promises

**Comment by jendrik20** [comment]
Well, I'm already happy that you'll be looking into it to fix it. So, thanks.

**Comment by tim-salabim** [comment]
@jendrik20 can you please re.try if this is now solved. You need to set options `fgb` and `georaster` to `FALSE` for it to print properly:

```
library(mapview)
mapviewOptions(fgb = FALSE)
mapviewOptions(georaster = FALSE)
mapview(franconia)
```

**Comment by edzer** [comment]
Works for me!

**Comment by jendrik20** [comment]
Hi @tim-salabim ,
Sorry to say, but I haven't got it working just yet. When trying 
```
mapviewOptions(fgb = FALSE, georaster = FALSE)
```
I get 
```
option 'fgb' requires GDAL >= 3.1.0! Your version is 3.0.4. Setting fgb = FALSE
```
rgdal seems to point to gdal 3.0.4. I do have the latest version of rgdal though.

```
library(rgdal)
```
```
Loading required package: sp
rgdal: version: 1.5-18, (SVN revision 1082)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 3.0.4, released 2020/01/28
Path to GDAL shared files: C:/R/packages/rgdal/gdal
GDAL binary built with GEOS: TRUE 
Loaded PROJ runtime: Rel. 6.3.1, February 10th, 2020, [PJ_VERSION: 631]
Path to PROJ shared files: C:/R/packages/rgdal/proj
Linking to sp version:1.4-4
To mute warnings of possible GDAL/OSR exportToProj4() degradation,
use options("rgdal_show_exportToProj4_warnings"="none") before loading rgdal.
```
I updated qgis with the osgeo4w installer (just to be sure to see if that mattered at all), which also includes a version of gdal and which was also on 3.0.4. This updated gdal (for qgis) to 3.1.4. But with library(rgdal) and  sf::sf_extSoftVersion() I still get met the same output as before. 

So I don't know why rgdal points to gdal 3.0.4. I don't know if this version was included with rgdal or one of my other packages or maybe other software, and I don't know how to update it in my R environment. 

I'm trying to see how to make this work. But any help would be appreciated.

**Comment by tim-salabim** [comment]
If you have gdal 3.0.4 then `fgb` will be `FALSE` by default so you only need to set `georaster = FALSE`.

**Comment by edzer** [comment]
It would be good if `fgb = FALSE` would be accepted irrespective the version of GDAL.

**Comment by tim-salabim** [comment]
It is, the above is only a warning.

**Comment by jendrik20** [comment]
@tim-salabim Yes, it works. Many thanks! 

And the  `option 'fgb' requires GDAL >= 3.1.0! Your version is 3.0.4. Setting fgb = FALSE`  is only a warning, not an error. I thought it to be an error which I needed to fix first. So I didn't retry the mapview call... But it turned out that after calling `mapviewOptions(fgb = FALSE, georaster = FALSE)`  calling `mapview(breweries)` in my .rmd works just beautifully again and embeds the map in my notebook (both .rmd and nb.hmtl.  Meaning that `fgb=false` is actually accepted with a warning. @edzer  Sorry about the confusion with this

@tim-salabim Did you perhaps changed the defaults in the source of mapview? If now I create a new notebook and call `mapviewOptions` (after loading mapview), fgb and georaster are allready set to false. Which suits my purpose. 

Really happy with this latest build of mapview as I have no more markdown errors when saving and maps are embedded again. 

Still not sure though how to update gdal for R though. But let's not hijack my own issue here. So, thanks again.

**Comment by tim-salabim** [comment]
For fgb the default depends on the gdal version. The georaster default is FALSE.

**Comment by Sckende** [comment]
It works for me ! Thanks a lot !
