### ISSUE TITLE
`mapview:::is_literally_false` errors when `options("OutDec")` is changed

### ISSUE THREAD

**Issue by eaurele** [r-spatial/mapview#353]
`options("OutDec" = ",")`  causes 
```
> mapview:::is_literally_false(FALSE)
Error: invalid version specification ‘3,5’
```

Suggested fix: replace `3.5` with `"3.5"` in https://github.com/r-spatial/mapview/blob/25326e514b44454c0084b004464033252220f34e/R/mapviewControls.R#L324

**Comment by tim-salabim** [comment]
Nice catch, thanks! Will update soon

**Comment by tim-salabim** [comment]
Should work now.
