### ISSUE TITLE
Multiple mapviews behave strangely in {xaringan} related to markdown 2.6

### ISSUE THREAD

**Issue by charliejhadley** [r-spatial/mapview#364]
This issue is connected to the change in {rmarkdown} 2.6 that required a dev release of {xaringan} as detailed here https://github.com/yihui/xaringan/issues/293.

https://github.com/yihui/xaringan/issues/293 means that {xaringan} won't display htmlwidgets like {mapview} without the dev release. I've installed both the dev release of {xaringan} and the dev release of {mapview} for this feature @tim-salabim added https://github.com/r-spatial/mapview/commit/1d7e42ecfbab52c2d09c9e84c4aeb07f2f90d0f9.

This now results in one of two behaviours:

- using {xaringan} and {mapview} without modification and knitting the document below results in RStudio hanging 

````
---
title: "Presentation Ninja"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library("tidyverse")
library("rnaturalearthdata")
library("sf")
library("mapview")
```

.pull-left[
```{r}
countries110 %>% 
  st_as_sf() %>% 
  mapview()
```
]

.pull-right[
```{r}
quakes %>%
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>%
  mapview()
```
]
````

- adding `mapviewOptions(fgb = TRUE)` means that mapview() elements now share the same data layer (screenshot below code)

````
---
title: "Presentation Ninja"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library("tidyverse")
library("rnaturalearthdata")
library("sf")
library("mapview")
mapviewOptions(fgb = TRUE)
```

.pull-left[
```{r}
countries110 %>% 
  st_as_sf() %>% 
  mapview()
```
]

.pull-right[
```{r}
quakes %>%
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>%
  mapview()
```
]
````

![image](https://user-images.githubusercontent.com/9363263/107791171-84a03a00-6d4b-11eb-8eb9-a63412d503c5.png)

**Comment by tim-salabim** [comment]
````
---
title: "Presentation Ninja"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library("poorman") # for the %>% pipe
library("rnaturalearthdata")
library("sf")
library("mapview")

mapviewOptions(fgb = TRUE)
```

.pull-left[
```{r, message=FALSE}
countries110 %>%
  st_as_sf() %>%
  mapview(layer.name = "countries")
# cntrs = st_as_sf(countries110)
# mapview(cntrs)
```
]

.pull-right[
```{r}
quakes %>%
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>%
  mapview(layer.name = "quakes")
```
]
````

**Comment by tim-salabim** [comment]
I've just updated RStudio to 1.4.1106, still all fine with the first approach. No crash/hang of RStudio

**Comment by charliejhadley** [comment]
@tim-salabim thanks for investigating this and identifying the issue - and a fix with `layer.name`. I've raised an issue over on {xaringan} so that others can solve the problem and the devs can decide if they consider it an issue or not.

I foolishly didn't get enough session information when I was getting the crash/hang behaviour - and I can't get my machine into a position to replicate that behaviour anymore.

I'm closing the issue as I feel it's resolved - thanks!
