### ISSUE TITLE
Mapview doesnt work when summarytools package is installed

### ISSUE THREAD

**Issue by PublicHealthDataGeek** [r-spatial/mapview#365]
Hi

I was wondering if you could offer any advice.  I am a user of mapview.  Today when I started using mapview I couldn't get my maps to appear (they worked a few weeks ago).  After updating R and installing the development version of mapview I managed to discover that the issue appears to be that when I load 'summarytools' package to create nice summaries of my data, that interferes with mapview.  I think it may be because of the following:

```library(summarytools)
Registered S3 method overwritten by 'pryr':
  method      from
  print.bytes Rcpp
For best results, restart R session and update pander using devtools:: or remotes::install_github('rapporter/pander')

Attaching package: ‘summarytools’

The following object is masked from ‘package:tibble’:

    view
```

Is there any advice you could offer?  It hasnt been an issue before when using these packages together.

Many thanks

Caroline

**Comment by tim-salabim** [comment]
Is this in interactive mode or in a markdown or shiny setting?

**Comment by PublicHealthDataGeek** [comment]
Hi Tim

Thanks for the rapid response. It is when I run an R script.  If I run
```library(mapview)
mapview(breweries)
```
it works fine.

if I run
```library(mapview)
library(summarytools)
mapview(breweries)
```
then R basically crashes and I have to kill the program.  

My current plan is just not to load them together but if there is anything else I should or can do that you can advise then that would be great.  
Thanks
Caroline

**Comment by tim-salabim** [comment]
When you say R chrashes, do you mean R itself or RStudio?

**Comment by PublicHealthDataGeek** [comment]
sorry R studio

**Comment by PublicHealthDataGeek** [comment]
Hi Tim
When I rerun the above, it works fine in the R terminal. Presumably that suggests it is an issue with R studio?

**Comment by tim-salabim** [comment]
I would assume so.

**Comment by PublicHealthDataGeek** [comment]
Thank you.  I will close this issue and have a look at R Studio.
