### ISSUE TITLE
[feature request] remove dimnames of geometries

### ISSUE THREAD

**Issue by tim-salabim** [r-spatial/mapview#367]
The below example (thanks to @fdetsch) throws mapview off:

```r
library(osmdata)
library(mapview)
library(poorman)

aoi = opq_osm_id(
  id = 2278487
  , type="relation"
) %>% 
  opq_string() %>% 
  osmdata_sf() %>% 
  poorman::pull(
    "osm_multipolygons"
  )

## encoding
is_char = sapply(
  aoi
  , class
) == "character"

for (i in which(is_char)) {
  Encoding(aoi[[i]]) = "UTF-8"
}

mapview(aoi)
mapview(st_make_valid(aoi))
```
The problem is that the geometriy coordinates have `names`. Consider adding a function to remove these prior to passing to browser.

```r
str(st_geometry(aoi))
sfc_MULTIPOLYGON of length 1; first list element: List of 1
 $ :List of 2
  ..$ 32644341-191114486                              : num [1:86, 1:2] 11.5 11.5 11.5 11.5 11.5 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:86] "262276194" "8202939633" "8202934907" "8202934915" ...
  .. .. ..$ : chr [1:2] "lat" "lon"
  ..$ 171387314-24223166-191114484-191114492-171387322: num [1:92, 1:2] 11.5 11.5 11.5 11.5 11.5 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:92] "95863203" "8231331190" "366945785" "8231331191" ...
  .. .. ..$ : chr [1:2] "lat" "lon"
 - attr(*, "class")= chr [1:3] "XY" "MULTIPOLYGON" "sfg"
```

**Comment by tim-salabim** [comment]
Solved, as long as all geometry parts (sfgs) have names (as we're only checking the first). Note, this is not an issue if `mapviewOptions fgb = TRUE)` as (I assume) the conversion to geojson removes these names in the process.

**Comment by edzer** [comment]
My guess is the conversion to fgb removes them, since simple features don't carry IDs on geometries or geometry parts (see the WKB or WKT definitions). Is this another example of one package trying to fix the damage done by another? I think I commented on this here: https://github.com/ropensci/osmdata/issues/188#issuecomment-561162043 - my solution would have been raising an error pointing to the package creating these objects.

**Comment by tim-salabim** [comment]
@edzer thanks for the pointer. I forgot about that one... I agree that this is ideally addressed somewhere else. I saw that **osmdata** has a dedicated function to "clean" the geometries for plotting. But it produces an error if used as a drop-in replacement for the above example:

```r
library(osmdata)
library(mapview)
library(poorman)

aoi = opq_osm_id(
  id = 2278487
  , type="relation"
) %>% 
  opq_string() %>% 
  osmdata_sf() %>% 
  poorman::pull(
    "osm_multipolygons"
  )

aoi2 = opq_osm_id(
  id = 2278487
  , type="relation"
) %>% 
  opq_string() %>% 
  unname_osmdata_sf() %>% 
  poorman::pull(
    "osm_multipolygons"
  )

Error: $ operator is invalid for atomic vectors
```
@mpadge should this work? If not, how can we use `unname_osmdata_sf()`?

**Comment by tim-salabim** [comment]
Figured it out:
```r
library(osmdata)
library(mapview)
library(poorman)

aoi = opq_osm_id(
  id = 2278487
  , type="relation"
) %>% 
  opq_string() %>% 
  osmdata_sf() %>% 
  unname_osmdata_sf() %>% 
  poorman::pull(
    "osm_multipolygons"
  )

mapviewOptions(fgb = FALSE)
mapview(aoi)
```
Reverted the fix, given that `osmdata` is the only package I have seen so far that produces this issue for mapview.

**Comment by mpadge** [comment]
@tim-salabim It would help if you could prompt yet again over in the relevant rstudio/leaflet#631 - a simple fix there will solve all of these issues.
