### ISSUE TITLE
Mapview does not render on GitHub Pages

### ISSUE THREAD

**Issue by qdread** [r-spatial/mapview#370]
I'm not sure if this is related to #312 or #351. I've tried both rolling back the mapview version to an older version, and updating to the dev version from GitHub, but nothing is working. 

We have a GitHub page with an embedded mapview (https://cyberhelp.sesync.org/vector-analysis-syracuse-lesson/#/slides/join , scroll down a bit from there), the relevant source code is at https://github.com/SESYNC-ci/vector-analysis-syracuse-lesson/blob/master/slides/join.Rmd (mapview code chunk is at bottom). The .Rmd is built using this script: https://github.com/SESYNC-ci/vector-analysis-syracuse-lesson/blob/master/bin/build_rmd.R . 

The code chunk where we call `mapview()` is pretty simple:

```
library(mapview)
mapview(census_tracts,
        legend = FALSE,
        viewer.suppress = TRUE) +
  mapview(lead['ppm'])
```

I haven't been able to get the mapview to render properly when the GitHub Page is built. The panel shows a blank map. Any ideas? Thanks in advance.

sessionInfo:

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_2.9.9
```

Unfortunately our remote server runs fairly old versions of GDAL and GEOS:

```
sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.5.1"        "2.2.2"        "4.9.2"         "true"        "false" 
```

**Comment by tim-salabim** [comment]
Not sure if this is the culprit, but inspecting the source of the page I see

```html
    <script src="/vector-analysis-syracuse-lesson/assets/.na.character/leaflet-providers_1.9.0.js"></script>
```
which is definitely not good, as it suggests that `leaflet-providers_1.9.0.js` cannot be found as it is supposedly located in a folder called `.na.character` which doesn't sound right.
Maybe something went wrong during the build?

Other than that I am not sure where things could go wrong as your GDAL does not support `fgb`, hence shouldn't be related to the issues you mention above...

**Comment by qdread** [comment]
Yes thanks for zeroing in on that issue. Our build script extracts all the html dependencies using `knit_meta()` then copies the scripts to the `/docs/assets/htmlwidgets` folder using the same relative paths. However for some reason the leaflet providers dependency gives a strange value for the file path:

```
[[9]]
List of 10
 $ name      : chr "leaflet-providers"
 $ version   : chr "1.9.0"
 $ src       :List of 1
  ..$ file: chr "/tmp/Rtmp2RoQLU"
 $ meta      : NULL
 $ script    : chr "leaflet-providers_1.9.0.js"
 $ stylesheet: NULL
 $ head      : NULL
 $ attachment: NULL
 $ package   : NULL
 $ all_files : logi FALSE
 - attr(*, "class")= chr "html_dependency"
```

It's `/tmp/Rtmp2RoQLU` so the relative path can't be constructed. I guess I might have to open an issue on the leaflet package?

**Comment by tim-salabim** [comment]
I think that would be a good starting point. It doesn't seem like it's particularly mapview related...

**Comment by qdread** [comment]
I was able to temporarily solve our problem by rolling leaflet back to v2.0.2 on our server. So at least we currently have a workaround. So I'll close this issue -- as you say the issue isn't really related to mapview. Thanks for all your work on the package!

**Comment by qdread** [comment]
Hi I am going to reopen this, apologies. I have actually been able to resolve mostly everything with the stable versions of leaflet and mapview. However I have a new issue when rendering on GitHub Pages. The layering does not seem to work. I have two layers to plot, a point layer and a polygon layer. Only the one that is plotted first is displaying. For example the current syntax is 

```
library(mapview)

mapview(lead['ppm'],
        map.types = 'OpenStreetMap',
        viewer.suppress = TRUE) +
  mapview(census_tracts,
          legend = FALSE)
```

In that case only the point feature `lead['ppm']` is rendering, not the polygon feature. 

If I switch it to the code below, only the polygons render and not the points. Any ideas there? Sorry again to reopen.

```
library(mapview)

mapview(census_tracts,
          legend = FALSE,
        map.types = 'OpenStreetMap',
        viewer.suppress = TRUE) +
  mapview(lead['ppm'])
```

**Comment by tim-salabim** [comment]
Can you reproduce the issue locally? Or is this only happening on the github page?

**Comment by qdread** [comment]
Try as I might, I can't reproduce it locally. It only happens on the Github page.

**Comment by tim-salabim** [comment]
Then it seems to be an issue of how you create your gh page, I guess. [This gh page](https://r-spatial.github.io/mapview/articles/articles/mapview_02-advanced.html#multiple-layers-1) works as expected

**Comment by qdread** [comment]
Yes, sorry for taking up your time. I was able to fix the issue with a workaround in our build script. So it wasn't anything to do with mapview. Again I appreciate all the work you've put into this amazing package. ✊

**Comment by tim-salabim** [comment]
No worries! Glad you found a solution!
