### ISSUE TITLE
Mapview: edit map - Raster image too large; 19177520 bytes is greater than maximum 4194304 bytes

### ISSUE THREAD

**Issue by Johnny987654321** [r-spatial/mapview#373]
I was trying to create a supervised classification of a map but then the overall resolution was limited when I actually wanted it to be the full resolution. I set the mapview option to Inf (infinite) but it still doesn't work. Below is the mapview settings and the error code that I was receiving:

![Screen Shot 2021-04-12 at 1 26 35 PM](https://user-images.githubusercontent.com/82477758/114626637-4cb66400-9cb4-11eb-9a49-d920b28339f3.png)

![Screen Shot 2021-04-12 at 1 29 30 PM](https://user-images.githubusercontent.com/82477758/114626654-5213ae80-9cb4-11eb-95dd-ca211dcbf889.png)

I hope someone can help me on this one.

**Comment by tim-salabim** [comment]
Thanks, I'll have a look soonish

**Comment by tim-salabim** [comment]
Should be fixed now. Can you please retry by re-installing both **leafem** and **mapview** from github:

```r
remotes::install_github("r-spatial/leafem")
remotes::install_github("r-spatial/mapview")
```

and let me know if that fixes your issue?

**Comment by Johnny987654321** [comment]
Hi Tim.

It's working just fine. I tried using Sentinel imagery and it was able to show the entire resolution. I think if I'm using a more powerful device, the processing speed would be faster. Thank you so much for this.

**Comment by tim-salabim** [comment]
@Johnny987654321 still experimental, but you could also try `mapviewOptions(georaster = TRUE)` which will use a dedicated leaflet plugin for large raster data. See e.g. https://twitter.com/TimSalabim3/status/1280950560892518402 . This plugin does resampling on-the-fly in the browser.

**Comment by Johnny987654321** [comment]
Sorry for opening this up again but I used the mapview and editmap function and it seems like its having a hard time processing around 150 or 200 spatial points.  After selecting DONE I am stuck waiting for it over an hour now. I'm really sorry for this problem. Should I create a new post about this?

**Comment by tim-salabim** [comment]
Yes please. A reprex would be great too. And do you think this is a mapview or mapedit issue?

**Comment by Johnny987654321** [comment]
I think its not its probably just my computer not being able to process things out... Thanks anyway
