### ISSUE TITLE
Automatically unselect all but the first layer

### ISSUE THREAD

**Issue by mzwick1** [r-spatial/mapview#374]
Is it possible to control which layers are switched on? Ideally, I would have a map with a raster brick where 4 layers are loaded but only the first one switched on.
Is that already implemented and I overlocked it?

Thank you for your help

**Comment by tim-salabim** [comment]
Hi @mzwick1 
this used to work via a hidden argument `hide`. Not sure where that was degraded, but I've re-enabled it, so you can now do:

``` r
library(mapview)
library(plainview, include.only = "poppendorf")

mapview(poppendorf, hide = TRUE)
```

![](https://i.imgur.com/AZ4DPVd.png)

<sup>Created on 2021-06-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by tim-salabim** [comment]
Also added a section in Description of the mapview documentation.
