### ISSUE TITLE
`layer.name` does not seem to work when `zcol`’s length > 1

### ISSUE THREAD

**Issue by edalfon** [r-spatial/mapview#383]
`layer.name` lets you customize “the name of the layer to be shown on
the map”. It works great!

``` r
library(mapview)
#> Warning: package 'mapview' was built under R version 4.0.3
mapview(breweries, zcol = "founded", layer.name = "Custom Layer Name: Founded")
```

![](https://i.imgur.com/AM0sz3u.png)

Now, it is also great that `zcol` can be a vector of length > 1, and
`mapview` renders every column indicated by `zcol`, as a separate layer.
However, in that case, `layer.name` does not seem to work anymore and the
names shown on the map go back to the default (column name).

``` r
mapview(
  breweries,
  zcol = c("founded", "number.seasonal.beers"),
  layer.name = c("Custom Layer Name: Founded",
                 "Custom Layer Name: # Seasonal Beers")
)
```

![](https://i.imgur.com/mH29hCE.png)

I got this to work by adding the layers using + operator
(I guess passing a list would also work).

``` r
mapview(breweries, zcol = "founded", layer.name = "Custom Layer Name: Founded") +
  mapview(breweries, zcol = "number.seasonal.beers", layer.name = "Custom Layer Name: # Seasonal Beers")
```

![](https://i.imgur.com/WTSUvyc.png)

But when you want to render several layers using different columns from
the same attribute table it is certainly more convenient the approach of
passing a vector to `zcol` and a matching vector to `layer.name`.

<sup>Created on 2021-05-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by tim-salabim** [comment]
Thanks, should work now.

**Comment by edalfon** [comment]
awesome!, thanks
