### ISSUE TITLE
sync rather than | still described in mapview articles

### ISSUE THREAD

**Issue by mhweber** [r-spatial/mapview#384]
Although mapview now uses  | operator rather than sync as of 2.9.0, the [extra functionality](https://r-spatial.github.io/mapview/articles/articles/mapview_05-extras.html) page still describes sync, and trying to use sync in R simply fails with no warning or messages.

**Comment by tim-salabim** [comment]
Using sync shouldn't fail silently. Do you have a reprex?

**Comment by mhweber** [comment]
@tim-salabim , sorry, it does give error but not warning or message - reprex from `mapview` [extra functionality](https://r-spatial.github.io/mapview/articles/articles/mapview_05-extras.html) page:

        m1 <- mapview(breweries, zcol = "village", map.types = "Esri.WorldImagery")
        m2 <- mapview(breweries, zcol = "brewery", col.regions = heat.colors)
        m3 <- mapview(breweries, zcol = "founded", legend = TRUE)
        m4 <- leaflet() %>% addTiles() %>% addCircleMarkers(data = breweries)

        sync(m1, m2, m3, m4)

Gives error:   `Error in sync(m1, m2, m3, m4) : could not find function "sync"`

So not really an issue in code; simply wanted to point out that documentation still describes using `sync` rather than `|` and using `sync` doesn't alert user to the new operator - had to find in switch in operator use in [changelog](https://r-spatial.github.io/mapview/news/index.html)
