### ISSUE TITLE
RStudio, Mapview - Issue when knitting to HTML

### ISSUE THREAD

**Issue by AnaWalpole** [r-spatial/mapview#386]
I created a nice map using:

library(mapview)
mapview(data, zcol = "case_rate")

However, when I try to knit to HTML, I get an error:
Could not determine mime type for `C:\Users\abcde\AppData\Local\Temp\RtmpGIAPDC\file154c41c935e\map-case_rate_layer.fgb'
Error: pandoc document conversion failed with error 63

And I'm not sure how to get around it...anybody got any ideas?

**Comment by tim-salabim** [comment]
Yes, you have two options (for now, until the current version makes it to CRAN). Either 

```r
remotes::install_github("r-spatial/mapview")
```
or 
```r
library(mapview)
mapviewOptions(fgb = FALSE)
mapview(data, zcol = "case_rate")
```

**Comment by tim-salabim** [comment]
Hopefully soon. There's still a few issues to iron out. I hope after my holidays next week.

**Comment by AnaWalpole** [comment]
Wonderful! Thank you :)

**Comment by donojazz** [comment]
I just recently had exact same issue.  I found the best solution was to download mapview 2.9.9 from github.  It fixed my problem. . JD

**Comment by tim-salabim** [comment]
mapview 2.10.0 is on CRAN, so I'm closing this here. Feel free to re-open if this issue persists.
