### ISSUE TITLE
Adding mapview layers to leaflet maps and vice versa

### ISSUE THREAD

**Issue by mosscoder** [r-spatial/mapview#39]
From [this](https://www.r-bloggers.com/mapview-0-5-0/) old blog post I read about:

_enhanced leaflet integration so that you can use leaflet maps and add features using mapview (e.g. +) or use mapview to create maps and add functionality provided by leaflet (using e.g. %>%)_

Yet I'm unable to join leaflet and mapview layers by this method. Can someone please provide an example of how to do this?

**Comment by tim-salabim** [comment]
What exactly are you trying to do? 

`+` is currently defined for:

1. `mapview + mapview` to easily combine two mapview maps

```
library(mapview)
mapview(breweries91) + mapview(gadmCHE)
```

2. `mapview + ANY` to easily add features (sp or raster objects) to a mapview map

```
mapview(breweries91) + gadmCHE
```

3. `leaflet + ANY` to add features to a leaflet map

```
leaflet() %>% addTiles() %>% addPolygons(data = gadmCHE) + breweries91
```

In addition you can use `%>%` to add things to a mapview map

```
mapview(gadmCHE)@map %>% addCircleMarkers(data = breweries91)
```

**Comment by eriklindquist** [comment]
Along these same lines...can mapview be used within a leafletProxy statement?

I want to start with a generic 'mapview' then add data according to user input via a R shiny app.

Many thanks for your very useful package.

**Comment by tim-salabim** [comment]
I do not work a lot w shiny, so could you give us a little reproducible example?

**Comment by eriklindquist** [comment]
Hi Tim

here is the code I am using...sorry for all the 'library' calls at the beginning...and for any crappy coding.  I am not so much a coder as I am a natural scientist...

[app.R.zip](https://github.com/environmentalinformatics-marburg/mapview/files/553769/app.R.zip)

**Comment by tim-salabim** [comment]
Thanks for the example. However, I am sorry but I do not understand what and how you are trying to achieve things. 
The error I get ("Error in +: non-numeric argument to binary operator") seems to suggest that it is not using the `+` operator provided by **mapview** but the base operator. Even when attaching mapview explicitly in the `server` function via `library(mapview)`.

I will need to dig more to find the root cause of this. In the meantime it would be very helpful if you could provide a simpler example (i.e. without the whole file select and all the type testing inside the app - makes it hard to debug). Ideally one where things work with a leaflet basemap, but not with the generic mapview basemap.

**Comment by eriklindquist** [comment]
Hi Tim...sorry about all that.  Yes, I will try to make a more simple example.

**Comment by daauerbach** [comment]
thanks for a great tool. the "+" and "%>%" answer above resolved my question. at some point may want to add/integrate this into the very nice doc pages...

**Comment by tim-salabim** [comment]
@daauerbach there is an easier way indeed. We have a non-exported function called `mapViewLayersControl` which basically does what you do manually here. To achieve the same as you do above you can simply do:

```
library(mapview)
library(sp)
#reproducible example; probably will need to view in browser (and zoom out to see any NEF)
data.frame(lon=-84, lat=34)%>%
  SpatialPointsDataFrame(data=data.frame(f="foo"),proj4string=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")) %>%
  mapview() -> m
m@map = m@map %>% 
  addWMSTiles(group="TWI", baseUrl="https://geoplatform1.epa.gov/arcgis/services/NEF/WetnessIndex/MapServer/WMSServer?", layers = "0", options = WMSTileOptions(format = "image/png", transparent = TRUE), attribution = "EPA") %>%
  addWMSTiles(group="NEF", baseUrl="https://geoplatform1.epa.gov/arcgis/services/NEF/NationalEcologicalFramework/MapServer/WMSServer?", layers = c("1","2","3"), options = WMSTileOptions(format = "image/png", transparent = TRUE), attribution = "EPA") %>%
  addWMSTiles(group="NLCD", baseUrl="http://isse.cr.usgs.gov/arcgis/services/LandCover/USGS_EROS_LandCover_NLCD/MapServer/WMSServer?",layers = c("1","6"), options = WMSTileOptions(format = "image/png", transparent = TRUE), attribution = "USGS") %>%
  mapview:::mapViewLayersControl(names = c("TWI","NEF","NLCD"))
m
```
where the `names` argument refers to the `group` argument in the `addWMSTiles` call.

**Comment by tim-salabim** [comment]
@eriklindquist are you still having this issue? If so, did you ever get a simpler example?

**Comment by joshualerickson** [comment]
Is there a solution to this ` ("Error in +: non-numeric argument to binary operator") ` via 2020? My goal has been to add a mapview object generated by rgee to a leaflet object that I generate. Example below. BTW love both packages! I'm expecting the breweries layer to be on top of the `viz_Area()` object, thus is probably my faulty logic. Thanks.

```viz_Area <- function() {

  grp <- c("USGS Topo", "USGS Imagery Only", "USGS Imagery Topo",
           "USGS Shaded Relief", "Hydrography")
  att <- paste0("<a href='https://www.usgs.gov/'>",
                "U.S. Geological Survey</a> | ",
                "<a href='https://www.usgs.gov/laws/policies_notices.html'>",
                "Policies</a>")
  GetURL <- function(service, host = "basemap.nationalmap.gov") {
    sprintf("https://%s/arcgis/services/%s/MapServer/WmsServer", host, service)
  }

  map <- leaflet::leaflet()
  map <- leaflet::addWMSTiles(map, GetURL("USGSTopo"),
                              group = grp[1], attribution = att, layers = "0")
  map <- leaflet::addWMSTiles(map, GetURL("USGSImageryOnly"),
                              group = grp[2], attribution = att, layers = "0")
  map <- leaflet::addWMSTiles(map, GetURL("USGSImageryTopo"),
                              group = grp[3], attribution = att, layers = "0")
  map <- leaflet::addWMSTiles(map, GetURL("USGSShadedReliefOnly"),
                              group = grp[4], attribution = att, layers = "0")

  opt <- leaflet::WMSTileOptions(format = "image/png", transparent = TRUE)
  map <- leaflet::addWMSTiles(map, GetURL("USGSHydroCached"),
                              group = grp[5], options = opt, layers = "0")
  map <- leaflet::hideGroup(map, grp[5])
  opt <- leaflet::layersControlOptions(collapsed = TRUE)
  map <- leaflet::addLayersControl(map, baseGroups = grp[1:4],
                                   overlayGroups = grp[5], options = opt)
  map %>%
    leafem::addMouseCoordinates(epsg = "EPSG:4326", proj4string = "+proj=utm +zone=32 +ellps=WGS84 +datum=WGS84 +units=m +no_defs")

}
```
viz_Area() + mapview::mapview(breweries)

```
Error in viz_Area() + mapview(breweries) : 
  non-numeric argument to binary operator
```

**Comment by tim-salabim** [comment]
I haven't tested your code, but where is viz_Area() defined? I might have learned enough over the last year's to be able to finally solve this, but no promises 👎🏽

**Comment by joshualerickson** [comment]
Sorry bout that!  `viz_Area <- function(){` should be at the top of the code. Been messing around with the code and my fault for not going through each of the steps and understanding what mapview does. On my end it doesn't make sense for me to make a function `viz_Area()` and then pass on to mapview, e.g. viz_Area() + mapview(breweries) or vice versa viz_Area() %>% mapview(breweries). My guess is it's due to  a `leaflet() %>% leaflet()` call embedded in both functions. I should pivot my code direction or if there is some way to **clear** a `leaflet()` call similar to `ggnewscale` that would be sweet. Example. Take the preceding call and copy all the calls and arguments.

```
clearLeaf <- function(leaf, data) {
  
  calls <- data@map$x$calls
  app <- append(calls, leaf$x$calls)
  
  leaf$x$calls <- app
  
  leaf
}
```


`viz_Area() %>% clearLeaf(mapview(breweries)) `

However, you don't retain the addLayers() arguments call from the following mapview object. Very hacky, but maybe expresses my path.

Have a good one.

**Comment by BWOlatunji** [comment]
> What exactly are you trying to do?
> 
> `+` is currently defined for:
> 
> 1. `mapview + mapview` to easily combine two mapview maps
> 
> ```
> library(mapview)
> mapview(breweries91) + mapview(gadmCHE)
> ```
> 
> 1. `mapview + ANY` to easily add features (sp or raster objects) to a mapview map
> 
> ```
> mapview(breweries91) + gadmCHE
> ```
> 
> 1. `leaflet + ANY` to add features to a leaflet map
> 
> ```
> leaflet() %>% addTiles() %>% addPolygons(data = gadmCHE) + breweries91
> ```
> 
> In addition you can use `%>%` to add things to a mapview map
> 
> ```
> mapview(gadmCHE)@map %>% addCircleMarkers(data = breweries91)
> ```

Is there a way to combine multiple mapview i.e. mapview()+mapview() in r shiny without getting this same error?

**Comment by joshualerickson** [comment]
Here are a couple of work arounds using `renderLeaflet()` function in shiny; 

```
library(shiny)
library(mapview)
library(leaflet)

ui <- fluidPage(
  
  leafletOutput('leafmap')
)

server <- function(input, output, session) {
  
  combined_mapview <- mapview(breweries) + mapview(gadmCHE)
  
  output$leafmap <- renderLeaflet({
    
    
    combined_mapview@map
    
  
  })
  
}

shinyApp(ui, server)

```

Or 

```
ui <- fluidPage(
  
  leafletOutput('leafmap')
)

server <- function(input, output, session) {
  
  output$leafmap <- renderLeaflet({
    
    (mapview(breweries) + mapview(gadmCHE))@map
    
  
  })
  
}

shinyApp(ui, server)

```

**Comment by atashie** [comment]
@joshualerickson thanks for that amazing solution! I have been having the same issue and your solution is the first to work for me
