### ISSUE TITLE
popup and burst conflict

### ISSUE THREAD

**Issue by Sckende** [r-spatial/mapview#391]
Hi Tim,

I would like to use custom popups combined with the burst argument. Custom popups work well if `burst = F`, but are replaced by default popups when `burst = T`.

See the following examples: 

```r
library(mapview)
mapview(franconia, zcol = 'NUTS_ID', popup = T) # works

mapview(franconia, zcol = 'NUTS_ID', popup = 'SHAPE_AREA') # works

mapview(franconia, zcol = 'NUTS_ID', popup = 'SHAPE_AREA', burst = T) # doesn't work

```
I use R 4.1.1. and the latest version of mapview (2.10.0) on Windows 10.

Thanks for your time.

**Comment by tim-salabim** [comment]
@Sckende this should now work, though you won't get full control over the popup content when supplying a column name. However, you can now also specify the popups yourself (with all the control you want). E.g.:

```r
mapview(
  franconia
  , zcol = 'NUTS_ID'
  , popup = leafpop::popupTable(
    franconia
    , zcol = 'NAME_ASCI'
    , feature.id = FALSE
    , row.numbers = FALSE
    , className = "mapview-popup" # to use mapview popup css
  )
  , burst = TRUE
)
```
![image](https://user-images.githubusercontent.com/2826432/131247051-59493aa5-3d0f-4ec3-8ea7-986473236331.png)

Let me know if that solves your issue?

**Comment by Sckende** [comment]
It works for me. Thanks a lot !
