### ISSUE TITLE
renderMapview in rmackdown

### ISSUE THREAD

**Issue by agronomofiorentini** [r-spatial/mapview#393]
Hi Tim,
I have a problem with rendering mapview within r mackdown with runtime: shiny.

Consider that I have a sentinel image and I have a number of shapefiles.

I created a reactive object based on user input (selectInput) in order to clip only the zone that the user insert.

When I then pass this reactiver object to mapview, it returns the following error.

Warning: Error in : Operation not allowed without an active reactive context.
* You tried to do something that can only be done from within a reactive consumer.
  149: <Anonymous>

The code for rendering is
```
renderMapview({
     reactive_object()
})
```

Do you know how can i solve this?

**Comment by tim-salabim** [comment]
Try `renderLeaflet` and return the @map slot of the mapview object.

**Comment by agronomofiorentini** [comment]
Worked perfectly.. thanks
Kind regards 

Marco
