### ISSUE TITLE
Uncheck spatial layers on map start?

### ISSUE THREAD

**Issue by RussellGrayxd** [r-spatial/mapview#404]
Hi devs,

is it possible to uncheck all spatial layers on map start when there are multiple layers so the user can check them as they please?

Thank!
RG

**Comment by tim-salabim** [comment]
This was possible once, but I think got lost somewhere... I'll have a look. Are you referring to list objects or when using +?

**Comment by RussellGrayxd** [comment]
Both I guess! Basically if I have multiple overlapping polygons added into a single interactive mapview, I would like to start the map with them unchecked.
Would be great to have this!
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 

0934581341 | ***@***.***://www.rjgrayecology.com/
705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168

 |
| 
 |
|  |

 

    On Thursday, November 25, 2021, 02:25:24 p.m. GMT+7, tim-salabim ***@***.***> wrote:  
 
 


This was possible once, but I think got lost somewhere... I'll have a look. Are you referring to list objects or when using +?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by temospena** [comment]
Hi,
I'm looking for the same solution, in this case using +.
Thanks!

**Comment by tim-salabim** [comment]
This should now work for all methods. All got a new argument `hide = FALSE` as default. If you have a list of layers, you can pass a boolean vector/list to control which should be hidden.

**Comment by RussellGrayxd** [comment]
Absolute gold. Works great!
Thanks a million!RG
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 

0934581341 | ***@***.***://www.rjgrayecology.com/
705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168

 |
| 
 |
|  |

 

    On Monday, December 6, 2021, 02:39:03 p.m. GMT+7, tim-salabim ***@***.***> wrote:  
 
 


This should now work for all methods. All got a new argument hide = FALSE as default. If you have a list of layers, you can pass a boolean vector/list to control which should be hidden.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
