### ISSUE TITLE
When calling multiple mapview objects with +, only the first is rendered

### ISSUE THREAD

**Issue by michaeldgarber** [r-spatial/mapview#406]
Hello, thanks for the great package. I like to create mapview objects and then layer them over one another using the + sign. Recently (I noticed it today), this layering is no longer working as expected. It only prints the first layer called in the sequence.

For example, in the code below, only the object "mv_many_seasonals" is rendered. Thanks in advance for any help.

```
mapview(breweries)
summary(breweries$number.seasonal.beers)

breweries_many_seasonals = breweries %>% 
  st_sf() %>% 
  filter(number.seasonal.beers > 3)

breweries_fewer_seasonals = breweries %>% 
  st_sf() %>% 
  filter(number.seasonal.beers <= 3)

mv_many_seasonals = breweries_many_seasonals %>% mapview(col.regions = "red")
mv_fewer_seasonals = breweries_fewer_seasonals %>% mapview(col.regions = "blue")

mv_many_seasonals + mv_fewer_seasonals
```

Session Info:
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)
> packageVersion("mapview")
[1] ‘2.10.0’

**Comment by tim-salabim** [comment]
This is because you're using the %>% pipe. One of the problems with it is that all data that it spits out is called `.` so effectively so want to add two layers with the same name. So either set the `layer.name` arguments to individual names for each layer, or do the call without the pipe:

```
mv_many_seasonals = mapview(breweries_many_seasonals, col.regions = "red")
mv_fewer_seasonals = mapview(breweries_fewer_seasonals, col.regions = "blue")

mv_many_seasonals + mv_fewer_seasonals
```

**Comment by michaeldgarber** [comment]
Perfect - that did the trick. Thanks! I will remember to use the `layer.name` argument.

So just to be clear in case helpful for others, this works as expected:
```
mv_many_seasonals = breweries %>% 
  filter(number.seasonal.beers > 3) %>% 
  mapview(col.regions = "red", layer.name = "many seasonals")

mv_fewer_seasonals = breweries %>% 
  filter(number.seasonal.beers <= 3) %>% 
  mapview(col.regions = "blue", layer.name = "fewer seasonals")

mv_many_seasonals+mv_fewer_seasonals
```
