### ISSUE TITLE
Does map.types function?

### ISSUE THREAD

**Issue by fabeit** [r-spatial/mapview#407]
I have tried several of the options shown here https://leaflet-extras.github.io/leaflet-providers/preview/ but none of them seem to work. Does map.types actually work or do I require some sort of API?

**Comment by tim-salabim** [comment]
Hi, thanks for raising this. I just tried a few myself and it seems only selected ones from that list work... If you open your map in the browser and open the browser console it should tell you what is going on. For Thunderforest for example, the error says

"Failed to load resource: the server responded with a status of 403 (Forbidden)"

so it seems one needs a token or thelike to access those...

**Comment by fabeit** [comment]
Thanks for the reply. I am not sure where do you see that error message. I am using Rstudio and when I use mapview the map appears in the viewer. If I then open in the browser (Mozilla) and then open the console I have maybe 20 errors and a few warnings. Is it this one "TopSitesFeed: Failed to fetch data from Contile server: NetworkError when attempting to fetch resource.".

In any case it's still strange because not even "Stamen.Terrain" or any of the Stamen work, but they work with get_map.

**Comment by tim-salabim** [comment]
Stamen.Terrain works for me. Do you have any ad-blockers on or something? Or are you behind a firewall?

**Comment by fabeit** [comment]
No I have everything disabled and do not use a firewall, could you provide your test code please?

**Comment by tim-salabim** [comment]
I am away from the computer rn, so will share tomorrow. Do you see the background maps when calling mapview without map.types argument?

**Comment by tim-salabim** [comment]
``` r
library(mapview)
mapview(franconia, map.types = "Stamen.Toner")
#> old-style crs object detected; please recreate object with a recent sf::st_crs()
#> old-style crs object detected; please recreate object with a recent sf::st_crs()
```

![](https://i.imgur.com/mleV6t3.png)

<sup>Created on 2021-12-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by fabeit** [comment]
@tim-salabim Thank Tim, now everything works, I have no clue what was blocking the map. Just a quick question. Is there a way to save mapview as a ggplot object? I would like to insert a mapview map into the plot_grid() function so I can combine maps and graphics. At the moment I am using ggmap() but it has limited controls and only Stamen. Any idea?

**Comment by tim-salabim** [comment]
No, there's now way to coerce a mapview object to a ggplot object currently. Have you looked at [maptiles](https://github.com/riatelab/maptiles)? Not sure if it works with ggplot though.
