### ISSUE TITLE
mapview 

### ISSUE THREAD

**Issue by sg630** [r-spatial/mapview#410]
> library(mapview)
Error: package or namespace load failed for ‘mapview’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘terra’ 1.4-22 is being loaded, but >= 1.5.12 is required

**Comment by tim-salabim** [comment]
Try reinstalling terra and raster

**Comment by markolipka** [comment]
I had the same problem a few days ago on a windows machine running R 4.0.?.

Reinstalled lots of packages but not sure what fixed it in the end...

**Comment by sg630** [comment]
Got it <- Thank you so much
________________________________
