### ISSUE TITLE
Error: old-style crs object detected; please recreate object with a recent sf::st_crs()

### ISSUE THREAD

**Issue by jslingsby** [r-spatial/mapview#411]
Hi Tim

I'm trying to plot a set of points with mapview(), but an interactive map is produced in the right place, but with no points shown and no error returned.

It may not be related*, but when I try the demo:
`mapview(breweries)`
I get:
_old-style crs object detected; please recreate object with a recent sf::st_crs()_

and again, no points appear...

I see the same error occurs in the [documentation example](https://r-spatial.github.io/mapview/reference/ops.html)

Not being able to find the breweries is even more dissappointing than not being able to plot my points - spatial R is thirsty work!

Likely an sf issue, but I thought I should make you aware of it.

*Edit: `mapviewOptions(fgb = FALSE)` solves the issue, so probably not related after all. Feel free to close the issue, but I'll leave it here so you're aware of the crs warning.

Thanks for a great package!
Jasper

**Comment by tim-salabim** [comment]
Thanks! I'll look into this soon. Lot's has changed in the spatial world since the last CRAN release, so time for me to catch up...

**Comment by tim-salabim** [comment]
Should work again if you install latest `leafem` from github... To avoid the crs warnings you'd also need to re-install `mapview` from github.
