### ISSUE TITLE
Plot a histogram with the values of the clicked pixel in a mapview with raster stack layer

### ISSUE THREAD

**Issue by agronomofiorentini** [r-spatial/mapview#416]
Dear contributors,
I would like to ask you if it is possible to create a histogram with the values of the pixel clicked in a map defined with mapview containing a stack layer.

With this function the shiny user can appreciate the temporal evolution of the value in a given pixel and be able to make considerations on the possible causes of such variation.

**Comment by tim-salabim** [comment]
Do you have an example where we could see such a histogram?

**Comment by agronomofiorentini** [comment]
Yes of course

I will attach the jpeg of the plot that i would like to generate on click on the mapview with the stack layer.

![newplot](https://user-images.githubusercontent.com/66969646/160610583-a1d2d680-b4bb-46a0-a8c7-e24416b232fd.png)

If you need i could also share the single raster layers tiff format.

**Comment by agronomofiorentini** [comment]
I will try to follow your suggestion and try to create a reproducible example and bring it back here.

I hope to succeed, in case then you could help me out.

Thanks Tim, I appreciate it

**Comment by tim-salabim** [comment]
Maybe for reprex purposes there a raster stack NDVI data set in library(cubeview)... Should be enough for a reprex.
