### ISSUE TITLE
default popup not displaying

### ISSUE THREAD

**Issue by djdowning** [r-spatial/mapview#417]
Just had this start occurring, not sure the cause?  The default popup won't render in RStudio, but if I remove certain fields it will render.  I tried calling it explicitly and also using leafpop calling popupTable but that would not work either.  Thank you.

(need a census key for this tidycensus example)

library(tidycensus)
library(tidyverse)
library(mapview)
library(leaflet)
library(leafpop)
library(sf)

blockgroup <- get_acs(geography = "tract", 
                      state = "Illinois",  
                      geometry = TRUE,
                      variable = c(Population="B01003_001",MedIncome="B06011_001"))

bg20 <- blockgroup %>% 
  dplyr::select(GEOID, NAME, variable, estimate, geometry) %>% 
  spread(key=variable, value = estimate)

mapview(bg20, zcol = "Population")  #no popup

bg20works <- bg20 %>% dplyr::select(-NAME)

mapview(bg20works, zcol = "Population") #popup works again

bg20worksalso <- bg20 %>% filter(str_length(NAME) < 45) 
mapview(bg20worksalso, zcol = "Population") #popup works also

**Comment by tim-salabim** [comment]
Can you make a reproducible example that doesn't require a census key?

**Comment by djdowning** [comment]
There was 2 missing geometries in the dataset I missed removing.  Once I removed the empty geometries all is well again.  Thanks Tim.
