### ISSUE TITLE
warning message when plotting raster

### ISSUE THREAD

**Issue by maxbre** [r-spatial/mapview#422]
given my reproducible example

```
library(tibble)
library(raster)
library(mapview)

tb <- tribble(
  ~x, ~y,  ~z,
  744916, 5037923,  1.0,
  744941, 5037923,  2.0,
  744916, 5037973,  3.0,
  744941, 5037973,  4.0
)

r <- rasterFromXYZ(tb, crs = 32632)

mapview(r)

```
I've got  the following:

```
Warning messages:
1: In showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj = prefer_proj) :
   Discarded ellps WGS 84 in Proj4 definition: +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs +type=crs
2: In showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj = prefer_proj) :
   Discarded datum World Geodetic System 1984 in Proj4 definition

```

what does it means that? 
can it be safely disregarded?
the warning message is spit out just the first time mapview is called

I've been looking around for a solution but as far as I understand the warning seems related to something like here mentioned:
- https://stackoverflow.com/questions/63727886/proj4-to-proj6-upgrade-and-discarded-datum-warnings
- https://gis.stackexchange.com/questions/372692/how-should-i-handle-crs-properly-after-the-major-change-in-proj-library/373449#373449

I've been trying also to pass crs in a different format but nothing seems to happen

```
r2 <- rasterFromXYZ(tb)
crs(r2) <- "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs" 
mapview(r2)

r3 <- rasterFromXYZ(tb)
crs(r3)<-CRS("+init=epsg:32632")
mapview(r3)

r4 <- rasterFromXYZ(tb)
crs(r4)<-CRS(SRS_string = "EPSG:32632")
mapview(r4)

```
any help for this?

thank you

> session_info()
─ Session info ────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22)
 os       Debian GNU/Linux 11 (bullseye)
 system   x86_64, linux-gnu
 ui       RStudio
 language en_GB:en
 collate  en_GB.UTF-8
 ctype    en_GB.UTF-8
 tz       UTC
 date     2022-05-16
 rstudio  2022.02.1+461 Prairie Trillium (desktop)
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────
 package           * version date (UTC) lib source
 assertthat          0.2.1   2019-03-21 [1] CRAN (R 4.2.0)
 base64enc           0.1-3   2015-07-28 [1] CRAN (R 4.2.0)
 brio                1.1.3   2021-11-30 [1] CRAN (R 4.2.0)
 cachem              1.0.6   2021-08-19 [1] CRAN (R 4.2.0)
 callr               3.7.0   2021-04-20 [1] CRAN (R 4.2.0)
 class               7.3-20  2022-01-13 [3] CRAN (R 4.2.0)
 classInt            0.4-3   2020-04-07 [1] CRAN (R 4.2.0)
 cli                 3.3.0   2022-04-25 [1] CRAN (R 4.2.0)
 codetools           0.2-18  2020-11-04 [3] CRAN (R 4.0.3)
 colorspace          2.0-3   2022-02-21 [1] CRAN (R 4.2.0)
 crayon              1.5.1   2022-03-26 [1] CRAN (R 4.2.0)
 crosstalk           1.2.0   2021-11-04 [1] CRAN (R 4.2.0)
 DBI                 1.1.2   2021-12-20 [1] CRAN (R 4.2.0)
 desc                1.4.1   2022-03-06 [1] CRAN (R 4.2.0)
 devtools          * 2.4.3   2021-11-30 [1] CRAN (R 4.2.0)
 digest              0.6.29  2021-12-01 [1] CRAN (R 4.2.0)
 dplyr               1.0.9   2022-04-28 [1] CRAN (R 4.2.0)
 e1071               1.7-9   2021-09-16 [1] CRAN (R 4.2.0)
 ellipsis            0.3.2   2021-04-29 [1] CRAN (R 4.2.0)
 fansi               1.0.3   2022-03-24 [1] CRAN (R 4.2.0)
 farver              2.1.0   2021-02-28 [1] CRAN (R 4.2.0)
 fastmap             1.1.0   2021-01-25 [1] CRAN (R 4.2.0)
 fs                  1.5.2   2021-12-08 [1] CRAN (R 4.2.0)
 generics            0.1.2   2022-01-31 [1] CRAN (R 4.2.0)
 glue                1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
 htmltools           0.5.2   2021-08-25 [1] CRAN (R 4.2.0)
 htmlwidgets         1.5.4   2021-09-08 [1] CRAN (R 4.2.0)
 jsonlite            1.8.0   2022-02-22 [1] CRAN (R 4.2.0)
 KernSmooth          2.23-20 2021-05-03 [3] CRAN (R 4.2.0)
 lattice             0.20-45 2021-09-22 [3] CRAN (R 4.2.0)
 leafem              0.2.0   2022-04-16 [1] CRAN (R 4.2.0)
 leaflet             2.1.1   2022-03-23 [1] CRAN (R 4.2.0)
 leaflet.providers   1.9.0   2019-11-09 [1] CRAN (R 4.2.0)
 lifecycle           1.0.1   2021-09-24 [1] CRAN (R 4.2.0)
 magrittr            2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
 mapview           * 2.11.0  2022-04-16 [1] CRAN (R 4.2.0)
 memoise             2.0.1   2021-11-26 [1] CRAN (R 4.2.0)
 munsell             0.5.0   2018-06-12 [1] CRAN (R 4.2.0)
 pillar              1.7.0   2022-02-01 [1] CRAN (R 4.2.0)
 pkgbuild            1.3.1   2021-12-20 [1] CRAN (R 4.2.0)
 pkgconfig           2.0.3   2019-09-22 [1] CRAN (R 4.2.0)
 pkgload             1.2.4   2021-11-30 [1] CRAN (R 4.2.0)
 png                 0.1-7   2013-12-03 [1] CRAN (R 4.2.0)
 prettyunits         1.1.1   2020-01-24 [1] CRAN (R 4.2.0)
 processx            3.5.3   2022-03-25 [1] CRAN (R 4.2.0)
 proxy               0.4-26  2021-06-07 [1] CRAN (R 4.2.0)
 ps                  1.7.0   2022-04-23 [1] CRAN (R 4.2.0)
 purrr               0.3.4   2020-04-17 [1] CRAN (R 4.2.0)
 R6                  2.5.1   2021-08-19 [1] CRAN (R 4.2.0)
 raster            * 3.5-15  2022-01-22 [1] CRAN (R 4.2.0)
 Rcpp                1.0.8.3 2022-03-17 [1] CRAN (R 4.2.0)
 remotes             2.4.2   2021-11-30 [1] CRAN (R 4.2.0)
 rgdal               1.5-31  2022-04-18 [1] CRAN (R 4.2.0)
 rlang               1.0.2   2022-03-04 [1] CRAN (R 4.2.0)
 rprojroot           2.0.3   2022-04-02 [1] CRAN (R 4.2.0)
 rstudioapi          0.13    2020-11-12 [1] CRAN (R 4.2.0)
 satellite           1.0.4   2021-10-12 [1] CRAN (R 4.2.0)
 scales              1.2.0   2022-04-13 [1] CRAN (R 4.2.0)
 sessioninfo         1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
 sf                  1.0-7   2022-03-07 [1] CRAN (R 4.2.0)
 sp                * 1.4-7   2022-04-20 [1] CRAN (R 4.2.0)
 terra               1.5-21  2022-02-17 [1] CRAN (R 4.2.0)
 testthat            3.1.4   2022-04-26 [1] CRAN (R 4.2.0)
 tibble            * 3.1.7   2022-05-03 [1] CRAN (R 4.2.0)
 tidyselect          1.1.2   2022-02-21 [1] CRAN (R 4.2.0)
 units               0.8-0   2022-02-05 [1] CRAN (R 4.2.0)
 usethis           * 2.1.5   2021-12-09 [1] CRAN (R 4.2.0)
 utf8                1.2.2   2021-07-24 [1] CRAN (R 4.2.0)
 vctrs               0.4.1   2022-04-13 [1] CRAN (R 4.2.0)
 webshot             0.5.3   2022-04-14 [1] CRAN (R 4.2.0)
 withr               2.5.0   2022-03-03 [1] CRAN (R 4.2.0)
 yaml                2.3.5   2022-02-21 [1] CRAN (R 4.2.0)

 [1] /home/max/R/x86_64-pc-linux-gnu-library/4.2
 [2] /usr/lib/R/site-library
 [3] /usr/lib/R/library

**Comment by edzer** [comment]
It's nothing really serious or worrysome; you get rid of the warning if you start your script with
```r
options(rgdal_show_exportToProj4_warnings = "none")
```

**Comment by maxbre** [comment]
thank you for the useful clarification, the fix works!
issue closed by my side
best

**Comment by tim-salabim** [comment]
Thanks for clarifying.
