### ISSUE TITLE
Cannot Save mapview or leaflet map as an image

### ISSUE THREAD

**Issue by msgoussi** [r-spatial/mapview#428]
```
m = mapview(breweries)
mapshot(m, file = paste0(getwd(), "/map.png"), 
remove_controls = c("homeButton", "layersControl"))
```

Could not load  c:%5CUsers%5C310677%5CAppData%5CLocal%5CTemp%5CRtmpqmrFHp%5Cfile5bb41a1a44ee.html
Error in (function (url = NULL, file = "webshot.png", vwidth = 992, vheight = 744,  : 
  webshot.js returned failure value: 1

**Comment by tim-salabim** [comment]
Please see #419
