### ISSUE TITLE
Mapview moving data?

### ISSUE THREAD

**Issue by Bruno-mels** [r-spatial/mapview#436]
Hi,

I'm not sure what I am doing wrong but I run into issues making maps with mapview. I extracted distribution data from GBIF and am capable of creating a map with Leaflet (see below).

![Rplot](https://user-images.githubusercontent.com/110697614/183192901-5e71b633-e100-4ef7-83dc-157f339d8b7f.png)

However, when use the same data to create a map with mapview, the plotted data moves. Could someone tell me what I am doing wrong?

![Rplot01](https://user-images.githubusercontent.com/110697614/183192983-bcf10386-4f24-41a2-abc4-ba510f8b16d5.png)

Kind regards,

Bruno

**Comment by tim-salabim** [comment]
Hard to say what's happening, without an example that we can run to reproduce the issue.

**Comment by Bruno-mels** [comment]
I've put my code underneath: 

library(rgbif)
library(sf)
library(leaflet)
library(mapview)
parrot <- occ_data(scientificName = 'Coracopsis barklyi', hasCoordinate = TRUE, limit = 500)
dat <- parrot$data[ , c("decimalLongitude", "decimalLatitude", "species")]
dat <- na.omit(dat)
colnames(dat) <- c("latitude", "longitude", "species")
df <- as.data.frame(cbind(dat$longitude,dat$latitude))

coordinates(df) <- ~V2+V1
leaflet(df) %>% addMarkers() %>% addTiles()

sp <- SpatialPoints(coords=cbind(dat$longitude, dat$latitude), 
                    proj4string = CRS("+init=epsg:4326"))
sp$species <- dat$species
mapview(sp)

**Comment by tim-salabim** [comment]
Hi, thanks. The problem is that you are switching `latitude` and `longitude`. See below for a working solution (without using sp):

```r
library(rgbif)
library(sf)
library(mapview)

parrot <- occ_data(scientificName = 'Coracopsis barklyi', hasCoordinate = TRUE, limit = 500)
dat <- parrot$data[ , c("decimalLongitude", "decimalLatitude", "species")]
dat <- na.omit(dat)
colnames(dat) <- c("latitude", "longitude", "species") # here you are switching long and lat!!

datsf = st_as_sf(
  dat
  , coords = c("latitude", "longitude")
  , crs = 4326
)

mapview(datsf)
```

**Comment by Bruno-mels** [comment]
Ah! I see it now. Coudn't figure it out for so long. Thanks for the quick help!
