### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/mapview#446]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

And **leafem** too, please!

**Comment by tim-salabim** [comment]
Will do, thanks for the heads-up

**Comment by olivroy** [comment]
Hi, is this still planned before the deadline next Monday?

**Comment by tim-salabim** [comment]
Yes

**Comment by rsbivand** [comment]
As of now, `mapview` only incurs a NOTE that suggested package `rgdal` is missing when it is not present, so no immediate vulnerability (but vulnerable to extra checks requiring all dependencies to be on known repositories (CRAN, Bioconductor) or listed as additional repositories in `DESCRIPTION`, which is not this case. So a new version without `rgdal` would be sensible now.

**Comment by tim-salabim** [comment]
The dev version is already clean. I just need to run the general winbuilder checks etc before submission. Should be updated on CRAN by the end of the week.

**Comment by rsbivand** [comment]
Tanks for your cooperation!

**Comment by tim-salabim** [comment]
> Dear maintainer,
> 
> thanks, package mapview_2.11.2.tar.gz is on its way to CRAN.
> 
> Best regards,
CRAN teams' auto-check service
Package check result: OK
> 
> No changes to worse in reverse depends.
