### ISSUE TITLE
Toggle legends  to show/hide with layers

### ISSUE THREAD

**Issue by Newtonrific** [r-spatial/mapview#450]
With a map with multiple layers, but only one layer set to be visible on initiation (i.e. all other layers use `hide = TRUE`) the legends for all layers are shown on initiation.  If a layer is then toggled to be visible then hidden again the legend also becomes hidden with the layer. Is it possible to have the legends for hidden layers also hidden on initiation?

**Comment by jhagenauer** [comment]
Same issue here.  I would love if this could be fixed.

**Comment by tim-salabim** [comment]
Sorry for the long silence on this. It should work as expected now. Feel free to reopen if it doesn't.

**Comment by tim-salabim** [comment]
```r
library(mapview)

m1 = mapview(franconia, zcol = "district", hide = TRUE)
m2 = mapview(breweries, zcol = "founded", hide = FALSE)
m3 = mapview(franconia, zcol = "SHAPE_AREA", hide = TRUE)

m12 = m1 + m2
m12

m123 = m12 + m3
m123
```

**Comment by avaloncookpb** [comment]
Hi there, thanks for addressing this. I'm still having issues with legend behavior described above. In the example you used, I still get a legend on default for maps set hide=TRUE, depending on the order in which they are called.

```
m12 = m1+m2
m12 #returns two legends

m21 = m2 + m1
m21 #returns one legend

m123= m1 + m2 + m3
m123 #returns 2 legends

m312 = m3 + m1 + m2
m312 #returns 3 legends
```

I would expect each case to only produce one legend (one for each layer where hide=FALSE), regardless of the order of the call. 

For my specific application, I am creating layers from one dataframe in a loop. When I set hide=TRUE for all variables except one that I specify, I still end up with 3 legends by default:

```
library(mapview)

variables<-c("founded", "number.of.types", "number.seasonal.beers", "zipcode")
maps<-list()

for (i in seq_along(variables)) {
  map <- mapview(breweries, 
                 zcol = variables[i],
                 hide=ifelse(variables[i]=="founded", FALSE, TRUE)
  )
  maps[[i]] <- map
}

FinalMap<-Reduce(`+`, maps)
FinalMap
```

Thank you!

**Comment by tim-salabim** [comment]
@avaloncookpb is this with mapview from CRAN or from here?
