### ISSUE TITLE
mapview - automatic change of point/polygon/line color when switching map type

### ISSUE THREAD

**Issue by FloFranz** [r-spatial/mapview#459]
Hi there,

assume I want to plot an sf object representing polygons with mapview using more than one map type:

`mapview(franconia, map.type = c('OpenStreetMap', 'Esri.WorldImagery'),
        alpha.regions = 0, lwd = 2, color = 'black')`

Viewing the result of the map with OpenStreetMap as background map, the black color of the polygon lines is easy to see. However, when you use Esri.WorldImagery as the background map, the black lines are not very visible. White lines would be much better to see. 

Is there a way to implement this in the mapview function so that the line color automatically changes depending on the selected background map?

**Comment by FloFranz** [comment]
Dear @tim-salabim,

thank you for your reply. You're right, in the best case it would need a color for the features that is adjusted according to the luminence of the selected background map tiles. Nevertheless, I think that a predefined simple color change depending on the background map could be beneficial for some regions (dark areas like forests in a satellite map). 

Anyway, I will find a way for my purposes and mapview remains an amazing package!

**Comment by tim-salabim** [comment]
Ok, I'll close here. If you figure out a good way of achieving this, please let us know here.
