### ISSUE TITLE
datetime as default aesthetic

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/mapview#463]
there's an error from leaflet when datetime is the default column available - should this go to leaflet rather than here? 

this had us going for a while, because we're dealing with pure long,lat,time data and datetime is not handled: 

```R
v <- sf::st_as_sf(data.frame(x = 0:10, y = seq(0, 20, length.out = 11), t = Sys.time() + 0:10), coords = c("x", "y"), crs = "OGC:CRS84")
mapview(v)     

Error in dispatch(map, "fitBounds", leaflet = { : Invalid map parameter
```

It's simple enough to as.integer that and get something useful (albeit not especially meaningful)

```R
v$t <- as.integer(v$t)
mapview(v)     

```

I know that formatting this stuff would be a can of worms, but I think that's a better result than the weird error. We just wanted to see the points and how they change in time from some real tracking data. 

![image](https://github.com/r-spatial/mapview/assets/4107631/9c5a66cb-7e89-436f-899e-71d186c22153)

**Comment by tim-salabim** [comment]
Sorry for the long silence. Here's the perfect place for this issue. Should be fixed now:

![image](https://github.com/r-spatial/mapview/assets/2826432/3d43c8b5-48fb-4047-8756-9d38d397ff73)

Let me know if this now does what you'd expect.

**Comment by tim-salabim** [comment]
I'm closing this here, feel free to reopen, if you feel it's not solved.

**Comment by mdsumner** [comment]
thanks @tim-salabim !!

**Comment by edzer** [comment]
It works for a hand full of time stamps, not for more, try e.g.
```r
library(mapview)
library(sf)
pm = read.csv("http://pebesma.staff.ifgi.de/pm10/3_1a.txt") |>  
  st_as_sf(coords = c("Long", "Lat"), crs = 'OGC:CRS84')
pm$time = as.POSIXct(paste(pm$Date,pm$Time))                                                                                                                                                                                    
mapview(pm["time"])        
```
one could do a `cut` on the time column, but getting the legend labels right by default is a challenge
```r
breaks = seq(min(pm$time), max(pm$time), length.out = 16)                                                         
mapview(pm, at = breaks) # doesn't work                                                                            
pm$tc = cut(pm$time, breaks, include.lowest = TRUE, labels = substr(breaks, 12, 19)[-1])     
table(pm$tc)
mapview(pm["tc"]) 
```

**Comment by tim-salabim** [comment]
Yeah, I just realised that my self...

**Comment by edzer** [comment]
I have a similar problem in `stars` / `sf`, when times are attributes, see [here](https://github.com/r-spatial/stars/blob/main/man/figures/README-plot5-1.png) where you'd like to use the way (base) plot creates axis labels on `POSIXct`  values, only showing the part that changes.

**Comment by tim-salabim** [comment]
I think I have a solution now. Please test and let me know what you think. Essentially this is now using a `leaflet::colorNumeric` palette and uses a function to map the ticks created by that to the corresponding `format(as.POSIXct())` labels. For @edzer 's example this seems to be appropriate, especially, as we have the hover labels showing the exact datetime(s). For @mdsumner 's example one could argue that a direct mapping to the handful of datetimes we have is more desirable... If we agree that this should be implemented, which is easy enough, then we would just need an appropriate cutoff for the maximum number of datetimes to be mapped directly. My suggestion would be 12. But, again, we may not even need to bother as we have the hover labels, as mentioned before.

**Comment by tim-salabim** [comment]
BTW, @edzer what kind of wild movement data is this? A pedestrian collecting PM10 measurements? Or a UAV?

**Comment by edzer** [comment]
> BTW, @edzer what kind of wild movement data is this? A pedestrian collecting PM10 measurements? Or a UAV?



On my way to https://spatial-data-science.github.io/2024/ I'm planning to pass through Nuremberg, and will tell you over a beer, then.

**Comment by tim-salabim** [comment]
Sounds good, let me know when the date comes nearer. Looking forward to catching up!

**Comment by tim-salabim** [comment]
Ok, closing here. If anyone wants to have the solution for a small set of objects implemented, feel free to reopen
