### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by FelipeCarrillo** [r-spatial/mapview#465]
If I run mapview(franconia) it works as expected. But running it like so:
mapview(franconia)  %>% addStaticLabels(., label = franconia$NAME_ASCI)

It prints the labels but the outline of franconia goes away. Am I missing something?

**Comment by tim-salabim** [comment]
Not sure, works for me. What's your `sessionInfo()`?

**Comment by FelipeCarrillo** [comment]
- Session info ----------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 4.1.1 (2021-08-10)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       Rgui
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       America/Los_Angeles
 date     2023-12-22
 pandoc   3.1.2 @ C:\\Users\\FCARRI~1\\AppData\\Local\\Pandoc\\pandoc.exe

- Packages --------------------------------------------------------------------------------------------------------------------------------------------------------
 package           * version     date (UTC) lib source
 base64enc           0.1-3       2015-07-28 [1] CRAN (R 4.1.1)
 bitops              1.0-7       2021-04-24 [1] CRAN (R 4.1.1)
 brew              * 1.0-7       2022-02-04 [1] CRAN (R 4.1.3)
 cachem              1.0.6       2021-08-19 [1] CRAN (R 4.1.3)
 cellranger          1.1.0       2016-07-27 [1] CRAN (R 4.1.3)
 class               7.3-20      2022-01-13 [1] CRAN (R 4.1.3)
 classInt            0.4-9       2023-02-28 [1] CRAN (R 4.1.3)
 cli                 3.6.1       2023-03-23 [1] CRAN (R 4.1.3)
 codetools           0.2-18      2020-11-04 [1] CRAN (R 4.1.1)
 colorspace          2.1-0       2023-01-23 [1] CRAN (R 4.1.3)
 conflicted        * 1.2.0       2023-02-01 [1] CRAN (R 4.1.3)
 crosstalk           1.2.0       2021-11-04 [1] CRAN (R 4.1.3)
 data.table        * 1.14.8      2023-02-17 [1] CRAN (R 4.1.3)
 DBI                 1.1.3       2022-06-18 [1] CRAN (R 4.1.3)
 dichromat           2.0-0.1     2022-05-02 [1] CRAN (R 4.1.3)
 digest              0.6.31      2022-12-11 [1] CRAN (R 4.1.3)
 dplyr             * 1.1.2       2023-04-20 [1] CRAN (R 4.1.3)
 e1071               1.7-13      2023-02-01 [1] CRAN (R 4.1.3)
 ellipsis            0.3.2       2021-04-29 [1] CRAN (R 4.1.3)
 excel.link        * 0.9.11      2023-05-08 [1] CRAN (R 4.1.1)
 fansi               1.0.4       2023-01-22 [1] CRAN (R 4.1.3)
 farver              2.1.1       2022-07-06 [1] CRAN (R 4.1.3)
 fastmap             1.1.0       2021-01-25 [1] CRAN (R 4.1.3)
 forcats           * 1.0.0       2023-01-29 [1] CRAN (R 4.1.3)
 formatR           * 1.11        2021-06-01 [1] CRAN (R 4.2.0)
 generics            0.1.3       2022-07-05 [1] CRAN (R 4.1.3)
 ggmap             * 3.0.2       2023-03-14 [1] CRAN (R 4.1.3)
 ggplot2           * 3.4.2       2023-04-03 [1] CRAN (R 4.1.3)
 ggthemes          * 4.2.4       2021-01-20 [1] CRAN (R 4.1.3)
 glue                1.6.2       2022-02-24 [1] CRAN (R 4.1.3)
 gtable              0.3.3       2023-03-21 [1] CRAN (R 4.1.3)
 hms                 1.1.3       2023-03-21 [1] CRAN (R 4.1.3)
 htmltools           0.5.4       2022-12-07 [1] CRAN (R 4.1.3)
 htmlwidgets         1.6.2       2023-03-17 [1] CRAN (R 4.1.3)
 httpuv              1.6.9       2023-02-14 [1] CRAN (R 4.1.3)
 httr                1.4.5       2023-02-24 [1] CRAN (R 4.1.3)
 jpeg                0.1-9       2021-07-24 [1] CRAN (R 4.1.1)
 jsonlite            1.8.4       2022-12-06 [1] CRAN (R 4.1.3)
 KernSmooth          2.23-20     2021-05-03 [1] CRAN (R 4.1.1)
 later               1.3.0       2021-08-18 [1] CRAN (R 4.1.3)
 lattice             0.20-45     2021-09-22 [1] CRAN (R 4.1.3)
 lazyeval            0.2.2       2019-03-15 [1] CRAN (R 4.1.3)
 leafem            * 0.2.0       2022-04-16 [1] CRAN (R 4.2.0)
 leaflet           * 2.1.2       2023-03-10 [1] CRAN (R 4.1.3)
 leaflet.providers   1.9.0       2019-11-09 [1] CRAN (R 4.1.3)
 leafpop             0.1.0       2021-05-22 [1] CRAN (R 4.1.3)
 lifecycle           1.0.3       2022-10-07 [1] CRAN (R 4.1.3)
 lubridate         * 1.9.2       2023-02-10 [1] CRAN (R 4.1.3)
 magrittr            2.0.3       2022-03-30 [1] CRAN (R 4.1.3)
 mapproj             1.2.8       2022-01-12 [1] CRAN (R 4.1.3)
 maps                3.4.1       2022-10-30 [1] CRAN (R 4.1.3)
 mapview           * 2.11.0.9006 2023-06-11 [1] Github (r-spatial/mapview@0aab88f)
 markdown            1.6         2023-04-07 [1] CRAN (R 4.1.3)
 memoise             2.0.1       2021-11-26 [1] CRAN (R 4.1.3)
 mime                0.12        2021-09-28 [1] CRAN (R 4.1.1)
 munsell             0.5.0       2018-06-12 [1] CRAN (R 4.1.3)
 pacman            * 0.5.1       2019-03-11 [1] CRAN (R 4.1.3)
 pals              * 1.7         2021-04-17 [1] CRAN (R 4.1.3)
 patchwork         * 1.1.2       2022-08-19 [1] CRAN (R 4.1.3)
 pillar              1.9.0       2023-03-22 [1] CRAN (R 4.1.3)
 pkgconfig           2.0.3       2019-09-22 [1] CRAN (R 4.1.3)
 plotly            * 4.10.2      2023-06-03 [1] CRAN (R 4.1.1)
 plyr                1.8.8       2022-11-11 [1] CRAN (R 4.1.3)
 png                 0.1-7       2013-12-03 [1] CRAN (R 4.1.1)
 promises            1.2.0.1     2021-02-11 [1] CRAN (R 4.1.3)
 proxy               0.4-27      2022-06-09 [1] CRAN (R 4.1.3)
 purrr             * 1.0.1       2023-01-10 [1] CRAN (R 4.1.3)
 R6                  2.5.1       2021-08-19 [1] CRAN (R 4.1.3)
 raster              3.6-23      2023-07-04 [1] CRAN (R 4.1.1)
 RColorBrewer      * 1.1-3       2022-04-03 [1] CRAN (R 4.1.3)
 rcom              * 3.2-1       2021-11-23 [1] local
 Rcpp                1.0.10      2023-01-22 [1] CRAN (R 4.1.3)
 readr             * 2.1.4       2023-02-10 [1] CRAN (R 4.1.3)
 readxl            * 1.4.3       2023-07-06 [1] CRAN (R 4.1.1)
 RgoogleMaps         1.4.5.3     2020-02-12 [1] CRAN (R 4.1.3)
 rlang               1.1.0       2023-03-14 [1] CRAN (R 4.1.3)
 rscproxy          * 2.3-1       2018-06-12 [1] autstat (R 4.1.0)
 rstudioapi          0.15.0      2023-07-07 [1] CRAN (R 4.1.1)
 s2                  1.1.2       2023-01-12 [1] CRAN (R 4.1.3)
 satellite           1.0.4       2021-10-12 [1] CRAN (R 4.1.3)
 scales            * 1.2.1       2022-08-20 [1] CRAN (R 4.1.3)
 servr               0.26        2023-03-19 [1] CRAN (R 4.1.3)
 sessioninfo       * 1.2.2       2021-12-06 [1] CRAN (R 4.1.3)
 sf                * 1.0-14      2023-07-11 [1] CRAN (R 4.1.1)
 sos               * 2.1-7       2023-05-26 [1] CRAN (R 4.1.1)
 sp                  1.6-0       2023-01-19 [1] CRAN (R 4.1.3)
 stringi             1.7.12      2023-01-11 [1] CRAN (R 4.1.3)
 stringr           * 1.5.0       2022-12-02 [1] CRAN (R 4.1.3)
 svglite             2.1.1       2023-01-10 [1] CRAN (R 4.1.3)
 svMisc              1.2.3       2021-10-11 [1] CRAN (R 4.1.3)
 svSocket          * 1.0.2       2021-05-05 [1] CRAN (R 4.2.0)
 systemfonts         1.0.4       2022-02-11 [1] CRAN (R 4.1.3)
 terra               1.7-29      2023-04-22 [1] CRAN (R 4.1.1)
 tibble            * 3.2.1       2023-03-20 [1] CRAN (R 4.1.3)
 tidyr             * 1.3.0       2023-01-24 [1] CRAN (R 4.1.3)
 tidyselect          1.2.0       2022-10-10 [1] CRAN (R 4.1.3)
 tidyverse         * 2.0.0       2023-02-22 [1] CRAN (R 4.1.3)
 timechange          0.2.0       2023-01-11 [1] CRAN (R 4.1.3)
 TinnRcom          * 1.0.22      2021-06-21 [1] local
 tzdb                0.3.0       2022-03-28 [1] CRAN (R 4.1.3)
 units               0.8-1       2022-12-10 [1] CRAN (R 4.1.3)
 USAboundaries     * 0.4.0       2021-10-12 [1] CRAN (R 4.1.3)
 USAboundariesData   0.4.0       2022-05-18 [1] https://ropensci.r-universe.dev (R 4.1.1)
 utf8                1.2.3       2023-01-31 [1] CRAN (R 4.1.3)
 uuid                1.1-0       2022-04-19 [1] CRAN (R 4.1.3)
 vctrs               0.6.1       2023-03-22 [1] CRAN (R 4.1.3)
 viridisLite         0.4.1       2022-08-22 [1] CRAN (R 4.1.3)
 withr               2.5.1       2023-09-26 [1] CRAN (R 4.1.1)
 wk                  0.7.2       2023-03-17 [1] CRAN (R 4.1.3)
 writexl           * 1.4.2       2023-01-06 [1] CRAN (R 4.1.3)
 xfun                0.39        2023-04-20 [1] CRAN (R 4.1.3)
 yaml                2.3.7       2023-01-23 [1] CRAN (R 4.1.3)

**Comment by FelipeCarrillo** [comment]
I realized that I had and older version of mapview and leafem. I just updated to mapview 2.11.2 and leafem 0.2.3 but didn't make any difference. Are there any other packages that I need to update?

**Comment by FelipeCarrillo** [comment]
I just went ahead and updated to R-4.2.3 and has the latest mapview and leafem. I still not getting the outline of franconia, I only get the labels. What could I be missing?

**Comment by tim-salabim** [comment]
Maybe leaflet? I am on

```leafem_0.2.3   leaflet_2.2.1  mapview_2.11.2```

**Comment by FelipeCarrillo** [comment]
It won't work at all while using the Rconsole. I switched to Rstudio and it works well now. I wonder why addStaticLabels doesn't work with the Rconsole standalone.

**Comment by tim-salabim** [comment]
Ah, I see. If you're not using RStudio, you will need to set `mapviewOptions(fgb = FALSE)` (once for the session) before creating the map. Default print method for `leaflet` maps outside of RStudio is to just display the `index.html` temp file and that won't allow cross-origin (CORS) calls on the website (which we do when using `fgb = TRUE`. In RStudio, the map is served via `localhost` so CORS generally works.

**Comment by FelipeCarrillo** [comment]
Problem solved. Thanks Tim
