### ISSUE TITLE
npts reports values for more features than expected

### ISSUE THREAD

**Issue by lvalnegri** [r-spatial/mapview#468]
Hello,

I have the attached `sf` object  [1003.zip](https://github.com/r-spatial/mapview/files/14011188/1003.zip) of three features:
```
Simple feature collection with 3 features and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 7.247586 ymin: 45.30151 xmax: 7.333099 ymax: 45.31725
Geodetic CRS:  WGS 84
# A tibble: 3 × 3
  livello                                                                                geometry   CMN
* <chr>                                                                        <MULTIPOLYGON [°]> <dbl>
1 H       (((7.256099 45.30256, 7.256145 45.30273, 7.256399 45.30299, 7.256773 45.30322, 7.256...  1003
2 L       (((7.256099 45.30256, 7.256145 45.30273, 7.256399 45.30299, 7.256773 45.30322, 7.256...  1003
3 M       (((7.256099 45.30256, 7.256145 45.30273, 7.256399 45.30299, 7.256773 45.30322, 7.256...  1003
```
for which running
```
y |> mapview::npts(TRUE)
```
returns:
```
 [1]  24  26   9 421   6  24  26   9 452   6  24  26   9 487   6
```
Am I right in thinking I should expect three values only?

Thanks.

**Comment by tim-salabim** [comment]
What is this data? The file inside the archive is merely called `1003`... Is it a `rds` file? Without knowing how to read it, I cannot help

**Comment by lvalnegri** [comment]
> What is this data? The file inside the archive is merely called `1003`... Is it a `rds` file? Without knowing how to read it, I cannot help

oh, sorry, my bad. yes, it's `rds`.

**Comment by tim-salabim** [comment]
Your data are 3 `MULTIPOLYGONS` with 5 `POLYGONS` each, hence the npts vector of length 15:

``` r
library(sf)
#> Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE

jnk = readRDS("/home/tim/Downloads/1003.rds")

length(st_geometry(jnk))
#> [1] 3
lengths(st_geometry(jnk))
#> [1] 5 5 5
```

<sup>Created on 2024-01-23 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
