### ISSUE TITLE
Mapview is wrapping data of different UTM zones in a single UTM zone

### ISSUE THREAD

**Issue by biswasdibyendu** [r-spatial/mapview#470]
I have movement data spread over UTM zone 44N and 43N (shp file) downloaded from MoveBank. It is being plotted perfectly in ArcGIS Pro and in R just by plotting the shp file.  Then while using Mapview to check the data on the map, I found the locations after a certain longitude (at the western boundary) are being moved and being mapped on much eastern side as shown in the pictures.  And the subsequent analysis also gave the wrong result. A chunk of data is actually straddling. Mapview is wrapping the data to fit in the UTM zone extent and won't let me have records outside the zone 44N.
![Screenshot (152)](https://github.com/r-spatial/mapview/assets/60889962/d161938d-ba15-4cf6-8550-a282d0b37492)

**Comment by tim-salabim** [comment]
I am not sure I follow. Can you provide a reproducible example? Are things plotted correctly if you set `native.crs = TRUE`?

**Comment by biswasdibyendu** [comment]
@tim-salabim I tried that too. But not working. Same problem occurring with function "move.obj" from package "move".

**Comment by tim-salabim** [comment]
I don't think I can help you, unless you provide a reproducible example

**Comment by biswasdibyendu** [comment]
HI @tim-salabim . I think the problem is not with Mapview, rather it is a projection problem in R itself. So I am closing this question here. and will put in some other platform. Thank You for you time and consideration.
