### ISSUE TITLE
Plot only the last raster in mapview

### ISSUE THREAD

**Issue by agronomofiorentini** [r-spatial/mapview#474]
Dear Contributors,

I have a question. 

If I have a raster stack where I have 5 bands and I would like to start the map with all 5 layers in the map but have only the last of those layers displayed.

I would like to start a map as follow.

<img width="594" alt="Screenshot 2024-03-15 104238" src="https://github.com/r-spatial/mapview/assets/66969646/1f44a9e8-bb4e-4111-97b8-587b3f858872">

is there a option or function that i can use?

Maybe we can use the following code in order to do so.

```
library(plainview)

mapview(poppendorf, legend = TRUE)
```

**Comment by tim-salabim** [comment]
Thanks for raising. A fix should be straight forward, time is the issue.

**Comment by tim-salabim** [comment]
This should work now and be much more versatile:

```
library(mapview)
library(plainview)

nms = names(poppendorf)

# hide all but first layer
mapview(poppendorf, hide = TRUE)

# hide first layer - equivalent for other layers
mapview(poppendorf, hide = 1)
mapview(poppendorf, hide = nms[1])

# hide all but last layer
mapview(poppendorf, hide = 1:4)
mapview(poppendorf, hide = nms[1:4])

# hide arbitrary layers
mapview(poppendorf, hide = c(1, 3, 5))
mapview(poppendorf, hide = nms[c(2, 4, 5)])
```

Please let me know if it now does what you'd expect
