### ISSUE TITLE
mapview for inherited classes

### ISSUE THREAD

**Issue by bart1** [r-spatial/mapview#475]
It seems that classes that inherit `sf` do not get recognized by `mapview`. In my case the `move2` class (representing movement data) . It would be great to have mapview work for inherited classes, is there some way of achieving this? Alternative a separate method can be set (e.g.  `setMethod('mapView', signature(x = 'move2'), .sf_method)`, however that seems a less general solution. If desirable I can provide a patch for the later solution.

Current error:
``` r
require(mapview)
#> Loading required package: mapview
#> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
#> which was just loaded, will retire in October 2023.
#> Please refer to R-spatial evolution reports for details, especially
#> https://r-spatial.org/r/2023/05/15/evolution4.html.
#> It may be desirable to make the sf package available;
#> package maintainers should consider adding sf to Suggests:.
#> The sp package is now running under evolution status 2
#>      (status 2 uses the sf package in place of rgdal)
require(move2)
#> Loading required package: move2
data<-mt_read(mt_example())[1:100,]
mapview(data)
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'mapView' for signature '"move2"'
```

**Comment by bart1** [comment]
Now thinking a bit more about it maybe a `ANY` methods can be used to dispatch to inherited classes?

**Comment by tim-salabim** [comment]
Could the method be defined in `move2`?

**Comment by edzer** [comment]
`mapview` dispatches to `mapView` which has methods for classes. As it uses S4, S3 classes need to be declared as such. Did you set `setOldClass("move2")` in the packages?

**Comment by bart1** [comment]
@edzer thank you for the hint, I already had set `setOldClass("move2")` that did not do the trick but diving a bit deeper into it if I set `setOldClass(c("move2","sf"))` that seems to work. I will check that is does not have unintended consequences but that seems quite a general solution to make many `sf` methods work.
