### ISSUE TITLE
Undefined Cartesian SRS

### ISSUE THREAD

**Issue by hyapici** [r-spatial/mapview#476]
I am very very new to mapview interface and maybe this is something extremely easy to solve. However, here's my problem: I am trying to map a certain list of points using:

`mapview(data, xcol = "x (longitude)", ycol= "y (latitude)")
`
and I am getting:

```
writing: substituting ENGCRS["Undefined Cartesian SRS with unknown unit"] for missing CRS
writing: substituting ENGCRS["Undefined Cartesian SRS with unknown unit"] for missing CRS
writing: substituting ENGCRS["Undefined Cartesian SRS with unknown unit"] for missing CRS
```

data points are displayed just fine, but the map is missing. What am I doing wrong?

Thank you very much for your assistance.

**Comment by tim-salabim** [comment]
best would be to turn the data into an `sf` object by using `sf::st_as_sf`. This function allows you to set the CRS which will then be used to transform to webmercator and place the data on a map. Note, when you have a `sf` object, you don't nee to specify `xcol` and `ycol` anymore (as the sf object is aware of these)

**Comment by hyapici** [comment]
Thank you for the quick response. Now I have successfully converted my data to `sf` object but still no map under the points. I tried to set CRS for data as in:

`https://tmieno2.github.io/R-as-GIS-for-Economists/turning-a-data-frame-of-points-into-an-sf.html#fnref48`

however now I am getting the error:

`basestation_sf <- st_set_crs(basestation_sf, 1057) 
Warning message:
In CPL_crs_from_input(x) :
  GDAL Error 1: PROJ: proj_create_from_database: crs not found`

any help will be much appreciated

**Comment by edzer** [comment]
`EPSG:1057` is not a recognized projection.

**Comment by hyapici** [comment]
I thought each code corresponds to a specific region of the world map. when I used 4269 instead of 1057, the problem is solved, and the map displays correctly. Thank you very much for your prompt and insightful answers.
