### ISSUE TITLE
Error in h(simpleError(msg, call))

### ISSUE THREAD

**Issue by kristianunger** [r-spatial/mapview#484]
Hi Markus,

I recently ran into the following error when running

It's the latest PureCN version 2.11.0 as part of the the docker image kristianunger/purecndocker:0624 

singularity run -B purecndocker_0624.sif Rscript $PURECN/PureCN.R --out $OUT/$SAMPLEIDOUT \
    --tumor $covout/${SAMPLEID}_coverage_loess.txt.gz \
    --fun-segmentation PSCBS \
    --sampleid $SAMPLEID \
    --vcf $INPUT_VCF \
    --statsfile $statsfile \
    --normaldb $normal_db/normalDB_agilent_v6_hg38.rds \
    --intervals $baits \
    --snpblacklist $srr \
    --genome hg38 \
    --postoptimize \
    --model betabin \
    --force --seed 123

 INFO [2024-06-02 14:48:31] Segmenting data...
INFO [2024-06-02 14:48:32] Interval weights found, will use weighted PSCBS.
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'median': non-numeric argument to mathematical function
Calls: runAbsoluteCN ... .log_level -> layout -> median -> .handleSimpleError -> h
In addition: Warning message:
In .bcfHeaderAsSimpleList(header) :
  duplicate keys in header will be forced to unique rownames
Execution halted

Can you give me an idea what might be the problem?

Best wishes

Kristian

**Comment by tim-salabim** [comment]
Who is Markus? And how is this a mapview issue?

**Comment by kristianunger** [comment]
Apologies! I raised the issue here by mistake. Wrong tab in the browser. It was supposed to be posted at the git for PureCN (Markus Riester).

**Comment by tim-salabim** [comment]
No worries
