### ISSUE TITLE
problem when passing layerId (mapview_2.11.2.9000)

### ISSUE THREAD

**Issue by cedricbriandgithub** [r-spatial/mapview#489]
```r
library(mapview)
mapView(franconia, layerId=franconia$NUTS_ID)
```
> Error in validateScalarName(name) : 
>  Invalid argument 'name' (must be a non-empty character string and contain no '/' or '\')

```r
traceback()
```

> 10: stop("Invalid argument '", name, "' (must be a non-empty character string and contain no '/' or '\\')")
> 9: validateScalarName(name)
> 8: htmltools::htmlDependency(name = layerId, version = "0.0.1", 
>        src = c(file = data_dir), attachment = data_file)
> 7: fileAttachment(path_layer, layerId)
> 6: leafem::addFgb(map = m, file = fl, radius = cex, weight = lwd, 
>        opacity = alpha, fillOpacity = alpha.regions, color = color, 
>        fillColor = col.regions, popup = popup, label = label, group = layer.name, 
>        fill = ifelse(getGeometryType(x) == "ln", FALSE, TRUE), className = "mapview-popup", 
>        scale = scaleList, options = leaflet::pathOptions(pane = pane), 
>        ...) at fgb.R#187
> 5: sfFgb(x = x, map = map, pane = pane, zcol = zcol, color = color, 
>        col.regions = col.regions, at = at, na.color = na.color, 
>        cex = cex, lwd = lwd, alpha = alpha, alpha.regions = alpha.regions,  >       map.types = map.types, verbose = verbose, popup = popup, 
 >       layer.name = layer.name, label = label, legend = legend, 
>        legend.opacity = legend.opacity, homebutton = homebutton, 
>        native.crs = native.crs, highlight = highlight, maxpoints = maxpoints, 
>        attributes = sf2DataFrame(x, drop_sf_column = TRUE), canvas = canvas, 
>        viewer.suppress = viewer.suppress, hide = hide, ...) at sf.R#64
> 4: leaflet_sf(x, map = map, pane = pane, zcol = zcol, color = color, 
>        col.regions = col.regions, at = at, na.color = na.color, 
>        cex = cex, lwd = lwd, alpha = alpha, alpha.regions = alpha.regions, 
>        na.alpha = na.alpha, map.types = map.types, verbose = verbose, 
>        popup = popup, layer.name = layer.name, label = label, legend = legend, 
>        legend.opacity = legend.opacity, homebutton = homebutton, 
>        native.crs = native.crs, highlight = highlight, maxpoints = maxpoints, 
>        canvas = canvas, viewer.suppress = viewer.suppress, hide = hide,  >       ...) at mapView.R#742
>  3: .local(x, ...)
>  2: mapView(franconia, layerId = franconia$NUTS_ID) at mapView.R#2
>  1: mapView(franconia, layerId = franconia$NUTS_ID)

**Comment by cedricbriandgithub** [comment]
locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

time zone: Europe/Paris
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] leafem_0.2.3        htmltools_0.5.8.1   mapview_2.11.2.9000
[4] rj_4.0.10-2         safer_0.2.1

**Comment by tim-salabim** [comment]
This currently only works if you set `mapviewOptions(fgb = FALSE)`

**Comment by cedricbriandgithub** [comment]
Thanks
