### ISSUE TITLE
mapview can't install

### ISSUE THREAD

**Issue by weathermiya** [r-spatial/mapview#490]
1. use R package > install > search "mapview"
but can't find this package to install
Warning in install.packages :
  package ‘mapview’ is not available (for R version 3.4.1)

2. use remotes::install_github("r-spatial/mapview") then has ERROR: this R is version 3.4.1, package 'mapview' requires R >= 3.6.0

On the premise that R is not updated, how can I install this package?
thanks.

**Comment by tim-salabim** [comment]
I guess you need to install an older version with e.g. `remotes::install_version()`

**Comment by weathermiya** [comment]
> I guess you need to install an older version with e.g. `remotes::install_version()`

Thanks, but maybe I will try updating my R version. 
My R version is really too old...

**Comment by tim-salabim** [comment]
If that is an option, I'd recommend it, yes! Closing here, feel free to re-open if you still have problems with the new R version
