### ISSUE TITLE
mapview() didn't work with dev package version

### ISSUE THREAD

**Issue by KrysD** [r-spatial/mapview#50]
Hi, 

I was using mapview with the CRAN package (`mapview_1.2.0`) to render map with large spatial line dataframe.

I wanted to use this package in shiny and see in the issues that i have to switch to the dev package from the gith. 

First of all using `renderMapview` and `mapviewOutput` doesnt show anything in my shinyApp. 
Here is the code i used : 

```
#UI side
mapviewOutput("mapBM",width = "100%",height = 600)

#server side
map <- mapview(mydata) #mydata is the spatialLineDataframe
output$mapBM <- renderMapview({map})
```
then when i tried to show the map in Rstudio with the function `mapview(mydata)` like with the CRAN package version but the function is running in loop showing neither result nor error.

**Comment by tim-salabim** [comment]
There is a general issue with `renderMapview` (see also https://github.com/environmentalinformatics-marburg/mapview/issues/58). For now I suggest using `renderLeaflet` together with the `@map` slot of the mapview object.

**Comment by tim-salabim** [comment]
closing here as I think using the above remedy for mapview objects (using @map inside renderLeaflet) is an acceptable way of handling things in shiny
