### ISSUE TITLE
Red circles in latticeView sync mode

### ISSUE THREAD

**Issue by mtennekes** [r-spatial/mapview#51]
I almost got `latticeView` working in `tmap`. It really works like charm, thanks!

One small thing: in `sync` mode, the red "cursor" circles are not only visible when the cursor hovers over  another facet (as it is supposed to be), but also when the cursor is outside the facets, or when the cursor hovers over the same facet as the red circle. These red "idle" circles are placed in the center of the map.

This problem only seem to appear with leaflet objects, not with mapview objects, at least in this example:

    l1 <- leaflet() %>% addProviderTiles("CartoDB.Positron")
    l2 <- leaflet() %>% addProviderTiles("OpenStreetMap")
    sync(l1, l2)

![image](https://cloud.githubusercontent.com/assets/2444081/21294944/d1ac1b56-c549-11e6-845d-753f35d81799.png)

    m1 <- mapview()
    m2 <- mapview()
    sync(m1, m2)

![image](https://cloud.githubusercontent.com/assets/2444081/21294965/5e7e7ff6-c54a-11e6-80bd-08ca0bf38d0a.png)

**Comment by mtennekes** [comment]
I found out that the same issue occurs with mapview objects. The idle circles are always placed at lan=0 and lon=0.

**Comment by tim-salabim** [comment]
Yes, I also noticed this. And you are right, it is always located at 0/0.
This stems, afaik, from the underlying JS plugin and I don't think we can do much about it. I will double-check the plugin side and maybe @timelyportfolio can also confirm this?

**Comment by tim-salabim** [comment]
I am closing this here even though this is still not resolved. However, I don't intend to address this before leaflet is upgraded to 1.x which will mean that we need to upgrade the plugin too. If this issue then still persists I will try to look into it again.
