### ISSUE TITLE
Cannot establish dependency in renderMapview

### ISSUE THREAD

**Issue by happyshows** [r-spatial/mapview#58]
for example, if I insert req(val <- input$my_slider) to the code chunk.

```
Listening on http://127.0.0.1:5822
Warning: Error in .getReactiveEnvironment()$currentContext: Operation not allowed without an active reactive context. (You tried to do something that can only be done from inside a reactive expression or observer.)
Stack trace (innermost first):
    56: .getReactiveEnvironment()$currentContext
    55: .subset2(x, "impl")$get
    54: $.reactivevalues
    53: $
    52: eval
    51: eval
    50: inherits
    49: isTruthy
    48: fun_
    47: dotloop
    46: req
    45: slot [/Users/showsle/R/InefficientInv/server.R#50]
    44: mapview2leaflet
    43: renderMapview
    42: server [/Users/showsle/R/InefficientInv/server.R#49]
     1: runApp
Error in .getReactiveEnvironment()$currentContext() : 
  Operation not allowed without an active reactive context. (You tried to do something that can only be done from inside a reactive expression or observer.)
```

package version 1.2.0

**Comment by timelyportfolio** [comment]
Unfortunately, this is not nearly enough code to say that `mapview` is the source of the error.  Whenever we req(input$*), we can get this error if not in proper context.  Please provide more detail.

**Comment by happyshows** [comment]
please find the minimal example below. I don't think it's caused by value assignment

```
library(mapview)
library(shiny)

server <- function(input, output) {
  output$test <- renderMapview({
    req(input$obs)
    isolate({
      browser()
    })
  })
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      sliderInput("obs", "Number of observations:", min = 10, max = 500, value = 100)
    ),
    mainPanel(
      mapviewOutput('test')
    )
  )
)

shinyApp(ui = ui, server = server)
```

**Comment by timelyportfolio** [comment]
Ok, that helps.  I am guessing this [line](https://github.com/environmentalinformatics-marburg/mapview/blob/f6a67f6415672342020f6818030c0d596a661b39/R/print-methods.R#L23) is the soruce of the trouble.  Although not technically correct, we can get working by isolating the `req`.

```
library(mapview)
library(shiny)

server <- function(input, output) {
  output$test <- renderMapview({
    isolate({req(input$obs)})
    mapview(breweries91)
  })
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      sliderInput("obs", "Number of observations:", min = 10, max = 500, value = 100)
    ),
    mainPanel(
      mapviewOutput('test')
    )
  )
)

shinyApp(ui = ui, server = server)
```

**Comment by timelyportfolio** [comment]
One other "hacky" way to workaround for now is demonstrated below.

```
library(mapview)
library(shiny)

server <- function(input, output) {
  output$test <- renderLeaflet({
    req(input$obs)
    rws <- input$obs
    mapview(breweries91[1:rws,])@map
  })
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      sliderInput("obs", "Number of observations:", min = 1, max = nrow(breweries91@data), value = nrow(breweries91@data))
    ),
    mainPanel(
      leafletOutput('test')
    )
  )
)

shinyApp(ui = ui, server = server)
```

**Comment by happyshows** [comment]
Thanks for the prompt help. I'd like to keep this issue open so that others might refer to this ticket before the formal resolution arrives.

**Comment by timelyportfolio** [comment]
Agree that we should keep open.

**Comment by tim-salabim** [comment]
The line you are referring to was my attempt to adapt [renderLeaflet](https://github.com/rstudio/leaflet/blob/master/R/shiny.R#L29) to mapview. I see now that this is not the way to do this. The problem is that we cannot pass a valid htmlwidget to `renderMapview` as `expr` as `mapview` objects are S4 objects, hence the line to convert to a valid `leaflet` htmlwidget. If my understanding of environments is correct, we would need to evaluate `expr` in the current (i.e. functions) environment - where `expr` after conversion to leaflet is a valid htmlwidget - rather that the default `parent.frame()`.

**Comment by tim-salabim** [comment]
@timelyportfolio do you have any idea how to get this working, i.e. have a valid `renderMapview` definition?

**Comment by tim-salabim** [comment]
Can we accept that mapview slot @map is a leaflet object and thus in shiny we should use renderLeaflet? If not, feel free to reopen
