### ISSUE TITLE
Problem with loading the library

### ISSUE THREAD

**Issue by michsvob** [r-spatial/mapview#74]
In an attempt to load the library I get the following error:

```r
Error: package or namespace load failed for 'mapview' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgdal/libs/rgdal.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgdal/libs/rgdal.so, 6): Library not loaded: /Builds/unix/recipes/build/gdal-2.1.3-obj/libgdal.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgdal/libs/rgdal.so
  Reason: image not found
```
Installation of the package (v 1.2) proceeded without errors.
This is my sessionInfo():
```r
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] leaflet_1.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10     lattice_0.20-35  codetools_0.2-15 digest_0.6.12    foreach_1.4.3    mime_0.5         grid_3.4.0      
 [8] R6_2.2.0         xtable_1.8-2     magrittr_1.5     sp_1.2-4         raster_2.5-8     iterators_1.0.8  tools_3.4.0     
[15] htmlwidgets_0.8  crosstalk_1.0.0  shiny_1.0.3      httpuv_1.3.3     compiler_3.4.0   htmltools_0.3.6 
```

I tried also installing from tar.gz as well as an installing older version 1.1, but with no difference.

**Comment by tim-salabim** [comment]
Did you try this in a fresh R session?

**Comment by michsvob** [comment]
I did, but it did not help. Could the problem be that when installing the package following is printed out?

Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/mapview_1.2.0.tgz'
Content type 'application/x-gzip' length 2839105 bytes (2.7 MB)
==================================================
downloaded 2.7 MB

tar: Failed to set default locale

The downloaded binary packages are in
	/var/folders/9n/8xq29v0d3bd1bdxknb3c51z80000gn/T//RtmpNMSJxp/downloaded_packages

**Comment by tim-salabim** [comment]
I don't know. According to the error there seems to be a problem with **rgdal**. Could you try to update GDAL to version 2.1.0, update **rgdal** and try again? You also might want to try the latest develop version via
```r devtools::install_github("environmentalinformatics-marburg/mapview@develop")```

**Comment by michsvob** [comment]
Thanks, but this did not help either. I was not able to load library rgdal. The problem might be on my side, I don't know...

**Comment by edzer** [comment]
The second error message has nothing to to with the first. From the first, it seems that you installed `rgdal` from source. If so, have you tried to install `rgdal` from binary?

**Comment by gisma** [comment]
To me it seems to be a problem of the GDAL sharred libs. It may help to install GDAL 2.x via 
[Homebrew-osgeo4mac](https://github.com/OSGeo/homebrew-osgeo4mac)

**Comment by michsvob** [comment]
Thank you for the suggestions. I tried installing also from binary, but it didn't help. As to installing from homebrew I was not quite sure what I should do, so I tried running following commands on terminal: brew tap osgeo/osgeo4mac and brew install gdal2, which apparently installed a lot of things, but didn't help either.

**Comment by tim-salabim** [comment]
@michsvob do you still have problems installing? Or can i close this?

**Comment by michsvob** [comment]
Hi, I was not able to install that using the provided solutions, but I solved my original problem using another approach, so I don’t need a solution any more and don’t really have much time for testing. I suppose people don’t have the problem often, so you can close the topic. 

Thanks a lot anyway.

**Comment by tim-salabim** [comment]
Thanks for the quick reply!

**Comment by jleape** [comment]
I am having the same issue. @michsvob, do you mind sharing your solution?

**Comment by michsvob** [comment]
> I am having the same issue. @michsvob, do you mind sharing your solution?

Sorry, I don't remember any more what I needed to achieve back then. I suppose, I might have just used leaflet library instead of this one.

**Comment by jleape** [comment]
Gotcha. Trying some different GDAL installs, but I may just use leaflet, too. Thanks for the quick reply.

**Comment by jleape** [comment]
In my case it was unable to load systemfonts. Installing XQuartz seems to have solved it: https://www.xquartz.org/
