### ISSUE TITLE
Is a CRAN release forthcoming?

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/mapview#75]
Hi,

I'd like to use mapview in teach a course 1-5 June, with sf. Is it likely that a new version will be submitted to CRAN in time, or could you provide a Windows binary package (R >=3.4) or should I (try to) build one myself?

**Comment by tim-salabim** [comment]
The next version is release ready and I will upload to CRAN soon, most likely this weekend. Is this OK?

**Comment by rsbivand** [comment]
Excellent! Thanks for the information, please keep me updated on progress.

**Comment by tim-salabim** [comment]
windows binaries of mapview 2.0.1 are on CRAN so I'm closing this issue

**Comment by rsbivand** [comment]
Great, thanks!
