### ISSUE TITLE
Plain NEWS file additional to NEWS.md

### ISSUE THREAD

**Issue by pat-s** [r-spatial/mapview#76]
Hi Tim,

in previous versions you had a plan `NEWS` file and now you switched to `NEWS.md`. Unfortunately, the latter is not supported from R's `news()` function or from RStudios 'packages'  tab :/ 

We are currently facing the same issue whether to maintain two (redundant) news files. I'm wondering why there is no function in CRAN which converts `NEWS.md` to a plain `NEWS` file.

**Comment by tim-salabim** [comment]
Thanks for the heads-up. Fixed now. We use https://github.com/environmentalinformatics-marburg/Rsenal/blob/master/R/bumpVersion.R to take care of versioning. This now assumes a NEWS.md file to be present and will then write a plain NEWS file with bumped version when running `Rsenal::bumpVersion()`. So no need for taking care of 2 NEWS files. Note that this is currently only implemented for strict major.minor.patch semantic. Though I guess it could easily be adapted to other versioning schemes.
