### ISSUE TITLE
mapshot: Error in system.file: 'package' must be of length 1

### ISSUE THREAD

**Issue by KillianDudduss** [r-spatial/mapview#77]
Hello, 

I've been trying to make one of your function work into an R scrpit that I was writing but the thing is that when I'm trying to make a snapshot of my leaflet map with mapshot, the error "Error in system.file: 'package' must be of length 1" is triggered??? 

Do you have a clue how to fix this or no clue at all ?

**Comment by tim-salabim** [comment]
I have not seen this error before. A reproducible example would be helpful. And your sessionInfo()

**Comment by KillianDudduss** [comment]
Yeah no problem, sorry for the late reply, the reproducible example is this : `###################
#### Library ######
###################
library(leaflet)
library(shiny)
library(shinyjs)
library(mapview)
library(raster)
library(htmlwidgets)
###################
getwd()
setwd("D:\\R")

elevationFRA <- getData("alt", country = "FRA")
elevationLUX <- getData("alt",country = "LUX")

################################
front <- boundaries(elevationLUX)
x1 <- front@extent@xmin
y1 <- front@extent@ymin

x2 <- front@extent@xmax
y2 <- front@extent@ymax

xmil <- (x2+x1)/2
ymil <- (y2+y1)/2

ydist <- (y2-y1)

zoomLevel <- setZoomBound(ydist)
################################

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      actionButton(inputId = "button",
                   label = "coucou"),
      actionButton(inputId= "snapshot",
                   label = "Take a snapshot!")
    ),
    mainPanel(
      leafletOutput("mymap"),
      tableOutput("table")
    )
    #)
  )
)


server <- function(input, output) {
  
  output$mymap <- renderLeaflet({
    leaflet()%>%
      #################
      addProviderTiles(providers$OpenStreetMap, options = providerTileOptions(zIndex=-10)) %>%
      #################
      setView(lng = xmil,
              lat = ymil,
              zoom = zoomLevel[1]) %>%
      addRasterImage(x = elevationLUX,
                     opacity = 0.8,
                     colors = rainbow(25, alpha = 0.8),
                     layerId = "elevLux")
  })
  
  #######################
  # Boutton ajout marker
  #######################
  observeEvent(input$button, {
    leafletProxy("mymap") %>%
      addMarkers(lat = 45.777222,
                 lng = 3.087025,
                 "btn") %>%
      addCircles(layerId = "circle",
                 lat =45.777222,
                 lng =3.087025,
                 radius = 20000,
                 color = "red",
                 fillColor = "red")
    
  })
  
  #########################
  # Ajout des markers a la volee
  #########################
  cpt_click <- 0
  
  observeEvent(input$mymap_click, {
    leafletProxy("mymap") %>%
      addMarkers(lng = input$mymap_click$lng,
                 lat = input$mymap_click$lat,
                 layerId = paste0("marker",cpt_click))
    cpt_click <<- cpt_click+1
    
    output$table <- renderTable({
      options(digits=3)
      data.frame(LONG = format(input$mymap_click$lng,nsmall = 3),
                 LAT =format(input$mymap_click$lat,nsmall = 3))
    })
  })
  
  #########################
  # Suppression des markers
  observeEvent(input$mymap_marker_click, {
    leafletProxy("mymap") %>%
      removeMarker(layerId = input$mymap_marker_click$id)
  })
  
  #########################
  # Prendre une snapshot de la map
  
  observeEvent(input$snapshot, {
    leafletProxy("mymap") %>%
      mapshot(file = "D:\\R\\data\\snapshot01.png")
  })
}

shinyApp(ui = ui, server = server)


`

And my sessionInfo() is : `sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] LeafletGoogle_0.0.0.9000 htmlwidgets_0.8          mapview_2.0.1           
 [4] shinyjs_0.9              leaflet_1.1.0.9000       shiny_1.0.3             
 [7] raster_2.5-8             sp_1.2-4                 RMySQL_0.10.11          
[10] DBI_0.6-1               

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10      plyr_1.8.4        R.methodsS3_1.7.1 base64enc_0.1-3   R.utils_2.5.0    
 [6] iterators_1.0.8   tools_3.3.3       gdalUtils_2.0.1.7 digest_0.6.12     jsonlite_1.4     
[11] satellite_0.2.0   lattice_0.20-34   viridisLite_0.2.0 png_0.1-7         foreach_1.4.3    
[16] crosstalk_1.0.0   yaml_2.1.14       rgdal_1.2-6       stats4_3.3.3      grid_3.3.3       
[21] webshot_0.4.0     sf_0.4-2          R6_2.2.0          udunits2_0.13     magrittr_1.5     
[26] scales_0.4.1      codetools_0.2-15  htmltools_0.3.6   units_0.4-4       mime_0.5         
[31] xtable_1.8-2      colorspace_1.3-2  httpuv_1.3.3      miniUI_0.1.1      munsell_0.4.3 `

**Comment by KillianDudduss** [comment]
`library(leaflet)
library(shiny)
library(shinyjs)
library(mapview)
library(raster)
library(htmlwidgets)

getwd()
setwd("D:\\R")

elevationFRA <- getData("alt", country = "FRA")
elevationLUX <- getData("alt",country = "LUX")

front <- boundaries(elevationLUX)
x1 <- front@extent@xmin
y1 <- front@extent@ymin

x2 <- front@extent@xmax
y2 <- front@extent@ymax

xmil <- (x2+x1)/2
ymil <- (y2+y1)/2

ydist <- (y2-y1)

zoomLevel <- setZoomBound(ydist)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      actionButton(inputId = "button",
                   label = "coucou"),
      actionButton(inputId= "snapshot",
                   label = "Take a snapshot!")
    ),
    mainPanel(
      leafletOutput("mymap"),
      tableOutput("table")
    )
    #)
  )
)


server <- function(input, output) {
  
  output$mymap <- renderLeaflet({
    leaflet()%>%
      #################
      addProviderTiles(providers$OpenStreetMap, options = providerTileOptions(zIndex=-10)) %>%
      #################
      setView(lng = xmil,
              lat = ymil,
              zoom = zoomLevel[1]) %>%
      addRasterImage(x = elevationLUX,
                     opacity = 0.8,
                     colors = rainbow(25, alpha = 0.8),
                     layerId = "elevLux")
  })
  
  observeEvent(input$button, {
    leafletProxy("mymap") %>%
      addMarkers(lat = 45.777222,
                 lng = 3.087025,
                 "btn") %>%
      addCircles(layerId = "circle",
                 lat =45.777222,
                 lng =3.087025,
                 radius = 20000,
                 color = "red",
                 fillColor = "red")
    
  })

  cpt_click <- 0
  observeEvent(input$mymap_click, {
    leafletProxy("mymap") %>%
      addMarkers(lng = input$mymap_click$lng,
                 lat = input$mymap_click$lat,
                 layerId = paste0("marker",cpt_click))
    cpt_click <<- cpt_click+1
    
    output$table <- renderTable({
      options(digits=3)
      data.frame(LONG = format(input$mymap_click$lng,nsmall = 3),
                 LAT =format(input$mymap_click$lat,nsmall = 3))
    })
  })
  
  observeEvent(input$mymap_marker_click, {
    leafletProxy("mymap") %>%
      removeMarker(layerId = input$mymap_marker_click$id)
  })
  
  observeEvent(input$snapshot, {
    leafletProxy("mymap") %>%
      mapshot(file = "D:\\R\\data\\snapshot01.png")
  })
}

shinyApp(ui = ui, server = server)


`

**Comment by tim-salabim** [comment]
If you replace 

```r
observeEvent(input$snapshot, {
    leafletProxy("mymap") %>%
    mapshot(file = "D:\R\data\snapshot01.png")
}
```
with
```r
observeEvent(input$snapshot, {
    leaflet() %>% addTiles() 
    mapshot(file = "D:\R\data\snapshot01.png")
}
```
it works. 

Therefore, I don't see how this is a mapview issue. It seems to be related to `leafletProxy`.
I suggest you ask this question on StackOverflow.

**Comment by StevenMMortimer** [comment]
I have posted this as a question on StackOverflow here: https://stackoverflow.com/questions/51334762/return-a-rendered-leaflet-map-from-leafletproxy

The `mapshot()` function only works with a `leaflet` object, but `leafletProxy()` doesn't return one like `leaflet()` does. `leafletProxy` returns an object of `leaflet_proxy`, which is handled differently in the backend of leaflet even though these two commands function in a similar way. For example, these two commands have the same behavior but are routed differently in the leaflet code: 

- `leaflet() %>% addTiles()`
- `leafletProxy("mapId") %>% addTiles()`
