### ISSUE TITLE
Change legend name - bug?

### ISSUE THREAD

**Issue by andreasLD** [r-spatial/mapview#78]
How can I change the legend name in the following mapview-output?

    require(mapview)
    mapview(breweries91,
    zcol = 'founded',
    at = seq(1400, 2200, 200),
    legend = TRUE,
    layer.name = 'Year')

In the legend title I want to have 'Year' written instead of 'Year founded' without changing the column name in breweries91. Logically I'd expect this from the layer.name parameter. However it just adds to the column name.

**Comment by tim-salabim** [comment]
This should now work as expected

**Comment by aleszu** [comment]
Hi folks, any idea how to change the date format here so years aren't showing up in legend as 1,400 and 2,000?
