### ISSUE TITLE
Integrate sf classes into mapview

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/mapview#80]
https://github.com/edzer/sfr

sf is a new approach to geographic data that is extremely promising. It is very likely that we will all transition towards sf as a replacement of sp soon, and mapview (and leaflet) should support sf objects natively.

**Comment by tim-salabim** [comment]
They do! See here https://github.com/r-spatial/mapview/blob/master/NEWS.md

**Comment by adrfantini** [comment]
That's A W E S O M E! 
Thanks!
I was looking at the docs here:
https://environmentalinformatics-marburg.github.io/mapview/introduction.html
but it seems that that page has not been updated for a while.

**Comment by tim-salabim** [comment]
Yeah, I should remove that one and link to the new online documentation at https://r-spatial.github.io/mapview/
