### ISSUE TITLE
plainView() does not support addMouseCoordinates()

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/mapview#81]
As per the title, it would be useful if one could identify mouse coordinates (and values under the mouse) even when in plainview mode, in units of X-Y.

**Comment by tim-salabim** [comment]
Agreed. Yet not that easy to realize. Coordinates (i.e. row and column indices) should be easy, raster values is something that we've banged our heads about for a long time...

**Comment by adrfantini** [comment]
I understand. I bult an application for on-line editing of raster files
(mainly netCDF) and had to work around that too. (I had a popup come up
when a point was clicked).
Still X-Y would already be pretty useful!

2017-05-23 16:55 GMT+02:00 tim-salabim <notifications@github.com>:

**Comment by tim-salabim** [comment]
XY Position information is now provided in plainview

**Comment by adrfantini** [comment]
Awesome!

**Comment by tim-salabim** [comment]
I'm going to close this here. Values under the mouse will be revisited when we turn to the stars.
