### ISSUE TITLE
Error in mapview (conflict in arguments)

### ISSUE THREAD

**Issue by babaknaimi** [r-spatial/mapview#89]
The new problem is the following error:

mapview(spatiaPointDF,zcol='fieldname',radius = 10)

Error in (function (map, lng = NULL, lat = NULL, radius = 10, layerId = NULL,  : 
  formal argument "radius" matched by multiple actual arguments

**Comment by tim-salabim** [comment]
Please always try to provide a reproducible example.
mapview has no argument `radius`. It has argument `cex` to control point size, so when you set
```r
library(mapview)
mapview(breweries91, zcol = "founded", cex = 10)
```
things will behave the way you want.

**Comment by babaknaimi** [comment]
Sorry for that. In fact, it is mentioned that other arguments can be passed to some functions line addCircle through ..., and radius, fillOpacity etc. are for example such arguments that I wanted to try, but I got that error. I thought it is clear what the error means and just wanted you to know. Anyway, thanks for your response. Cheers, Babak
