### ISSUE TITLE
maximum image zoom?

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/mapview#90]
Is there a maximum image zoom for images?  leaflet disables the zoom in after 5 clicks for poppendorf on my defice, mapview keeps zooming but the image disappears. I need to be able to go a bit closer than this - is it a mapview or leaflet setting? 

```R
library(leaflet)
library(mapview)
## click zoom "+" until it's locked, ~5 clicks
leaflet() %>% leaflet::addRasterImage(poppendorf[[1]])

## click zoom "+" until the image disappears, ~6 clicks
 mapview(poppendorf)
```

Thanks!

**Comment by tim-salabim** [comment]
@mdsumner in mapview we allow for scrolling past the standard `maxZoom` setting (19 I think - see [these lines](https://github.com/r-spatial/mapview/blob/master/R/leafletControls.R#L171-L177)). This works for vector data sets which are rendered in svg (and is helpful for examining sliver polygons etc). I think the fact that rasters are not rendered beyond this zoom is related to [this issue](https://github.com/rstudio/leaflet/issues/371) - especially @jcheng5 's second comment.
You can always use `plainview()` for rasters to zoom into infinity. Obviously without a background map, but these usually only render until zoom levels of 18/19 anyway.

**Comment by mdsumner** [comment]
Great thanks! plainView is my destiny in more ways than one ;)

**Comment by EDiLD** [comment]
Can this be reopened? It try to digitize some aeral images using `mapedit`. However, the raster disappear at Zoom-level 18 :(

**Comment by tim-salabim** [comment]
@EDiLD I know they do disappear. But this is really a leaflet issue until they provide a possibility to adjust the zoom levels for `addRasterImage`. I am fairly sure that this will become possible when leaflet 2.0 is released (soon).

**Comment by EDiLD** [comment]
Thanks @tim-salabim I have a possible fix here: https://github.com/rstudio/leaflet/issues/507

**Comment by tim-salabim** [comment]
Let the leaflet developers decide that. They are about to release a backward breaking change anyway, so I don't think it matters much.

**Comment by EDiLD** [comment]
Thanks for the input. PR created, let's see what they say...

**Comment by andzandz11** [comment]
How can I force the maximum/minimum zoomlevel by user supplied parameter?
