### ISSUE TITLE
multiple slideView in flexdashboard

### ISSUE THREAD

**Issue by pdbentley** [r-spatial/mapview#95]
Hey, thanks for your great work. i am trying to add multiple slideView calls to a dashboard. While a single use works, when i try two it does not. I suspect the same calls or ids are being used. 

This works for a single

        ---
        title: "timeline"
        output:
          flexdashboard::flex_dashboard:
            self_contained: true
            orientation: columns
            theme: readable
            vertical_layout: fill
            navbar:
              - {title: "Reload Board", href: 'javascript:history.go(0)', align: right}
        
        ---
        
        
        
        slideView1 { data-icon="fa-map-o"}
        =====================================  
        
        
        Column {data-width=300}
        --------------------------------
        ### map 1
        
        ```{r}
        
        ### raster data ###
        library(sp)
        library(raster)
        library(mapview)
        
        # data(poppendorf)
        
        stck1 <- subset(poppendorf, c(3, 4, 5))
        stck2 <- subset(poppendorf, c(2, 3, 4))
        slideView(stck1, stck2)
        
        
        
        ```
        
        

And this does not work for a double

        ---
        title: "timeline"
        output:
          flexdashboard::flex_dashboard:
            self_contained: true
            orientation: columns
            theme: readable
            vertical_layout: fill
            navbar:
              - {title: "Reload Board", href: 'javascript:history.go(0)', align: right}
        
        ---
        
        
        slideView1 { data-icon="fa-map-o"}
        =====================================  
        
        
        Column {data-width=300}
        --------------------------------
        ### map 1
        
        ```{r}
        
        ### raster data ###
        library(sp)
        library(raster)
        library(mapview)
        
        # data(poppendorf)
        
        stck1 <- subset(poppendorf, c(3, 4, 5))
        stck2 <- subset(poppendorf, c(2, 3, 4))
        slideView(stck1, stck2)
        
        
        
        ```
        
        
        
        
        Column {data-width=300}
        --------------------------------
        ### map 2
        
        ```{r}
        
        ### raster data ###
        library(sp)
        library(raster)
        library(mapview)
        
        # data(poppendorf)
        
        stck1 <- subset(poppendorf, c(3, 4, 5))
        stck2 <- subset(poppendorf, c(2, 3, 4))
        slideView(stck1, stck2)
        
        
        
        ```

Any thoughts on way around this?

**Comment by tim-salabim** [comment]
@pdbentley sorry for taking so long to reply!
I suggest to use package [widgetframe](https://github.com/bhaskarvk/widgetframe) for situations where you have multiple htmlwidgets in one dashboard. 
As for your example, when you set `self_contained: false` in your yaml header, then the slideviews are rendered. 
There is, however, still an issue with the naming of the image files that are being written to disk and then used in `slideview` making it impossible to show more than two different images at the moment (in the example below you will only see the two images from the second subset call as the images created from the first are being overwritten. I will try to fix this soon.

```r
---
title: "timeline"
output:
  flexdashboard::flex_dashboard:
    self_contained: false
    orientation: columns
    theme: readable
    vertical_layout: fill
    navbar:
    - {title: "Reload Board", href: 'javascript:history.go(0)', align: right}
---
    
    
slideView1 { data-icon="fa-map-o"}
=====================================  
    
    
Column {data-width=300}
-------------------------------
### map 1
    
```{r}

### raster data ###
library(sp)
library(raster)
library(mapview)
library(widgetframe)
    
# data(poppendorf)

stck1 <- subset(poppendorf, c(3, 4, 5))
stck2 <- subset(poppendorf, c(5, 1, 3))
sv1 = slideView(stck1, stck2)
frameWidget(sv1)


```
    
    
    
    
Column {data-width=300}
--------------------------------
### map 2
    
```{r}
    
### raster data ###
library(sp)
library(raster)
library(mapview)

# data(poppendorf)

stck1 <- subset(poppendorf, c(3, 4, 5))
stck2 <- subset(poppendorf, c(1, 3, 2))
sv2 = slideView(stck1, stck2)
frameWidget(sv2)


```
```

**Comment by tim-salabim** [comment]
This should be resolved now. When I run

---
title: "timeline"
output:
  flexdashboard::flex_dashboard:
    self_contained: false
    orientation: columns
    theme: readable
    vertical_layout: fill
    navbar:
    - {title: "Reload Board", href: 'javascript:history.go(0)', align: right}
---
    
    
slideView1 { data-icon="fa-map-o"}
=====================================  
    
    
Column {data-width=300}
-------------------------------
### map 1
    
```{r}

### raster data ###
library(sp)
library(raster)
library(mapview)
library(widgetframe)
    
# data(poppendorf)

stck1 <- subset(poppendorf, c(3, 4, 5))
stck2 <- subset(poppendorf, c(5, 1, 3))
sv1 = slideView(stck1, stck2)
frameWidget(sv1)


```
    
    
    
    
Column {data-width=300}
--------------------------------
### map 2
    
```{r}
    
### raster data ###
library(sp)
library(raster)
library(mapview)

# data(poppendorf)

stck3 <- subset(poppendorf, c(5, 1, 3))
stck4 <- subset(poppendorf, c(1, 3, 2))
sv2 = slideView(stck3, stck4)
frameWidget(sv2)


```
