### ISSUE TITLE
slideView multiple images

### ISSUE THREAD

**Issue by pdbentley** [r-spatial/mapview#96]
Hey, 

WIth slideView, is it possible to have more than two images? I would like to add several images, but give the viewer the choice of which two images to compare. Through shiny it should be possible. But what an rmd or non-shiny flexdashboard? For context i am building html reports for various projects, and am focusing on embedded approaches to interaction, so people can have their own copy instead of visiting a website.

**Comment by tim-salabim** [comment]
No, this is currently not possible. I am not sure how much work it would be to enable something like a layer switcher. @swoellauer is this possible and if so how much effort would it be?

**Comment by tim-salabim** [comment]
Closing this. Feel free to reopen. This is currently not high on my priority list, but I may look into it in the future.
