### ISSUE TITLE
mapView error when simple features contain ZM dimensions

### ISSUE THREAD

**Issue by kent37** [r-spatial/mapview#99]
For example:

```
library(sf)
library(mapview)

t = st_as_sfc("LINESTRING ZM (-71.433917 42.593903 4250 1498623425.8, -71.433355 42.594131 4250 1498623426.8)", crs=4326)
mapView(t)
## Error in if (length(nms) != n || any(nms == "")) stop("'options' must be a fully named list, or have no names (NULL)") : 
##  missing value where TRUE/FALSE needed
        
mapView(st_zm(t)) # works
```

**Comment by tim-salabim** [comment]
Coincidentally, in response to https://github.com/r-spatial/mapview/issues/98 I pushed a fix for this today https://github.com/r-spatial/mapview/commit/c41df1ec34d1cdc4bf9623f55ed8979dd5f1dd89
Hence, with `devtools::install_github("r-spatial/mapview@develop")` this should no longer fail.

**Comment by tim-salabim** [comment]
sorry, just realised that the earlier fix was only for class `sf`. https://github.com/r-spatial/mapview/commit/7372c3ccbd8df91f84d87ac86236b6181c43563e should fix this for class `sfc` as well

**Comment by kent37** [comment]
Cool thank you!

**Comment by kent37** [comment]
BTW if you need real-world XYZM data let me know; mine is airplane flight tracks.

**Comment by tim-salabim** [comment]
Yes, at some stage we (whoever that may be) will want to progress towards 3d data representation straight from R. I'll keep this in mind thanks!

**Comment by mdsumner** [comment]
@kent37 I'd like to try your data in my hypertidy/rangl repo for plotting with rgl,  it's been latent for a while but ready for general use -  still a bit buggy no doubt,  I hadn't tried any xyz sf data yet

**Comment by kent37** [comment]
@mdsumner OK give me a few days, I'll get you something.

**Comment by kent37** [comment]
@mdsumner Attached is a zipped shapefile containing 144 flight tracks of aircraft departing runway 33L at Boston Logan airport on June 28, 2017. Data is from an ADS-B recorder so it is kind of rough. Each point includes lat, lon, altitude in feet and time in EDT. Unzip and read with
st_read('tracks.shp')
[tracks.zip](https://github.com/r-spatial/mapview/files/1294520/tracks.zip)

If you are making interactive 3D visualizations of such things I'm interested :-)
